### ISSUE TITLE
[Discussion]: Importing remaining patches from FastTrack fork

### ISSUE THREAD

**Issue by sumghai** [CombatExtended-Continued/CombatExtended#10]
The following is a TODO list of compatibility patches that still need to be migrated from the defunct CE: FastTrack Edition fork, and updated to CE 2.0 standards:
* [x] Alpha Animals (#65)
* [x] Forsakens (#13)
* [ ] Kenshi Hiver Race
* [ ] Kenshi Shek Race
* [ ] Kenshi Skeleton Race
* [x] More Vanilla Turrets (#134)
* [x] NewRatkinPlus (#93)
* [ ] Warhammer: Gor

Mods whose patch implementations were dubious or otherwise need to be rewritten from the ground up:
* Rimworld of Magic 
* Star Wars - Factions 
  * Patches missed final FT release deadline
* [Ods] Great War German Uniforms 
  * Revamp of various Ods WWII uniform mods

Mods that have not yet been updated for RimWorld 1.1, and whose patches will not be imported:
* Flommel
* Spidercamp's Dog Pack

**Comment by sumghai** [comment]
@zhrocks11 @N7Huntsman - With regard to More Vanilla Turrets, I'd like to hold off on bringing over the fixes for #1162 and #1165, at least until the general CE turret bugs have been fixed.

**Comment by Juanfrank** [comment]
I don't know if I'm supposed to post this here, but I'm working with the Alpha Animals patch alongside Breadbox2k19. And currently in the playtest change until completely functional before I do a PR to this repo.

**Comment by sumghai** [comment]
@Juanfrank - I'm more than happy for you and Breadbox2k19 to have a crack at Alpha Animals! To help speed things up for you, here's the current FastTrack implementation for your reference:

[CEFT_old_patches_Alpha_Animals.zip](https://github.com/CombatExtended-Continued/CombatExtended/files/4496216/CEFT_old_patches_Alpha_Animals.zip)

**Comment by onigamii** [comment]
#13 is done

**Comment by N7Huntsman** [comment]
I've submitted #93 with a patch for NewRatkinPlus, based on an updated version of my patch. We can discuss desired balance/content adjustments the FT version makes as needed.

**Comment by sumghai** [comment]
> I've submitted #93 with a patch for NewRatkinPlus, based on an updated version of my patch. We can discuss desired balance/content adjustments the FT version makes as needed.
Nice, thanks!

By the way, have the turret-related issues with CE been resolved? At some point I'd like to revisit the More Vanilla Turret patches.

**Comment by Breadbox2k19** [comment]
I don’t think those kenshi racial patches need any update whatsoever since they are xml only. Same goes for the warhammer gor patch.

**Comment by Breadbox2k19** [comment]
Can you post all the old compatibility patches here? Updating it for 1.1 is trivial is it’s xml only.

**Comment by sumghai** [comment]
@N7Huntsman has already made a PR for his implementation of NewRatkinPlus, so I am going to defer to his version instead of the FT one.

[CEFT_old_patches_Kenshi_races.zip](https://github.com/CombatExtended-Continued/CombatExtended/files/4681728/CEFT_old_patches_Kenshi_races.zip) - these should be split up into individual faction/race folders

[CEFT_old_patches_Warhammer_Gor_races.zip](https://github.com/CombatExtended-Continued/CombatExtended/files/4681741/CEFT_old_patches_Warhammer_Gor_races.zip)

I will rewrite the More Vanilla Turret patches from scratch once the turret bugs in CE have been fixed.

As for the other patches, those are so horribly outdated, we're better off redoing them from scratch and not as a FastTrack project.

**Comment by sumghai** [comment]
Ratkin patches have been merged into the repo.

**Comment by N7Huntsman** [comment]
@sumghai While pre-existing issue with turrets not functioning has been resolved, fixing it has caused another issue related to reloading them for some turrets to the surface. There's no current estimate on that particular one being fixed, but I don't believe it is quite as problematic as the previous bug. It'd be up to you whether you think it'll prevent you from working on the MVT patch, but I should think you'd be able to do all typical functionality checks.

**Comment by N7Huntsman** [comment]
Closed for the time being, since I haven't heard from @sumghai for a while. Will reopen if/when he gets back in touch.
