### ISSUE TITLE
[Bug]: Revia patch failure on 8/25 update

### ISSUE THREAD

**Issue by Mortagonus** [CombatExtended-Continued/CombatExtended#1009]
**Title should be:** [Bug]: Patch failure on Rimworld booting with latest Revia patch

**Specifications**
Please provide the following.

Rimworld version: 1.3
Combat Extended version: Latest official
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10

**Description**
Provide a concise description of the issue or concern. What happened?
I receive a patch operation failure red error on load after newest Revia update from today 8/25

**Expected behavior**
No red error and patch failure

**To reproduce**
Startup Rimworld

[Combat Extended] Patch operation Verse.PatchOperationSequence(count=1, lastFailedOperation=Verse.PatchOperationFindMod(Revia Race)) failed
file: C:\Applications\Steam\steamapps\workshop\content\294100\1631756268\Patches\Revia Race\ThingDefs_Races\Race_Revia.xml
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.PatchOperation:Complete (string)
Verse.PatchOperationSequence:Complete (string)
Verse.LoadedModManager:ClearCachedPatches ()
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Fixed by #1039
