### ISSUE TITLE
[Bug]: Extracted trees are not selectable

### ISSUE THREAD

**Issue by Greysa** [CombatExtended-Continued/CombatExtended#1045]
**Specifications**
Please provide the following.

Rimworld version:  1.3.3102
Combat Extended version: 1.3.4.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win 10 64 bit
Your mod list: 

[Mod list length: 124]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Animal Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=712141500]
Animals Logic [https://steamcommunity.com/sharedfiles/filedetails/?id=1098354593]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Factions Expanded - Insectoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2149755445]
Vanilla Factions Expanded - Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2329011599]
Vanilla Factions Expanded - Medieval [https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450]
Vanilla Achievements Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2288125657]
Vanilla Weapons Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360]
Vanilla Weapons Expanded - Grenades [https://steamcommunity.com/sharedfiles/filedetails/?id=2194472657]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
Better Pawn Control [https://steamcommunity.com/sharedfiles/filedetails/?id=1541460369]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
CM Color Coded Mood Bar [1.1+] [https://steamcommunity.com/sharedfiles/filedetails/?id=2006605356]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
Chemicals & Neutroamine [https://steamcommunity.com/sharedfiles/filedetails/?id=765351437]
Collapser [https://steamcommunity.com/sharedfiles/filedetails/?id=1499847220]
Colony Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=715565262]
Door Mat [https://steamcommunity.com/sharedfiles/filedetails/?id=1505423207]
Draggable Corners [https://steamcommunity.com/sharedfiles/filedetails/?id=2014036648]
Dubs Bad Hygiene [https://steamcommunity.com/sharedfiles/filedetails/?id=836308268]
Common Sense [https://steamcommunity.com/sharedfiles/filedetails/?id=1561769193]
Dubs Break Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=1722398508]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
Expanded Prosthetics and Organ Engineering [https://steamcommunity.com/sharedfiles/filedetails/?id=725956940]
EPOE No Table [https://steamcommunity.com/sharedfiles/filedetails/?id=2210925683]
JecsTools [https://steamcommunity.com/sharedfiles/filedetails/?id=932008009]
Psychology (unofficial) v1.1-1.3 [https://steamcommunity.com/sharedfiles/filedetails/?id=2016263135]
EdB Prepare Carefully [https://steamcommunity.com/sharedfiles/filedetails/?id=735106432]
Enemy Self Preservation [https://steamcommunity.com/sharedfiles/filedetails/?id=2006638530]
Faction Raid Cooldown [https://steamcommunity.com/sharedfiles/filedetails/?id=2345845316]
Fertile Fields [1.1] [https://steamcommunity.com/sharedfiles/filedetails/?id=2012735237]
Follow Me [https://steamcommunity.com/sharedfiles/filedetails/?id=715759739]
Giddy-up! Core [https://steamcommunity.com/sharedfiles/filedetails/?id=1216999901]
Giddy-up! Battle Mounts [https://steamcommunity.com/sharedfiles/filedetails/?id=1217001091]
Giddy-up! Caravan [https://steamcommunity.com/sharedfiles/filedetails/?id=1253251478]
Giddy-up! Ride and Roll [https://steamcommunity.com/sharedfiles/filedetails/?id=1331961995]
Grazing Lands [https://steamcommunity.com/sharedfiles/filedetails/?id=1770268130]
Heat Map [https://steamcommunity.com/sharedfiles/filedetails/?id=947972722]
Humanoid Alien Races [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
More Faction Interaction (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2379076640]
Hospitality [https://steamcommunity.com/sharedfiles/filedetails/?id=753498552]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
Jobs of Opportunity (While You're Up) [https://steamcommunity.com/sharedfiles/filedetails/?id=2034960453]
Mad Skills [https://steamcommunity.com/sharedfiles/filedetails/?id=731111514]
Medical Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=715565817]
MendAndRecycle [https://steamcommunity.com/sharedfiles/filedetails/?id=735241897]
Milkable Muffalo [1.2] [https://steamcommunity.com/sharedfiles/filedetails/?id=2019852283]
Misc. Training [https://steamcommunity.com/sharedfiles/filedetails/?id=717575199]
More Than Capable [https://steamcommunity.com/sharedfiles/filedetails/?id=1803932954]
No One Left Behind [https://steamcommunity.com/sharedfiles/filedetails/?id=2401146569]
Non-Flammable Metal (1.0-1.3) [https://steamcommunity.com/sharedfiles/filedetails/?id=1259296818]
People Can Change [https://steamcommunity.com/sharedfiles/filedetails/?id=1257561308]
QualityBuilder [https://steamcommunity.com/sharedfiles/filedetails/?id=754637870]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
Real Ruins [https://steamcommunity.com/sharedfiles/filedetails/?id=1552146295]
RimHUD [https://steamcommunity.com/sharedfiles/filedetails/?id=1508850027]
Recipe icons [https://steamcommunity.com/sharedfiles/filedetails/?id=1616643195]
Relations Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=709317151]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
Royalty Tweaks [https://steamcommunity.com/sharedfiles/filedetails/?id=2018384424]
RunAndGun [https://steamcommunity.com/sharedfiles/filedetails/?id=1204108550]
Show Draftees Weapon [https://steamcommunity.com/sharedfiles/filedetails/?id=1690978457]
ShowModDesignators [https://steamcommunity.com/sharedfiles/filedetails/?id=1399212509]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
Stabilize [https://steamcommunity.com/sharedfiles/filedetails/?id=2023407836]
Tech Advancing [https://steamcommunity.com/sharedfiles/filedetails/?id=735268789]
Vanilla Animals Expanded — Arid Shrubland [https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626]
Vanilla Animals Expanded — Australia [https://steamcommunity.com/sharedfiles/filedetails/?id=1963681588]
Vanilla Animals Expanded — Boreal Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364938]
Vanilla Animals Expanded — Cats and Dogs [https://steamcommunity.com/sharedfiles/filedetails/?id=1823540489]
Vanilla Animals Expanded — Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849183875]
Vanilla Animals Expanded — Endangered [https://steamcommunity.com/sharedfiles/filedetails/?id=2366589898]
Vanilla Animals Expanded — Extreme Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849184079]
Vanilla Animals Expanded — Ice Sheet [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364782]
Vanilla Animals Expanded — Temperate Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=2260502331]
Vanilla Animals Expanded — Tropical Rainforest [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283872]
Vanilla Animals Expanded — Tropical Swamp [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283935]
Vanilla Animals Expanded — Tundra [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364585]
Vanilla Apparel Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817]
Vanilla Armour Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282]
Vanilla Books Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2193152410]
Vanilla Brewing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2186560858]
Vanilla Brewing Expanded - Coffees and Teas [https://steamcommunity.com/sharedfiles/filedetails/?id=2275449762]
Vanilla Cooking Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519]
Vanilla Cooking Expanded - Stews [https://steamcommunity.com/sharedfiles/filedetails/?id=2134312965]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Vanilla Cooking Expanded - Sushi [https://steamcommunity.com/sharedfiles/filedetails/?id=2158539170]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
Vanilla Expanded - Royalty Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2260012940]
Vanilla Factions Expanded - Settlers [https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119]
Vanilla Factions Expanded - Vikings [https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285]
Vanilla Furniture Expanded - Art [https://steamcommunity.com/sharedfiles/filedetails/?id=1968134023]
Vanilla Furniture Expanded - Farming [https://steamcommunity.com/sharedfiles/filedetails/?id=1957158779]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded - Power [https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Furniture Expanded - Props and Decor [https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
Vanilla Plants Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308522]
Vanilla Plants Expanded - Succulents [https://steamcommunity.com/sharedfiles/filedetails/?id=2198652536]
Vanilla Storytellers Expanded - Empress Evil [https://steamcommunity.com/sharedfiles/filedetails/?id=2149702528]
Vanilla Storytellers Expanded - Freya Fierce [https://steamcommunity.com/sharedfiles/filedetails/?id=2231483525]
Vanilla Storytellers Expanded - Igor Invader [https://steamcommunity.com/sharedfiles/filedetails/?id=2249879548]
Vanilla Storytellers Expanded - Perry Persistent [https://steamcommunity.com/sharedfiles/filedetails/?id=2149702069]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
Vanilla Traits Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2296404655]
Vanilla Weapons Expanded - Coilguns [https://steamcommunity.com/sharedfiles/filedetails/?id=2375692535]
Vanilla Weapons Expanded - Heavy Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2329126791]
Vanilla Weapons Expanded - Laser [https://steamcommunity.com/sharedfiles/filedetails/?id=1989352844]
Vanilla Weapons Expanded - Quickdraw [https://steamcommunity.com/sharedfiles/filedetails/?id=1906780517]
Wall Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208]
Work Tab [https://steamcommunity.com/sharedfiles/filedetails/?id=725219116]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
[KV] Trading Spot [https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658]
RocketMan - Performance Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928]

**Description**
Extracted trees are not selectable after extraction, and are therefore not plantable. The icon is there on the map, it cannot be selected though.

**Expected behavior**
Extracted trees should be selectable and therefore replantable.

**To reproduce**
Start new game, extract tree.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x ] Confirmed that my game version and load order are correct.
- [ ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Fixed in the most recent release.
