### ISSUE TITLE
[Bug]: Can only Refill Vanilla Apparel Expanded's Mini-Turret Pack using FMJ Ammo

### ISSUE THREAD

**Issue by Whyareuhere** [CombatExtended-Continued/CombatExtended#1049]
Specifications
Please provide the following.

Rimworld version: 1.3.3102
Combat Extended version: 1.3.4.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win 10 64 bit
Your mod list:

[Mod list length: 59]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Factions Expanded - Insectoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2149755445]
Vanilla Factions Expanded - Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=2329011599]
Vanilla Factions Expanded - Medieval [https://steamcommunity.com/sharedfiles/filedetails/?id=2023513450]
Vanilla Achievements Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2288125657]
Vanilla Weapons Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360]
Vanilla Weapons Expanded - Grenades [https://steamcommunity.com/sharedfiles/filedetails/?id=2194472657]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
Vanilla Animals Expanded — Arid Shrubland [https://steamcommunity.com/sharedfiles/filedetails/?id=1836900626]
Vanilla Animals Expanded — Australia [https://steamcommunity.com/sharedfiles/filedetails/?id=1963681588]
Vanilla Animals Expanded — Boreal Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364938]
Vanilla Animals Expanded — Cats and Dogs [https://steamcommunity.com/sharedfiles/filedetails/?id=1823540489]
Vanilla Animals Expanded — Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849183875]
Vanilla Animals Expanded — Endangered [https://steamcommunity.com/sharedfiles/filedetails/?id=2366589898]
Vanilla Animals Expanded — Extreme Desert [https://steamcommunity.com/sharedfiles/filedetails/?id=1849184079]
Vanilla Animals Expanded — Ice Sheet [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364782]
Vanilla Animals Expanded — Temperate Forest [https://steamcommunity.com/sharedfiles/filedetails/?id=2260502331]
Vanilla Animals Expanded — Tropical Rainforest [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283872]
Vanilla Animals Expanded — Tropical Swamp [https://steamcommunity.com/sharedfiles/filedetails/?id=1907283935]
Vanilla Animals Expanded — Tundra [https://steamcommunity.com/sharedfiles/filedetails/?id=1895364585]
Vanilla Apparel Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817]
Vanilla Armour Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814988282]
Vanilla Books Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2193152410]
Vanilla Brewing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2186560858]
Vanilla Brewing Expanded - Coffees and Teas [https://steamcommunity.com/sharedfiles/filedetails/?id=2275449762]
Vanilla Cooking Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519]
Vanilla Cooking Expanded - Stews [https://steamcommunity.com/sharedfiles/filedetails/?id=2134312965]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Vanilla Cooking Expanded - Sushi [https://steamcommunity.com/sharedfiles/filedetails/?id=2158539170]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
Vanilla Expanded - Royalty Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2260012940]
Vanilla Factions Expanded - Settlers [https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119]
Vanilla Factions Expanded - Vikings [https://steamcommunity.com/sharedfiles/filedetails/?id=2231295285]
Vanilla Furniture Expanded - Art [https://steamcommunity.com/sharedfiles/filedetails/?id=1968134023]
Vanilla Furniture Expanded - Farming [https://steamcommunity.com/sharedfiles/filedetails/?id=1957158779]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded - Power [https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Furniture Expanded - Props and Decor [https://steamcommunity.com/sharedfiles/filedetails/?id=2102143149]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Spacer Module [https://steamcommunity.com/sharedfiles/filedetails/?id=2028381079]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
Vanilla Plants Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308522]
Vanilla Plants Expanded - Succulents [https://steamcommunity.com/sharedfiles/filedetails/?id=2198652536]
Vanilla Storytellers Expanded - Empress Evil [https://steamcommunity.com/sharedfiles/filedetails/?id=2149702528]
Vanilla Storytellers Expanded - Freya Fierce [https://steamcommunity.com/sharedfiles/filedetails/?id=2231483525]
Vanilla Storytellers Expanded - Igor Invader [https://steamcommunity.com/sharedfiles/filedetails/?id=2249879548]
Vanilla Storytellers Expanded - Perry Persistent [https://steamcommunity.com/sharedfiles/filedetails/?id=2149702069]
Vanilla Textures Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2016436324]
Vanilla Traits Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2296404655]
Vanilla Weapons Expanded - Coilguns [https://steamcommunity.com/sharedfiles/filedetails/?id=2375692535]
Vanilla Weapons Expanded - Heavy Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2329126791]
Vanilla Weapons Expanded - Laser [https://steamcommunity.com/sharedfiles/filedetails/?id=1989352844]
Vanilla Apparel Expanded - Accessories [https://steamcommunity.com/sharedfiles/filedetails/?id=2521176396]
Vanilla Weapons Expanded - Quickdraw [https://steamcommunity.com/sharedfiles/filedetails/?id=1906780517]
RocketMan - Performance Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928]

Description
Mini-turret pack in Vanilla Aparrel Expanded - Accessories only accepts FMJ ammo of the same type as the regular mini-turrets. Makes it ineffective in fights against enemies with some form of heavy armor following standard bullet behavior.

Expected behavior
Mini-turret pack should be able to refilled of different ammo types (AP, HE, AP-I, etc.).

To reproduce
Start new game, wear mini-turret pack, fire until empty, attempt to reload. Only FMJ ammo is able to refill it.

Complete the following checklist
I hereby verify that I have done the following:

[x ] Confirmed that my game version and load order are correct.
 Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
 Confirmed I am not running any mods with known incompatibilities with Combat Extended.
[ x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Not really a bug, just a limitation of the way the patch for the turret was implemented.
