### ISSUE TITLE
[Bug]: CE incorrectly replaces Hospitality Guest's inventory

### ISSUE THREAD

**Issue by ewyncliffe** [CombatExtended-Continued/CombatExtended#1056]
Rimworld version: 1.3
Combat Extended version: Sep 7 Latest Steam Version
Combat Extended source Steam
Your operating system: Windows
Your mod list:

[Mod list length: 98]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
SRTS Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1845423808]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
JecsTools [https://steamcommunity.com/sharedfiles/filedetails/?id=932008009]
Humanoid Alien Races [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
HD Pawn Rendering [https://steamcommunity.com/sharedfiles/filedetails/?id=2538746878]
RimHUD [https://steamcommunity.com/sharedfiles/filedetails/?id=1508850027]
Map Designer [https://steamcommunity.com/sharedfiles/filedetails/?id=2111424996]
Map Edit Tools [https://steamcommunity.com/sharedfiles/filedetails/?id=1796223954]
Map Reroll [https://steamcommunity.com/sharedfiles/filedetails/?id=761315214]
Pack Mules Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1501052499]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
SpeakUp [https://steamcommunity.com/sharedfiles/filedetails/?id=2502518544]
More Faction Interaction (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2379076640]
Stack XXL [https://steamcommunity.com/sharedfiles/filedetails/?id=826366050]
[SYR] Individuality [https://steamcommunity.com/sharedfiles/filedetails/?id=1497105115]
Expectations Modifier [https://steamcommunity.com/sharedfiles/filedetails/?id=1904336011]
Mechanoids Extraordinaire [https://steamcommunity.com/sharedfiles/filedetails/?id=1106719215]
Durable Clothes (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2015395963]
Incident Disabler [https://steamcommunity.com/sharedfiles/filedetails/?id=2347633285]
Mad Skills [https://steamcommunity.com/sharedfiles/filedetails/?id=731111514]
Cash Register [https://steamcommunity.com/sharedfiles/filedetails/?id=2506046833]
Gastronomy [https://steamcommunity.com/sharedfiles/filedetails/?id=2279786905]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Halo UNSC Weapon Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=1542254108]
Pocket Sand [https://steamcommunity.com/sharedfiles/filedetails/?id=2226330302]
Won hair_women  [https://steamcommunity.com/sharedfiles/filedetails/?id=1886150617]
What the hack?! [https://steamcommunity.com/sharedfiles/filedetails/?id=1505914869]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
Archotech+ (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2270493883]
Artillery Gun [https://steamcommunity.com/sharedfiles/filedetails/?id=2481466772]
Enable Oversized Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2543371889]
Android tiers [https://steamcommunity.com/sharedfiles/filedetails/?id=1386412863]
Android tiers - TX Series [https://steamcommunity.com/sharedfiles/filedetails/?id=2010528561]
Android Tiers SM7 Overhaul (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2572407779]
Biosculpter Reworked [https://steamcommunity.com/sharedfiles/filedetails/?id=2560741422]
Carry Capacity Fixed [https://steamcommunity.com/sharedfiles/filedetails/?id=1906760965]
Character Editor [https://steamcommunity.com/sharedfiles/filedetails/?id=1874644848]
Combat Extended Guns [https://steamcommunity.com/sharedfiles/filedetails/?id=1582570547]
Combat Extended Melee [https://steamcommunity.com/sharedfiles/filedetails/?id=1924933379]
Combat Readiness Check (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2314304057]
Dress Patients [https://steamcommunity.com/sharedfiles/filedetails/?id=1667901146]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
Eccentric Extras - Angel Hairs [https://steamcommunity.com/sharedfiles/filedetails/?id=2014890320]
Eccentric Tech - Core [https://steamcommunity.com/sharedfiles/filedetails/?id=2552623545]
Eccentric Tech - Angel Apparel [https:// no link (local mod)]
Eccentric Extras - Signature Gear [https:// no link (local mod)]
Eccentric Tech - Advanced Shields [https:// no link (local mod)]
Eccentric Tech - Cosmetic Modifications 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2552628984]
Eccentric Tech - Flares 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2552628275]
Eccentric Tech - Foxy's Armory 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=2552628608]
Elite Bionics Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=1665403571]
Erin's Hairstyles - Redux [https://steamcommunity.com/sharedfiles/filedetails/?id=2361911135]
EvolvedOrgansRedux [https://steamcommunity.com/sharedfiles/filedetails/?id=2424381146]
Expanded Prosthetics and Organ Engineering - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=1949064302]
EPOE-Forked: Royalty DLC expansion [https://steamcommunity.com/sharedfiles/filedetails/?id=2008970276]
Medical System Expansion 2 [https://steamcommunity.com/sharedfiles/filedetails/?id=2056706586]
Medicines+ (Forked) [https://steamcommunity.com/sharedfiles/filedetails/?id=2558272601]
Mod Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=1507748539]
Dubs Bad Hygiene [https://steamcommunity.com/sharedfiles/filedetails/?id=836308268]
Multi-Bed Royalty Patch (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2441022091]
No One Left Behind [https://steamcommunity.com/sharedfiles/filedetails/?id=2401146569]
Out of Combat Move Speed Boost [https://steamcommunity.com/sharedfiles/filedetails/?id=2146654275]
Pick Up And Haul [https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058]
Outgoing Skipshield [https://steamcommunity.com/sharedfiles/filedetails/?id=2563147203]
P-Music [https://steamcommunity.com/sharedfiles/filedetails/?id=725130005]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
Polyamory Beds (Vanilla Edition) [https://steamcommunity.com/sharedfiles/filedetails/?id=2008138191]
[SYR] Universal Fermenter [https://steamcommunity.com/sharedfiles/filedetails/?id=2558008936]
VGP Vegetable Garden [https://steamcommunity.com/sharedfiles/filedetails/?id=2007061826]
VGP Garden Drinks UF [https://steamcommunity.com/sharedfiles/filedetails/?id=2167582651]
VGP Garden Fabrics [https://steamcommunity.com/sharedfiles/filedetails/?id=2007062162]
VGP Garden Gourmet [https://steamcommunity.com/sharedfiles/filedetails/?id=2007062982]
VGP Garden Medicine [https://steamcommunity.com/sharedfiles/filedetails/?id=2007063140]
VGP Three Sisters Plants [https://steamcommunity.com/sharedfiles/filedetails/?id=2007063848]
Realistic Human Sounds (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2013191418]
LED Lamps [https://steamcommunity.com/sharedfiles/filedetails/?id=842019577]
Rimsenal - Augmented Vanilla Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=849231601]
Rimsenal - Core [https://steamcommunity.com/sharedfiles/filedetails/?id=725947920]
Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
Rimsenal - Federation Faction Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=736172213]
Repairable Gear [https://steamcommunity.com/sharedfiles/filedetails/?id=2482478785]
Silver Coins [https://steamcommunity.com/sharedfiles/filedetails/?id=2483911712]
Egg Incubator [https://steamcommunity.com/sharedfiles/filedetails/?id=2505566813]
Tilled Soil [https://steamcommunity.com/sharedfiles/filedetails/?id=725747149]
Ultratech: Altered Carbon Remastered [https://steamcommunity.com/sharedfiles/filedetails/?id=2196278117]
Wall Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208]
[FSF] Better Ancient Complex Loot [https://steamcommunity.com/sharedfiles/filedetails/?id=2559244124]
[FSF] Meditation Freedom [https://steamcommunity.com/sharedfiles/filedetails/?id=2555422930]
[KV] RimFridge [https://steamcommunity.com/sharedfiles/filedetails/?id=1180721235]
[KV] Trading Spot [https://steamcommunity.com/sharedfiles/filedetails/?id=1180719658]
[Kit] Graze up [https://steamcommunity.com/sharedfiles/filedetails/?id=2302739121]
Hospitality [https://steamcommunity.com/sharedfiles/filedetails/?id=753498552]
RocketMan - Performance Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928]

**Description**
Hospitality guests spawn with correct ammunition for their guns, but with their inventory replaced by pemmicans, simple and fine meals, and packaged survival meals exclusively. 

**Expected behavior**
Hospitality guests should spawn with assortment of random items and silver. 

**To reproduce**
Run hospitality using the latest github version of hospitality. Spawn in guests with Do Incidents in dev mode. Check inventory of guests. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by skycrossercat** [comment]
Test with minimal mod list:
Harmony
Core
Hugslib
CE
Hospitality

and can confirm the problem still exist.

**Comment by LeriWeill** [comment]
This explains why a lot of time my guests didn't have any money to rent rooms. Makes sense!

**Comment by simplyWiri** [comment]
I believe this is due to a bug introduced on hospitalities end here:
https://github.com/OrionFive/Hospitality/pull/588

From CE's perspective, we are getting given pawns which have only food (and no other items), we only add items to the pawns inventory (weapon if they don't have one, ammo if they have a weapon without ammo, potentially a shield etc)

**Comment by simplyWiri** [comment]
Solved in an upstream push to Hospitality, if this issue persists when using the latest version of Hospitality from github, please re-open this issue. Ta
