### ISSUE TITLE
[Bug]: Psyfocus Bullet Shield doesn't stop projectiles

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#108]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.1 (Most recent update)
Combat Extended version: 2.1
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system:
Your mod list: Core, Royalty, Harmony, Combat Extended

**Description**
The psycast Bullet Shield does not stop projects from passing through it, friendly or hostile. Targets within and on the far side of the shield can be hit.

**Expected behavior**
Expected shield to stop bullets and fragmentation from passing through or into it.

**To reproduce**
Equip a colonist with the bullet shield psycast, have them create a bullet shield, then have another colonist or spawned hostile shoot at something inside/on the far side of the shield.

**Screenshots & log dumps**
No error associated with event.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by MadaraUchiha** [comment]
There's an upstream bug with Vanilla which causes EMP ammo (grenades in their case) to play the breaking animations but not actually break the shield.

I'll look into the other kinds of ammo for now, but will hold out on checking up how EMP ammo interacts with the shield until that bug is addressed.

See: https://ludeon.com/forums/index.php?topic=52322.0
