### ISSUE TITLE
[Bug]: CE disables UI 

### ISSUE THREAD

**Issue by hgAspirin9999** [CombatExtended-Continued/CombatExtended#11]
**Specifications**
Rimworld version: 1.1.2604
Combat Extended version: 1.1.2.0
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 7 (x32)
Mods: Harmony + Core + HugsLib + Combat Extended

**Description**
Starting/Loading a game with activated CE makes UI dissapear.

**Expected behavior**
UI should be painted, but it is not

**To reproduce**
Start a new game/Load an existing one

**Screenshots & log dumps**
![Rim](https://user-images.githubusercontent.com/27885343/79567726-63d06f00-80bd-11ea-8598-e056dc771884.png)
[Debug log.txt](https://github.com/CombatExtended-Continued/CombatExtended/files/4492781/Debug.log.txt)
[Repeating error in the debug window.txt](https://github.com/CombatExtended-Continued/CombatExtended/files/4492814/Repeating.error.in.the.debug.window.txt)

**Complete the following checklist**
I hereby verify that I have done the following:
[x] Confirmed that my game version and load order are correct.
[x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
[x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
[x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
> Windows 7 (x32) 
Combat Extended is not compatible with 32-bit systems, as I understand. Unfortunately, I'd say this is unlikely to change.

**Comment by onigamii** [comment]
Yep, this only happens on x32 systems.

**Comment by onigamii** [comment]
If nothing is to be discussed i'm clossing this issue.
