### ISSUE TITLE
[Feature Request] Debug fill ammo without manual pawn loading 

### ISSUE THREAD

**Issue by sealvessel** [CombatExtended-Continued/CombatExtended#1133]
**Specifications**
A debug option to instantly fill the turret with the selected ammo type. There is one in vanilla, but none with this mod. 

Rimworld version:
Combat Extended version: Current

**Expected behavior**
A red X button to fill the ammunition that is selected in the dropdown menu of the turret. For example, a mini turret can have hollow point or armor penetrating rounds. 

**Screenshots & log dumps**

**Comment by SamaelGray** [comment]
Implemented in https://github.com/CombatExtended-Continued/CombatExtended/pull/2084.
