### ISSUE TITLE
[Patch Request]: HALO: Rimworld Auxiliary Combat Armory

### ISSUE THREAD

**Issue by Ceephalon** [CombatExtended-Continued/CombatExtended#114]
**Mod name:** HALO: Rimworld Auxiliary Combat Armory

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=1961456342
**Description:**
Adds a few HALO themed weapons to the game
(used to have a CE patch? Mod page implies that "To my knowledge a patch is being provided by CE." Dont have the personal knowledge to comment more)
**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by N7Huntsman** [comment]
Already in progress. #29

**Comment by N7Huntsman** [comment]
Patch has been merged.
