### ISSUE TITLE
[Discussion]:Discussion on usefulness of a loadout composition feature before I implement it

### ISSUE THREAD

**Issue by nickweedon** [CombatExtended-Continued/CombatExtended#1147]
Before implementing a PR I wanted to discuss thoughts on the idea of having "composable loadouts".
The idea is simply that the loadout dialog would support an additional SourceSelection button called 'loadouts' which would list existing loadouts allowing the player to create loadouts that are composed of other loadouts.
Having briefly looked at the code the mechanics would likely be creating LoadoutSlot instances taking a LoadoutGenericDef where the lambda will essentially chain to the underlying loadout effectively creating something like a composition pattern.

Before I dive in i just wanted to see if anyone objects or finds this useful or if perhaps it has been discussed before and shot down already for some reason?

**Comment by N7Huntsman** [comment]
How would the usefulness of it compare to the current ability to save loadouts and create copies with one-click via the 'Copy Loadout' button?

**Comment by perkinslr** [comment]
Different goals.  Copy loadout lets you quickly set up loadouts initially.  Composable loadouts would serve a similar initial function, but later changes would be easier.  

So you could create a "basic loadout" which includes a meal, bandages, that sort of thing.  Then compose that basic loadout into your brawler loadout, your worker loadout, your soldier loadout, and so on (the soldier loadout, in turn, might get referenced by sniper, rifleman, et cetera).  Later, when you decide you want *everyone* to carry go-juice, you can add it to the "basic loadout", and it will automatically be included in all downstream loadouts.

Under the current system, you can make a "basic loadout", copy it for each subsequent loadout, copy the soldier loadout to the rifleman and sniper loadouts.  But when you want to add go-juice to each loadout, you must iterate the loadouts to add it.

**Comment by N7Huntsman** [comment]
Ah, I understand what you mean.

**Comment by nickweedon** [comment]
Thanks @perkinslr, I hadn't checked in in a couple of days so missed this activity but you summarized my thoughts perfectly.

**Comment by nickweedon** [comment]
OK, it seems I havn't received any comments stating this is a bad idea and it seems at least one other person can see some utility in this so i'll go ahead with getting started on a PR

**Comment by N7Huntsman** [comment]
Sorry for the belated response. But yeah, I can certainly see the utility of it to make loadouts a bit easier to manage.

**Comment by nickweedon** [comment]
Once my load/save change is merged I will get started on this change. I felt that having the load/save behavior implemented first made sense.

I have been pondering two different approaches to the composable loadout idea, namely:
- Option A: Allow an infinite level of composability.
- Option B: Restrict composability to a depth of two levels.

For example:

**Allowed for Option B**
   
        Light Soldier
        ├── Medicine Loadout
        └── Grenade Loadout
        
**Not allowed for Option B**
       
        Light Soldier
        ├── Accessory Loadout
        │   ├── Shield Loadout
        │   └── Belt Loadout
        ├── Medicine Loadout
        └── Grenade Loadout

Having thought about this I actually prefer "Option A" as while Option B may help reduce complexity for the player it also presents certain problems such as preventing the player from adding a loadout to his/her loadout when that loadout already refers to other loadouts (hence creating more than 2 levels). Enforcement of this rule might actually create more of a headache than it solves.

**Comment by nickweedon** [comment]
**Interoperability with load/save feature**

Saving and loading composite loadouts begs the obvious question _"What should happen to loadouts referenced in the saved/loaded loadout?"_

This comment proposes a solution to address this question.

**Background on load/save:**
The load/save feature is largely self explanatory however for the context of this discussion one caveat should be discussed which is the ability to save a loadout that has a different file name than the name of the loadout it contains. While the action of saving a loadout will pre-populate the save filename with the name of a loadout, the user is free to change this filename.
When loading a loadout and the loadout already exists, a new loadout name is automatically generated (consistent with how 'Copy Loadout...' works).

Changes to load/save screen:
- A new checkbox will be added to the load screen, to the effect of 'Replace existing loadout'. When checked, a loadout of the same name will be replaced with the loaded loadout, when not checked the existing behavior will be used and a unique name generated.
- A new checkbox will appear on the save screen which reads "Save composed loadouts" but only when saving a loadout that is composed of 1 or more other loadouts. This will be checked by default and when checked the save action will recursively save all composed loadouts.

**Saving**
Saving a loadout will be reasonably straightforward and will allow recursive saving of composed loadouts if the "Save composed loadouts" checkbox is enabled. For the case of saving the subordinate composed loadouts, the name of the file will be the name of the loadout. If the file exists it is overwritten, consistent with the existing save behavior.

**Loading**
In the situation of loading a composed loadout, there are 3 possible scenarios that can occur, namely:

- Scenario A - The loadout does not exist but there is a file name that matches the name of the loadout: In this case the loadout file with the matching name is automatically loaded, this occurs recursively.
- Scenario B - The loadout does not exist and there is no matching file: In this case a message is presented to the user stating that the composed loadout will not be loaded as it does not exist. The rest of the loadout will still be loaded.
- Scenario C - The loadout does exist: In this case, if the 'Replace existing loadout' checkbox is enabled then the loadout is loaded, replacing the loadout with the same name. If the 'Replace existing loadout' checkbox is disabled then the existing loadout is referred to.

**Comment by N7Huntsman** [comment]
As a summary of our brief chat in discord, a couple of items for consideration:
- Handling for conflicting instructions between parent/child loadouts.
- Concept of a visual "nested list" of loadouts to help users visualize loadout relationships.

**Comment by Anrock** [comment]
@nickweedon I'm kinda back to rimworld and I already want to have a "soldier" + "medic" loadout composition. Any progress with composable loadouts?

**Comment by nickweedon** [comment]
@Anrock Sorry about the super late response but i somehow missed this. I actually completed the change a while back on the ability to load/save a loadout but then i got stalled in conversations on the composable loadouts due to well intentioned discussion with people with similar and even better ideas, albiet more elaborate. I'm pretty busy with with my dev day job work right now but hopefully i can circle back in a few months and resurrect this idea (and possibly play rimworld again!) :)
