### ISSUE TITLE
Broken Blindfold

### ISSUE THREAD

**Issue by muggums** [CombatExtended-Continued/CombatExtended#1158]
![broken](https://user-images.githubusercontent.com/52576613/140591170-659bcd08-15c2-4c38-9df1-f2545c6151ee.png)
with combat extended
![mods](https://user-images.githubusercontent.com/52576613/140591173-1a654e6a-8421-48f4-aba5-0dd15cafbcde.png)
mod list that causes issue
![fixe](https://user-images.githubusercontent.com/52576613/140591178-de4f7687-d287-4ed5-8472-7dc92698591d.png)
without combat extended

**Comment by N7Huntsman** [comment]
The blindfold uses a special `<li>EyeCover</li>` layer from Ideology. Presumably, the issue is caused by CE rendering not handling that layer?

**Comment by sumghai** [comment]
I can confirm that this issue persists as of CE v1.3.4.5, and it is indeed related to the new `EyeCover` apparel layer.

This also affects a number of third-party mods that add spectacles, sunglasses and other eyewear.
