### ISSUE TITLE
[Bug]: Unknown Error

### ISSUE THREAD

**Issue by Nubasik** [CombatExtended-Continued/CombatExtended#1175]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: v.1.3.3179 rev360
Combat Extended version: 1.3.4.3
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Win 10 Pro
Your mod list:
Harmony
Core
Royalty
Ideology
HugsLib
Combat Extended

**Description**
Provide a concise description of the issue or concern. What happened?

**Expected behavior**
What did you expect to happen?

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
![2021-11-18_180611](https://user-images.githubusercontent.com/70583512/142443434-08bc8efe-d188-4326-a84d-6caf9872ee53.png)

Logs - https://gist.github.com/HugsLibRecordKeeper/1589dc15606649f66ff93c39d22a8f24
https://gist.github.com/HugsLibRecordKeeper/33e0944d91f23182452a45c820079b09
**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
You're using an uncompiled version because you downloaded it directly from the zip. You need a compiled version, which you can find on Steam, on the release page. If you're trying to run the latest dev, there's a download link pinned in issues, and if you're trying to run one of the PRs, you need to grab it from the latest bot comment with a download link.
