### ISSUE TITLE
[Patch Request]: Vanilla Factions Expanded - Mechanoids

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#1197]
**Mod name:** Vanilla Factions Expanded - Mechanoids

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2329011599

**Description:**
Updated on 12/10 added new mechs and weapons.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [ ] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by ItsSamGray** [comment]
Two new pieces of apparel/armor is added alongside other stuff as well, being Mechanite underarmor and pants.

**Comment by N7Huntsman** [comment]
Patch updated by #1207

**Comment by alreShan** [comment]
An un-patched turret: auto tesla turret.   Check the screenshots blow.

unpatched caliber
![#2024-3-17 VFE - Mechanoid  an unpatched caliber of a turret - lightning bolt](https://github.com/CombatExtended-Continued/CombatExtended/assets/104878767/558eae12-f5ed-4fca-b2b6-0a649076f52e)

no reaction to enemy
![#2024-3-17  VFE - Mechanoid   auto tesla turret no reaction to a enemy megaspider](https://github.com/CombatExtended-Continued/CombatExtended/assets/104878767/fd2039aa-d060-489c-b1e5-f8dfddef38db)
