### ISSUE TITLE
[Bug]: Suppression Missing Null Check

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#1223]
From bill doors on the discord:
```
my coder managed to find a bug when pawns becomes supressed and instakilled in the same time.
The pawn factor of the function GetCoverPositionFrom needs a pawn == null || pawn.Dead to prevent the Null Reference Exception error
otherwise the game will try to make a dead person seek cover
```

**Comment by perkinslr** [comment]
Supposedly, BillDoors' coder worked around this in their mod, and the code-path in general never gets called with a dead pawn on our side.  We could, in theory, make it more defensive, and the JIT would *probably* ellide the check, but I am disinclined to do so unless we get a feature request for mod compatibility.
