### ISSUE TITLE
[Bug]: Frag grenades kill people instantly with NaN damage

### ISSUE THREAD

**Issue by FORMless000** [CombatExtended-Continued/CombatExtended#1235]
Rimworld version: 1.3.3200
Combat Extended version: 1.3.4.4
Combat Extended source (Steam, GitHub, etc.): steam
Your operating system: Windows 10
Your mod list: Harmony, Core, CE

**Description**
Grenade frags deal NaN damage and instantly break the body part it hits. Mostly frags hit torso or head, resulting in an instakill.
No errors or warnings were thrown.

**Expected behavior**
No NaN damages.

**To reproduce**
Summon breachers and as their own grenade hit themselves, they might get instakilled.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by zozilin** [comment]
Possibly related to fractional damage? Not sure. Does not happen in 1.3.4.3 as confirmed by a user. 

By bill doors on discord:
> I guess it has something to do with the fragment's low penetration and pawn's low armor
> I'm observing pawns dying to a single small fragment with a NaN bruise
> I made a gun that fires small fragment and fired a Single shot
![image](https://user-images.githubusercontent.com/48126370/151852500-6bcf76de-6ff0-4b2b-b197-48064ec2b840.png)
