### ISSUE TITLE
[Bug]: Patch for Android Tiers TX expansion no longer works

### ISSUE THREAD

**Issue by FGRemastered** [CombatExtended-Continued/CombatExtended#1236]
**Specifications**

Rimworld version: 1.3.3200
Combat Extended version: 4.4-Hotfix
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win10x64
Your mod list: [Modlist.txt](https://github.com/CombatExtended-Continued/CombatExtended/files/7781371/CE.bugreport.txt)

**Description**
Androids from the TX expansion cannot:
- Select fire mode
- Select precision
- Aim for body parts

They're also missing:
- Smoke Sensitivity nullification (raceProperty)

It seems like the Patch got lost, as I couldn't find it anywhere in the mod files of either CE or AT TX.

**To reproduce**
Open the game with all required mods and libraries and equip a TX Android with a gun.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] ~~Disabled Combat Extended and attempted to reproduce the behaviour without success.~~

**Comment by FGRemastered** [comment]
Re-inserting the "Patches/Android Tiers++" folder solves this.

**Comment by N7Huntsman** [comment]
Yep, looks like the TX Series patches were incorrectly tucked in the Tiers++ folder and were assumed to be obsolete (since Tiers++ content was integrated). I'll be opening a PR to restore the patch--sorry about that.
