### ISSUE TITLE
[Bug]: Unable to trade at faction base.

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#124]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

~~Rimworld version:~~
~~Combat Extended version:~~
Combat Extended source (Steam, GitHub, etc.): Steam Workshop
~~Your operating system:~~
~~Your mod list:~~
**Unknown, as I'm copying this report from Steam workshop.**

**Description**
Combat Extended doesn't allow me to trade with factions
From Steam discussion: "So sometimes when I enter a faction base I can't trade with them. I click the trade button but nothing happens."

The discussion contains input from other users, and some speculation that it may be related to the factions selling minified turrets. So, potentially related to #123 .

**Expected behavior**
Expected to be able to trade with faction at their base.

**To reproduce**
From Steam discussion:
1. Send a caravan to a faction settlement that is not tribal to trade with. I used the civil outlander Union (the purple ones).
2. Trade or gift something.
3. Save.
4. Quit to main menu and reload the save.
5. Try to trade with the same settlement. It won’t work because of System.NullReferenceException:

**Screenshots & log dumps**
Steam discussion with details: https://steamcommunity.com/workshop/filedetails/discussion/1631756268/2265816381889030713/
Log: https://pastebin.com/MgwrLp4Z

**Complete the following checklist**
I hereby verify that I have done the following:
- [ ] Confirmed that my game version and load order are correct.
- [ ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by triocolore** [comment]
if you reading this 
https://steamcommunity.com/workshop/filedetails/discussion/1631756268/2265816381889030713/
 alexus finding minfied turret (any turret causing it), for example in my game "Exception while saving Turret_Flak258327: System.NullReferenceException: Object reference not set to an instance of an object" 
https://steamcommunity.com/workshop/filedetails/discussion/1631756268/2265816381889030713/
