### ISSUE TITLE
[Discussion]: Review of my new PR to add loadout load/save functionality.

### ISSUE THREAD

**Issue by nickweedon** [CombatExtended-Continued/CombatExtended#1245]
I normally like to create a discussion before writing code but in this case I have created the PR first.

The PR adds the ability to load and save loadouts as well as delete existing loadout files. Credit goes to the author of 
"[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings" (https://steamcommunity.com/sharedfiles/filedetails/?id=1180718516) for the load and save UI, although these classes have been modified and the load and save logic is completely new.

This is hopefully a good warmup to more more ambitious change i will make later to do with creating the idea of composable loadouts (https://github.com/CombatExtended-Continued/CombatExtended/issues/1147)

Let me know what you think, this will be very helpful for my own personal use but i think this simple change will be extremely useful to others also.

**Comment by nickweedon** [comment]
PR is: https://github.com/CombatExtended-Continued/CombatExtended/pull/1246

**Comment by nickweedon** [comment]
I forgot to mention that I still need to do the following (wanted to wait for a review of the change first):

- Add localization support for non-english languages for 2 strings I added (KV's load/save dialog uses existing localized strings already in the base game).
- Add logic to produce a warning when loading a loadout that refers to a missing ThingDef (e.g. the player has loaded a loadout into a game with different mods loaded). I figure the best thing to do here is to display a onscreen alert (Messages.Message) letting the player know that this loadout item will not be loaded because 'thing' is missing.

**Comment by N7Huntsman** [comment]
> The PR adds the ability to load and save loadouts as well as delete existing loadout files. Credit goes to the author of
"[KV] Save Storage, Outfit, Crafting, Drug, & Operation Settings" (https://steamcommunity.com/sharedfiles/filedetails/?id=1180718516) for the load and save UI, although these classes have been modified and the load and save logic is completely new.

Before it's merged, it may be prudent to secure the author's permission to use the UI, or else re-do it if they decline.

**Comment by nickweedon** [comment]
Totally agree, i actually reached out to the author tommorrow and he told me it is fine to use. Turns out that this code is actually from the Vanilla Rimworld. You can see the conversation here: https://steamcommunity.com/id/kiame
