### ISSUE TITLE
[Discussion]: Psycast Range

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#125]
Currently, Combat Extended does not change the ranges of the Psycasts added by the Royalty DLC. Since this generally leaves them with a much shorter range than most weapons, their effectiveness is limited.

It would likely be appropriate to scale the range of these Psycasts upward.

**Comment by Tostov** [comment]
I can agree with this, though I think while the targeting range should generally be increased, the effect range should not. This might result in semi-inconsistencies; for example, in the current state/vanilla, skip functionally has the same cast range as the range it can move the pawn, whereas after this change it would counceptually only be able to transport the pawn a shorter distance than the targeting range; but would probably be the best option, as skip, for example, is already a very strong tool with the current degree of mobility it allows.
