### ISSUE TITLE
[Bug]: Automatic aiming at android from Android Tiers fires "blanks" and uses all ammo

### ISSUE THREAD

**Issue by naanselmo** [CombatExtended-Continued/CombatExtended#1253]
**Specifications**
Rimworld version: 1.3.3200 (latest)
Combat Extended version: 1.3.4.4 (latest)
Combat Extended source (Steam, GitHub, etc.): Steam, and then GitHub development, to confirm it wasn't fixed
Your operating system: Windows 10
Your mod list (this is the one I used when reproducing):
- Harmony
- Core
- Ideology
- HugsLib
- Mod Manager
- Combat Extended
- Humanoid Alien Races
- Android tiers
- Enable Oversized Weapons

**Description**
When aiming at a pawn from Android Tiers that is humanlike and using automatic aiming, all shots will be fired in quick succession as "blanks" and all ammo is immediately used, starting to reload again. By blanks I mean that no shots will actually be fired but ammo will be used, and the pawn will even say lines that they'd say when firing from mods that create those interactions.

This happens due to this line, I believe, as Androids do not have Torsos but instead have a MechanicalThorax

https://github.com/CombatExtended-Continued/CombatExtended/blob/70ab571ab768398256d88b522e8719906637c817/Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs#L407

I believe the only thing that needs to be done is "convert" MechanicalThorax into a Torso for CE purposes at least when it comes to choosing what to shoot at, but I have no idea how that'd be done, never made a patch for CE!

**Expected behavior**
That only one bullet would be fired, and that it would actually be fired.

**To reproduce**
I created a new game with the above mods (could probably remove Mod Manager I guess, but it made it easier, and I forgot to disable Ideology so I left it in mod list above just in case). Trained colonist to max shooting skill. Spawned a bolt action rifle and .303 FMJ ammo. Spawned an hostile T1 android.

Shooting with automatic will perform the bug, and use all ammo and begin reloading. Aiming at torso works fine, as well as legs and head.

Thinking it might've been due to no patch mentioning T1 (only T4) for Android Tiers, I tried a T4 android, but exactly the same issue occurs.

**Screenshots & log dumps**
Pasting only the relevant portion of the logs that points to that function and an improper "First" on an empty list:

```
System.InvalidOperationException: Sequence contains no elements
  at System.Linq.Enumerable.First[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x00010] in <351e49e2a5bf4fd6beabb458ce2255f3>:0 
  at CombatExtended.Verb_LaunchProjectileCE.ShiftTarget (CombatExtended.ShiftVecReport report, System.Boolean calculateMechanicalOnly, System.Boolean isInstant) [0x0047b] in <2d8069341dcb4e5dae350fa7e8ad7808>:0 
  at CombatExtended.Verb_LaunchProjectileCE.TryCastShot () [0x00111] in <2d8069341dcb4e5dae350fa7e8ad7808>:0 
  at CombatExtended.Verb_ShootCE.TryCastShot () [0x00035] in <2d8069341dcb4e5dae350fa7e8ad7808>:0 
```

It continues, but the rest is in my opinion irrelevant (it's game ticks).

Logs were collected when running with more mods, but I used only the mods described above when reproducing the bug (but didn't get logs).

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Davidtank70** [comment]
I'm having this same issue.

**Comment by zixq** [comment]
Also having this problem, whenever a pawn with automatic targeting tries to fire at an android the game slows down massively and spams errors. I've found this to especially be a problem with mechanoids, which seem to always have automatic targeted aiming resulting in centipedes and lancers firing nonexistent bullets and consuming ammo while slowing the game down and being effectively neutralized. 
Also, unrelated to this specific issue, I can't seem to switch the targeted area for my android colonists, the targeted area button does not show up
