### ISSUE TITLE
[Patch Request]: Combat Enthusiast's Collection

### ISSUE THREAD

**Issue by NetImmerse** [CombatExtended-Continued/CombatExtended#132]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**

**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**

**Mod name: Combat Enthusiast's Collection**

**Link to mod download (preferably Steam workshop or Github): https://steamcommunity.com/sharedfiles/filedetails/?id=1862509294**

**Description: adds a couple of vanilla-friendly designed weapons**
**Before 1.1 this mod had an embedded CE 1.5 and 1.6 patch but after 1.1 mod author has no plans on updating CE patches**

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Andromeda-K22** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2131889888

Patch exists here - contact author for integration.

**Comment by N7Huntsman** [comment]
Completed. #168
