### ISSUE TITLE
[Discussion]: Partial Armor Implementation

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#1343]
Here's my general scheme for implementing partial armor, based upon a few very rough classifications of armor. Bear in mind, this mostly just applies to power armor and heavy, industrial ballistic armor (like some of those found in the EFT and RH2 mods). 

_If_ the listed body part is covered by the armor, they're adjusted along these guidelines--and these are only rough guidelines. If a body part isn't mentioned, it's not specifically changed. 

**Super Heavy:** (e.g Cataphract)
- Torso: 100%
- Legs: 100%
- Arms: 100%
- Hands: 80%

**Heavy:** (e.g Power Armor)
- Torso: 100%
- Neck: 80%
- Legs: 100%
- Arms: 90%
- Hands: 70%

**Medium:**  (e.g Recon Armor)
- Torso: 100%
- Neck: 60%
- Legs: 90%
- Arms: 80%
- Hands: 60%

**Industrial Ballistic Vests/Flak Jacket:**
- Neck: 60%
- Shoulders: 60%
(These are basically areas where the armor doesn't have a plate (or only has a thinner one than the main front and back plates).

Handled by #1404.

**Comment by ItsSamGray** [comment]
As copied from our discussion on discord, let's remember that AI pawns can autotarget if skilled enough and if we nerf the hand and arm protection on some PA variants too hard, there will be arms and hands flying off all the time.

Cataphract is ok imo, for heavy we can set arms to 90% and hands to 70% and set medium (recon) to 90% legs, 80% arms and 60% hands

**Comment by N7Huntsman** [comment]
> Heavy we can set arms to 90% and hands to 70% and set Medium to 90% legs, 80% arms and 60% hands
Alright, sure.

**Comment by ItsSamGray** [comment]
Implemented.
