### ISSUE TITLE
[Bug]: NullReferenceException when hovering over armour values of apparel viewed from research screen

### ISSUE THREAD

**Issue by hamisht99** [CombatExtended-Continued/CombatExtended#1388]
**Complete the template below. Reports that do not follow the template will be deleted.**

**Specifications**

Rimworld version: 1.3.3200
Combat Extended version: 
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win 10
<details>
<summary>Your mod list: </summary>

  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Royalty
  - Ludeon.RimWorld.Ideology
  - UnlimitedHugs.HugsLib
  - erdelf.HumanoidAlienRaces
  - OskarPotocki.VanillaFactionsExpanded.Core
  - OskarPotocki.VFE.Mechanoid
  - vanillaexpanded.achievements
  - OskarPotocki.VanillaFactionsExpanded.MedievalModule
  - sarg.alphaanimals
  - CarnySenpai.EnableOversizedWeapons
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEMedical
  - VanillaExpanded.VFESecurity
  - VanillaExpanded.VFESpacer
  - VanillaExpanded.VFEFarming
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VCookE
  - VanillaExpanded.VPlantsE
  - VanillaExpanded.VFEPower
  - OskarPotocki.VFE.Vikings
  - OskarPotocki.VFE.Insectoid
  - OskarPotocki.VanillaFactionsExpanded.SettlersModule
  - FS.ReviaRace
  - AludisNHG.Archotechrace
  - VanillaExpanded.VEE
  - VanillaExpanded.VBrewE
  - VanillaExpanded.VBrewECandT
  - OskarPotocki.VanillaExpanded.IdeologyPatches
  - OskarPotocki.VanillaExpanded.RoyaltyPatches
  - AludisNHG.Archotechfaction
  - Dubwise.Rimatomics
  - Dubwise.Rimefeller
  - FrozenSnowFox.AdvancedBionicsExpansion
  - CETeam.CombatExtended
  - Ham.ReviaBuff
  - CETeam.CombatExtendedMelee
  - Atlas.AndroidTiers
  - void.charactereditor
  - FrozenSnowFox.MoreQuests
  - FrozenSnowFox.ImprovedVanometricPowerCells
  - Ducks.InsaneSkills
  - Dubwise.DubsPerformanceAnalyzer
  - rimfridge.kv.rw
  - Dubwise.DubsMintMenus
  - Dubwise.DubsBadHygiene
  - AludisNHG.ArchotechCE
  - tammybee.whereismyweapon
  - Orion.Hospitality
  - FrozenSnowFox.ComplexJobs
  - trinity.RuntimeGCupdated
  - Ham.CustomFix
 

*(Ham mods are mine.  ReviaBuff does what it says on the tin and patches revian weapons to make them slightly stronger, CustomFix contains a single def for fixing psychic sensitivity when using eltex gear due to a bug in android tiers.)*

</details>

**Description**

Viewing info of an item from the research screen or relevant crafting bench and hovering the mouse over any of the "armor" sections will throw a null reference exception.  This applies to every item I tried, both modded and vanilla.  The text that would normally appear on the right side of the info box isn't present (I'm guessing due to the error).  Given that the tooltip still appears if I disable auto-open on the debug log, I'm guessing the issue is related to the actual numbers/calculation shown at the bottom on the right.

**Expected behavior**

No errors to be thrown, and the text on the right side of the screen to be shown.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

Click "Flak armor" on the research screen.  Click one of the armour items that should be shown on the left.  Hover the mouse over one of the CE armour values.  The text area on the right will not be filled, and if enabled, the debug log should appear with the exception.

**Screenshots & log dumps**

<details>
<summary>In game debug log</summary>  

```
Exception filling window for Verse.Dialog_InfoCard: System.NullReferenceException: Object reference not set to an instance of an object
  at CombatExtended.StatWorker_ArmorPartial.GetExplanationFinalizePart (RimWorld.StatRequest req, Verse.ToStringNumberSense numberSense, System.Single finalVal) [0x0001a] in <aaf910de4ee048aa8f557e0306cdc9d6>:0 
  at RimWorld.StatWorker.GetExplanationFull (RimWorld.StatRequest req, Verse.ToStringNumberSense numberSense, System.Single value) [0x00057] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at RimWorld.StatDrawEntry.GetExplanationText (RimWorld.StatRequest optionalReq) [0x00040] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at RimWorld.StatsReportUtility.DrawStatsWorker (UnityEngine.Rect rect, Verse.Thing optionalThing, RimWorld.Planet.WorldObject optionalWorldObject) [0x002a4] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at RimWorld.StatsReportUtility.DrawStatsReport (UnityEngine.Rect rect, Verse.Def def, Verse.ThingDef stuff) [0x00076] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at (wrapper dynamic-method) Verse.Dialog_InfoCard.Verse.Dialog_InfoCard.FillCard_Patch1(Verse.Dialog_InfoCard,UnityEngine.Rect)
  at Verse.Dialog_InfoCard.DoWindowContents (UnityEngine.Rect inRect) [0x00288] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
  at Verse.Window.InnerWindowOnGUI (System.Int32 x) [0x001ce] in <cdbd0ed5089a418da09b9a259f9dbd8f>:0 
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.Window:InnerWindowOnGUI (int)
UnityEngine.GUI:CallWindowDelegate (UnityEngine.GUI/WindowFunction,int,int,UnityEngine.GUISkin,int,single,single,UnityEngine.GUIStyle)
```

</details>

[In game debug log pastebin](https://pastebin.com/i66CPZfT)

**Complete the following checklist**
I hereby verify that I have done the following:
- [✅] Confirmed that my game version and load order are correct.
- [✅] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [✅] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [✅] Disabled Combat Extended and attempted to reproduce the behaviour without success.

**Comment by ItsSamGray** [comment]
This issue is already fixed in the latest github dev version
