### ISSUE TITLE
[Bug]: Patch operation For Vanilla Factions Expanded - Mechanoids failed

### ISSUE THREAD

**Issue by Eric-szh** [CombatExtended-Continued/CombatExtended#1409]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.3.3287
Combat Extended version: 1.3.4.5
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows
Your mod list:
Harmony
Core
Royalty
Ideology
Vanilla Expanded Framework
Vanilla Factions Expanded - Mechanoids
Combat Extended

**Description**
Provide a concise description of the issue or concern. What happened?
I try to run a game with those two mods, and it seems that CE has not patched successfully on VFE - Mechanoids. On the console, it shows that the patch is not successful. In-game when I try to examine a weapon from VFE - Mechanoids. It is not properly patched and resulted in no melee damage stats. 

**Expected behavior**
What did you expect to happen?
CE has successfully patched VFE - Mechanoids. No error should be found on the console and the weapons from VFE - Mechanoids should have patched stats.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Launches a game with the above modlist.
First, you will see errors in the console (included below)
Start a game.
Enter God mode.
In debug menu- spawn weapon - VFE_Gun_RaiderMechanoidGun
Place the gun on the ground
Examine the weapon using i 
And the weapon stats are unpatched.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
![image](https://user-images.githubusercontent.com/32203266/156948390-1b7fd645-1c0f-4455-b445-74d874ee63ea.png)
Error on starting: https://pastebin.com/A5b4Kq1m
Error on examining: https://pastebin.com/bXstUvZN

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches. (I redownloaded all mods in the modlists above again)
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x]  Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by ItsSamGray** [comment]
This issue is fixed in the latest dev build of CE, try getting the latest dev build from the github link and do a fresh install of CE from the downloaded file.
