### ISSUE TITLE
[Bug]: VFE - Mechanoids patch bug

### ISSUE THREAD

**Issue by kydsh** [CombatExtended-Continued/CombatExtended#1428]
Rimworld version:
Combat Extended version: 4.5-Hotfix
Combat Extended source: Steam
Your operating system:Win 10
Your mod list: Harmony, Ideology, Royalty, Vanilla Framework Expanded, Alpha Animals, Vanilla Factions Expanded - Mechanoids, Combat Extended.

**Description**
when I try to launch the rimworld with VFE-Mechanoids and without Alpha animals an patch error appears, when running both mods there are no problems

**Expected behavior**
Patch work without alpha animals

**To reproduce**
Launch VFE Mechs mod without alpha animals

**Screenshots & log dumps**
[log.txt](https://github.com/CombatExtended-Continued/CombatExtended/files/8309189/log.txt)
https://pastebin.com/A6DPMj1e

**Comment by ItsSamGray** [comment]
This issue is fixed on the latest de build snapshot of CE
