### ISSUE TITLE
[Bug]: Issues with dev mode

### ISSUE THREAD

**Issue by zozilin** [CombatExtended-Continued/CombatExtended#1436]
**Specifications**
Rimworld version: latest, all DLCs
Combat Extended version: latest dev build or any build after Multiplayer merge #1380 
Your operating system: Win10
Hugslog: https://gist.github.com/5c83b843c2bed9a52d25573f85172baf 
Modlist: any minimal modlist, CE, Harmony, DLCs or not

**Description**
Throws a "Could not instantiate a GameComponent of type CombatExtended.CE_DebugTooltipHelper:" error on a new colony
Can't open debug actions or debug logging menus, those throw errors mentioning Multiplayer API (see log)

**To reproduce**
1. Download a snapshot from https://combatextended.lp-programming.com/CombatExtended-latest.zip
2. Start a colony
3. Click on debug actions menu and on debug logging menu

Edit: Adding Vanilla Expanded Framework fixes the issue, somehow.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by ItsSamGray** [comment]
Playing with the latest dev build of CE in a Ce only modlist and no problems

**Comment by zozilin** [comment]
Yeah, no errors now, redownloaded the snapshot today and checked again. I probably downloaded the snapshot at an unfortunate time

**Comment by zozilin** [comment]
Actually, no. It's still happening.

**Comment by zozilin** [comment]
> Sokyran
Looks like the issue is the reference to Multiplayer API... Or well, possibly due to (at least I assume so) CombatExtended.CE_DebugTooltipHelper checking/loading all types.
Possible solution would be to replace the API calls with just reflection, as it's (as far as I recall) only used when loading

---

Is this really just me? I've tried everything, removed all mods besides harmony, still happens with dev build. It's definitely connected to #1380 as any builds before this merge work fine for me.

**Comment by zozilin** [comment]
> Playing with the latest dev build of CE in a CE only modlist and no problems

Are you sure you can use debug options? I know that at least one other person has this issue when downloading the latest snapshot. Do you also download from there or do you compile? And does it make a difference?

**Comment by ItsSamGray** [comment]
Confirmed related to the multiplayer compatibility API

**Comment by ItsSamGray** [comment]
Fixed in 4.6
