### ISSUE TITLE
[Bug]: Rimthreaded Combat Extended Pawns Don't Drop Ammo

### ISSUE THREAD

**Issue by Whyareuhere** [CombatExtended-Continued/CombatExtended#1458]
Rimworld version: 1.3.3311
Combat Extended version: Latest on Steam (Feb. 20)
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list: 
- Harmony
- Visual Exception
- Core
- Royalty
- Ideology
- SRTS Expanded (CE Fork)
- Hugslib
- Humanoid Alien Races
- Vanilla Expanded Framework
- Combat Extended
- RimThreaded

**Description**
An error results in the ammo injector system when loading in citing multiple definitions for ammo, despite other mods being compatible with Combat Extended. Whenever a pawn is downed (exception being colony pawns) ammo does not drop. When they spawn there is an error for "RandomElementByWeight with totalWeight=0 - use TryRandomElementByWeight.", which I suspect is for the ammo weight. Thus, when ammo is dropped the weight is read as a null, deleting them before it seems to be dropped by the pawn. This does NOT happen for colony pawns.

**Expected behavior**
Ammo should drop on the ground.

**To reproduce**
Load mod list above, spawn enemy pawn. Down them either via dev mode or other modes

**Screenshots & log dumps**
RandomElementByWeight with totalWeight=0 - use TryRandomElementByWeight.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct. (yes)
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches. (yes)
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended. (yes)
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success. (unable, this is an issue with Combat Extended ammo system)

**Comment by perkinslr** [comment]
> * [ ]  Confirmed I am not running any mods with known incompatibilities with Combat Extended. (yes)
> *

Um, `(no)`...  RimThreaded is a fundamentally broken mod that goes along merrily hiding its own errors.  We don't go out of our way to sabotage it, but we also won't break our own code to support it (nor waste much effort trying to find ways to support it that *don't* break our code).  If you post your *whole* hugs lib log, I can take a peek, but odds are good the answer will be "don't use rimthreaded".

**Comment by Whyareuhere** [comment]
Ah I see! My bad, I thought I put the output log in the bug report, here you go:

https://gist.github.com/HugsLibRecordKeeper/7427047012036ffc90b53d5ca324919c

I will ask the devs of Rimthreaded about what's going on

**Comment by perkinslr** [comment]
You got a log to go with the minimal mod list you put above?  The log you linked has 227 mods active.  

That aside, the error you mention looks like it happens on game startup, and is probably because it's trying to pick a random item from a list (by weight) while the list is empty.  This is a classic rimthreaded problem.  The solution is to add sufficient locks (on the rimthreaded side) to ensure the list is populated before an item is pulled from it.  The auto-suggested solution (TryRandomElementByWeight) would only hide the problem (probably resulting in a NPE on a later line of code).  

Verify you can create the issue with just the mods you listed above, get all the way into a game, snag a copy of the log, down a pawn, and snag another copy of the log.  *Maybe* something will show up there.  Oh, and check if the non-downed pawn has their ammo in inventory before getting downed.

**Comment by Whyareuhere** [comment]
Ok I just tried again and somehow this bug has disappeared, even with the modlist used above. Seems to be an issue with another mod I am running so I ask for someone to close this

**Comment by Whyareuhere** [comment]
Update: Rimfeller is somehow producing this error with Combat Extended and Rimthreaded, just to let you know

**Comment by Batur123** [comment]
> Update: Rimfeller is somehow producing this error with Combat Extended and Rimthreaded, just to let you know

Rimthreaded is also broken with Save our Ship 2. Game instantly crashes if you try to go info ship battle or move your ship.

**Comment by pO0P3R125** [comment]
> > Update: Rimfeller is somehow producing this error with Combat Extended and Rimthreaded, just to let you know
> 
> Rimthreaded is also broken with Save our Ship 2. Game instantly crashes if you try to go into ship battle or move your ship.

actually no, you need to increase the waiting time to 30 seconds (30000 miliseconds) in the mod options, this is not default as is too much time for most configs, that happens only with the biggest ships in save our ship 2, I welcome you to Rimthreaded discord and github for any further help or explanantion as active development has started again

**Comment by pO0P3R125** [comment]
> > * [ ]   Confirmed I am not running any mods with known incompatibilities with Combat Extended. (yes)
> 
> Um, `(no)`... RimThreaded is a fundamentally broken mod that goes along merrily hiding its own errors. We don't go out of our way to sabotage it, but we also won't break our own code to support it (nor waste much effort trying to find ways to support it that _don't_ break our code). If you post your _whole_ hugs lib log, I can take a peek, but odds are good the answer will be "don't use rimthreaded".

we don't hide our own errors in game and is not fundametally broken, I have played colonies on years without too much issue and gigantic modlists and being an actual tester in their server, we would like to have the incompatible mark from Combat extended remove, we don't mind getting reports redirected to our discord or github and fixing the errors that come up from our part, we are open to collaborate with anyone
