### ISSUE TITLE
Path Request:  Star Wars Races

### ISSUE THREAD

**Issue by KazTheMercenary** [CombatExtended-Continued/CombatExtended#1470]
Hey guys,
It looks like these 4 races comes with a default 2mm RHA and 2 MPa 'apparel armor' that isn't actually tied to apparel.  That little Ewok fought like a goddamn rabid raccoon, and I finally just had to shoot him as my knives/machetes weren't doing anything to the fuzzy little psycho.

.... patch maybe?  ^_^  Only requesting because of the time taken to untangle what was going on (assuming I had screwed up, which I had by not checking compatibility)

**Comment by ItsSamGray** [comment]
Try the latest dev build, the autopatcher got updated and will fix the armor issue.
The proper patch might come at a later date.

**Comment by KazTheMercenary** [comment]
So, it definitely auto-patched.  It's definitely BETTER.  It's definitely still happening.

But it's .13 RHA and 1 MPa, which is considerably more reasonable

That's after downloading the 'snapshot' dev build a few minutes ago, and replacing the Workshop version with it.
