### ISSUE TITLE
[Discussion]: Weapon switch gizmo

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#1475]
Given the popularity of Simple Sidearms and Pocket Sand mods and the situation with carried guns and grenades in CE which without said mods, requires the player to open the inventory tab of each pawn to switch weapons, we should probably start implementing a easy to use gizmo that enables weapon switching for the QoL's sake and a proper in-house solution to the issues instead of relying on third-party mods that can cause foreseen/unforeseen issues.

This gizmo could also contain grenades as a valid option to enable the player to throw grenades without having to switch items around in a micro managementy way.
It might not be a bad idea to introduce a small execution time for stowing the current weapon is use and grabbing another one from inventory for realism's sake and preventing the potential ways of abusing the system.

**Comment by albertbokor** [comment]
yepp, a "single grenade throw" functionality would be extremely useful

**Comment by N7Huntsman** [comment]
Haven't seen any movement on these matters, so closing this issue for the moment for housekeeping.
