### ISSUE TITLE
[Discussion]: Reloading on the move

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#1482]
Since reloading guns takes a fair amount of seconds in the scale of RW time and pawns move quite fast and always are running relative to how fast pawns can shoot and reload, it might be a good idea to implement a system with a togglable gizmo attached that enables reloading guns while moving.

This option definitely would result in a movement speed penalty (50% for example) when a pawn reloads a gun while moving and maybe a reload speed penalty as well to balance things out. This should help guns like shotguns and ones with fast rate of fire that deplete their magazines quite fast and require constant reloading.

This functionality could be tied to a weapon tag so that only certain weapons are allowed to be reloaded on the move.

**Comment by HarkonG** [comment]
Great idea, I'm all for it!

**Comment by Caulaflower** [comment]
probably doable but might be wonky. That said I will look into it once I finish dealing with the mechanoids PR

**Comment by Safairette** [comment]
Maybe, but I'd avoid making it a new gizmo. There's enough of them as is. A mod setting would fit it better imo and would also reduce the possible complaints of extra micromanagement

**Comment by ItsSamGray** [comment]
> Maybe, but I'd avoid making it a new gizmo. There's enough of them as is. A mod setting would fit it better imo and would also reduce the possible complaints of extra micromanagement

The gizmo is a necessity because the usage of the system should be togglable in-game and mid combat, you might want to reload on the move in certain situations and not reload in other situations because of the associated movement speed penalties with reloading on the move.

**Comment by perkinslr** [comment]
Could probably mitigate the extra clutter by piggybacking on the general `reload` gizmo.  Not sure if it should be part of the right-click menu or a sub-button on it.

**Comment by sumghai** [comment]
> Could probably mitigate the extra clutter by piggybacking on the general `reload` gizmo. Not sure if it should be part of the right-click menu or a sub-button on it.

If screen real estate is at a premium, one could render a standing/running man icon in the top right corner of the existing reload gizmo, and make it toggleable via a right-click context menu.

**Comment by ItsSamGray** [comment]
> > Could probably mitigate the extra clutter by piggybacking on the general `reload` gizmo. Not sure if it should be part of the right-click menu or a sub-button on it.
> 
> If screen real estate is at a premium, one could render a standing/running man icon in the top right corner of the existing reload gizmo, and make it toggleable via a right-click context menu.

yea those could work quite neatly

**Comment by Breadbox2k19** [comment]
Not every weapon should be allowed to reload on the move.

**Comment by N7Huntsman** [comment]
Haven't seen any movement on these matters, so closing this issue for the moment for housekeeping.
