### ISSUE TITLE
[Bug]: VWE Lasers Warming-up Mechanics Not Working in CE

### ISSUE THREAD

**Issue by Tesseract22** [CombatExtended-Continued/CombatExtended#1487]
Rimworld version: 1.3.3326
Combat Extended version: 1.3.4.5
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10

When CE is loaded, the laser guns in VWE Laser doesn't warm up. But it does when CE is not loaded

The laser gun should shoot faster and faster if the warm-up mechanics is functioning.

I hereby verify that I have done the following:

Confirmed that my game version and load order are correct.
Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
Confirmed I am not running any mods with known incompatibilities with Combat Extended.
Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by perkinslr** [comment]
Just for clarification: The time between shots with VFE Lasers decreases the longer they are shooting?  At the same target?  Does it fall off slowly?  Or snap back to default when you interrupt shooting?  Is it all VFE Lasers?

**Comment by N7Huntsman** [comment]
This is a fundamental difference in the functionality of VWE's Lasers versus those of Combat Extended. CE's laser function and are balanced differently, and it's unlikely we'll add this feature to our lasers.
