### ISSUE TITLE
[Discussion]: Suppression options in settings

### ISSUE THREAD

**Issue by FatalError42O** [CombatExtended-Continued/CombatExtended#1502]
I love combat extended, and the weapons and options it brings to the game- but... I find it really hard to enjoy because of one mechanic, that (as you may have guessed) being suppression.

I find it really frustrating to play with, pawns will actively jump into danger because of suppression even when they are already safe from enemy fire, I've had pawns jump over sandbags into the enemy field of fire because of suppression and get themselves killed. And when they aren't jumping into bullets, they're laying down doing nothing or clustering up near other people so they're even more likely to be shot. All of this because a few unskilled raiders with RPKs. 

I just find the suppression system broken frustrating and generally awful to play with- it feels like every raid is more a battle of trying to get my own pawns to do what I need and to not self-destruct. 

I appreciate people who like the suppression system, or take advantage of it- however, it's just not for me, and I've seen quite a few other people complain about it. 

What I'm really just wondering- is why there's no settings to limit (like a multiplier slider) or outright disable the suppression system? I hate it, and it's slowly driving me away from this mod(/insane), and I just want to turn it off. What are the chances that something like this would be added?

**Comment by FatalError42O** [comment]
here we can see a pawn "running for cover" also known as: running towards the enemy like a dumbass.
![image](https://user-images.githubusercontent.com/58855799/164360073-25b313ab-d214-4f22-9791-a0f7a467502d.png)
if THIS isn't reason enough to fix suppression, or add settings to disable it THEN WHAT IS

**Comment by FatalError42O** [comment]
I know nobody is responding to this, but I'd like to note, most of the time when they "run for cover" they're not denying orders to try to get to safety, they are actively endangering themselves all of the time, I've had pawns turn back halfway through a door after I ordered them into a room to safety to get to cover that's in the middle of a room with enemies.... they will literally _turn and charge the enemy instead of retreating because they're scared of how many bullets are flying_ I just can't find any situations where these mechanics seem reasonable- they always endanger themselves because of suppression, and go closer to the enemy! it's so frustrating losing a colonist because of this garbage mechanic!

**Comment by perkinslr** [comment]
It's been a known issue for a fairly long time.  It's also a bloody hard problem to solve (patches welcome).  Unfortunately, if you just disable the suppression system, you'll find your pawns die to snipers far more readily, you do want them to duck and cover at least some of the time.

There have been attempts to make the cover seeking smarter, or otherwise fix it right, but the performance impact is rather steep.  In the mean time, the Combat Extended Fixes (CEFixes) mod on steam disables the run for cover job.  They'll still cower in place (and sometimes still time that badly such that they get semi-stunlocked), but they won't actively run toward the enemy against orders with it.

**Comment by FatalError42O** [comment]
Yeah, alright- I'll use that mod. It's not like the stun locking is an issue, that's to be expected, and I'd hide in cover if there were stupid amounts of bullets flying over my head too- it's just the insane jumping into danger so frequently that bothers the shit out of me

**Comment by SamaelGray** [comment]
The system is overhauled to be more reliable.
