### ISSUE TITLE
[Discussion]: How to translate tips?

### ISSUE THREAD

**Issue by RogeVenham** [CombatExtended-Continued/CombatExtended#1517]
How to translate tips? Other language.

CombatExtended/blob/Development/Defs/Misc/TipSetDefs/Tips.xml

**Note: These are to be used for discussions related to Combat Extended, primarily by team members and other contributors. Not for feedback, requests, etc. Off-topic chatter will be deleted.**

**Comment by ItsSamGray** [comment]
Related to https://github.com/CombatExtended-Continued/CombatExtended/pull/1521
