### ISSUE TITLE
[Discussion]: VFE - Security; Artillery

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#152]
The Artillery from VFE - Security has proven to be problematic while trying to patch the mod. There are two primary culprits:
## 2. The way Combat Extended handles spawning shells for sieges.

Here, the issues and possible solutions can be discussed.

**Comment by N7Huntsman** [comment]
Regarding **#2.**:

```
        public static bool IsShell(ThingDef def)
        {
            var ammo = ThingDefOf.Turret_Mortar.building.turretGunDef.GetCompProperties<CompProperties_AmmoUser>();
            return ammo?.ammoSet.ammoTypes.Any(l => l.ammo == def) ?? false;
        }

        public static bool IsAmmoSystemActive(AmmoDef def)
        {
            if (Controller.settings.EnableAmmoSystem) return true;
            return (def != null && def.isMortarAmmo);
        }

        public static bool IsAmmoSystemActive(AmmoSetDef ammoSet)
        {
            if (Controller.settings.EnableAmmoSystem) return true;
            return (ammoSet != null && ammoSet.isMortarAmmoSet);
        }
```

**Comment by N7Huntsman** [comment]
Notably, for #2. changing the ammoSet from the 155mm shells to the 81mm shells fixes the issue.

**Comment by onigamii** [comment]
This is one thing that i'd like to get to work properly. In my [VFE-S repo](https://github.com/onigamii/VanillaFurnitureExpanded-SecurityCE) everything is up to date, except the shields and the artillery that somehow i can't get it to work like a mortar again, but it works (like the flak).

**Comment by N7Huntsman** [comment]
2. Has been fixed with a workaround wherein the raiders use a different version of the artillery (locked behind a research option that's been intentionally tucked away) that load the 81mm (vanilla) mortar shells, but fire a 155mm projectile. It's not an elegant solution, but it's functional. It also has the building level requirement dropped to 5, instead of 6, as this was causing issues with the raiders sometimes not building it.

**Comment by N7Huntsman** [comment]
#2 Consolidated into #513
