### ISSUE TITLE
[Discussion]: Implement a similar drug like Go-juice for tribals

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#1526]
In order to make Tribals stand a chance mid to late-game, it might be a good idea to implement a drug called "Psycho" made from concentrated extracts of psycoid leaves to mimic the effects of Yayo and Go-juice for movement speed, consciousness and suppressibility bonuses.

The drug colud be highly addictive (maybe near 50% addiction chance without tolerance build-up) and great side-effects like how major food poisoning effects are, a short high timer and a hard crash after the effects wear off so it's only effective for one engagement.

The drug would be available to the player as well but the side-effects are there to stop abusing it.

**Comment by T-rexsuper1** [comment]
Good idea! 

- sincerely, Five SeveN

**Comment by N7Huntsman** [comment]
Psychite tea already reduces pain, to a limited degree--though, I don't think it's strong enough to be a combat drug in its current form.

Could make the new drug a mix of psychoid leaves and either herbal medicine or perhaps raw fungus (_a la_ the norse berserkers myth).
