### ISSUE TITLE
[Bug]: Vanilla Factions Expanded - Classical mod weapons melee bug

### ISSUE THREAD

**Issue by Tanitanino** [CombatExtended-Continued/CombatExtended#1542]
Rimworld version: 1.3 
Combat Extended version: 4.6
Combat Extended source: steam

**Description**
Vanilla Factions Expanded - Classical mod listed as patched, but weapons lack Melee Damage and Melee Armor Penetration with endless red error loop when weapon details pressed. Because of that pawns who melee using these weapons come up with Melee out of range error and freeze.

**Expected behavior**
Melee Damage and Melee Armor Penetration present and no error. No error and pawn freeze on attack.

**To reproduce**
Press details inspecting the weapons. Pawns attacking using these weapons freeze.

**Screenshots & log dumps**
![scr](https://user-images.githubusercontent.com/104689163/166114260-cc45d118-e4f6-4324-ad54-7150f4171bb6.png)
![scre](https://user-images.githubusercontent.com/104689163/166114279-cf8acf09-1abd-49b7-ab8e-aba8c133b628.png)

**Complete the following checklist**
I hereby verify that I have done the following:
- [/] Confirmed that my game version and load order are correct.
- [/] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [/] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [/] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by ItsSamGray** [comment]
The Classical patch is working as intended, make sure the load order is correct and your CE is installed properly. Try resubbing to CE just to make sure there is no problem there.

**Comment by Tanitanino** [comment]
Deleting the mod altogether and resubbing to both mods fixed the problem. Thank you for your time!
