### ISSUE TITLE
[Patch Request]: Reinforced Mechanoids: Volume One

### ISSUE THREAD

**Issue by makethiswork** [CombatExtended-Continued/CombatExtended#1547]
Mod name: Reinforced Mechanoids: Volume One

https://steamcommunity.com/sharedfiles/filedetails/?id=2798710610&searchtext=reinforced+mechanoids+volume+one

Description:
Reinforced Mechanoids, formerly known as "HALO: Rimworld Heretic Mechanoids", is an expansion of vanilla Rimworld mechanoids, adding new threats and gameplay mechanics that perfectly fit into the vanilla game.

Nearly all mechanoids brings something new to table. They have unique abilities, behavior, etc. They are not just new skins for yet another enemy that shoots you.
On top of that, the player gets new mechanoids to build, similar to "Vanilla Factions Expanded - Mechanoids" as well as ancient droids that can be acquired via quests or trades.

Still not done, the mod also adds a new way to produce power, based on an old mod called "Mechanoid Power". All with new code, textures and reworked balance.

And for owners of the Royalty DLC, the mod also adds a way to finally make use of both the weather controller and climate adjuster yourself. Something I always wished I could do!

All comes with vanilla friendly textures, lore text (well, to some degree) and balancing as good as I managed to do it. Everything is integrated into the vanilla game and will feel like it always has been there.

Content:
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by Bifidobacterium-Bifidum** [comment]
Posted a [50$ bounty](https://app.bountysource.com/issues/109913330-patch-request-reinforced-mechanoids-volume-one) on this one.
Latest test with Steam version was showing ammo cannot be picked up by crafted mechanoids, e.g. Guardian.

Thank you for the great work!

**Comment by ItsSamGray** [comment]
The patch is merged into the dev build, the ammo issues will be resolved soon in an upcoming PR.
