### ISSUE TITLE
[Feature request]:  Add ammo selection for no ammo mode

### ISSUE THREAD

**Issue by Toucan3564** [CombatExtended-Continued/CombatExtended#1566]
"No ammo mode" makes FMJ a default type that can't be switched. It might be done for balancing purposes but this already is an "easy mode" option. So making it even easier wouldn't hurt anyone

**Comment by Caulaflower** [comment]
no.

**Comment by albertbokor** [comment]
it's only there for testers' convenience, should've hidden it somewhere

**Comment by perkinslr** [comment]
This has been on the table for over a year, but no one has stepped up to implement it.  The major problem is none of the devs run no ammo mode, so it doesn't get much attention.  Bottom line: PRs welcome.
