### ISSUE TITLE
[Question]: Save our Ship 2 Weapons

### ISSUE THREAD

**Issue by Batur123** [CombatExtended-Continued/CombatExtended#1574]
Save our Ship 2 wiki and Combat Extended compatibility list says they are compatible with each other. Why SOS2 ship weapons dont use any ammo?

Edit: It gives CE error if you try to look their caliber

**Comment by perkinslr** [comment]
There are degrees of compatibility.  Many of the SOS2 weapons are just direct energy weapons, or have their own ammo system, so don't need to use CE's.  I think the railgun could maybe benefit from CE ammo?  The lasers and what not do not.  That said, the error on looking at their caliber should get fixed.

**Comment by perkinslr** [comment]
Looks like the calibers can now be examined (latest dev version).  Please re-open if that is not the case.
