### ISSUE TITLE
[Bug]: Impact Effects not showing

### ISSUE THREAD

**Issue by amaotoUsagi** [CombatExtended-Continued/CombatExtended#1575]
Some of the projectiles don't really render their impact effects(?)

Noticed it on the 81mm Antigrain mortar bomb and the laser weapons.
To show the comparison, here is a without CE (left) and with CE (right)
![No effects](https://user-images.githubusercontent.com/99400373/169032967-f20d8ca7-e28a-4bc7-9703-89b6cdc8e1f0.png)

**Comment by ItsSamGray** [comment]
Lasers are still not showing the impact effect properly but the rest are fixed in #1643.
