### ISSUE TITLE
[Bug]: Alpha Animals/Witcher Monster Hunter/Genetic Rim ranged attack logging error.

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#161]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:
Combat Extended version: 2.2.2 (current development build)
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows 10 x64 bit
Your mod list: Harmony, Core, Royalty, Alpha Animals/Witcher Monster Hunter/Genetic Rim

**Description**
The mods listed above all share the same framework by Sarge that allows creatures to have a "built in" ranged attack. While these attacks are currently functional with Combat Extended, direct-impact projectiles (in contrast to "explosions" that deal damage across an area) are causing logging errors in all three mods when they hit their target. They do not generate logs when they miss, but should do so.

**Expected behavior**
Expected the attacks to throw no errors, and to use the grammar sets included with the base mods.

**To reproduce**
Load with above modlist. Dev spawn a leshy or djinn or any other creature with a ranged attack at a moderate distance from your pawns, setting them to Manhunter, if necessary. It may take a couple of attempts to get them to use a ranged attack, rather than closing the distance for melee (making your pawns run a short distance away can also work).

**Screenshots & log dumps**
Error log: https://pastebin.com/F3VUAYFQ
Screen shots:
![20200712114142_1](https://user-images.githubusercontent.com/38633594/87251280-68948d00-c438-11ea-8128-fa7d51194eee.jpg)
![20200712114136_1](https://user-images.githubusercontent.com/38633594/87251283-6df1d780-c438-11ea-8d68-addef4e8f0e9.jpg)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by MadaraUchiha** [comment]
Please attach the entire log entry stack trace.

You can do so by adding HugsLib and clicking the new `[Copy]` button that would appear at the top right when you select a log entry. (Or alternatively just use HugsLib log sender)
