### ISSUE TITLE
[Bug]: Flesh flies from Genetics Expanded cannot be targeted

### ISSUE THREAD

**Issue by Terkontar** [CombatExtended-Continued/CombatExtended#1617]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.3389 (64bit)
Combat Extended version: 1.3.4.6
Combat Extended source (Steam, GitHub, etc.): GitHub https://github.com/CombatExtended-Continued/CombatExtended/pull/1607
Your operating system: Windows 10
Your mod list:
https://pastebin.com/gxsWa5ek

**Description**
Vanilla Genetics Expanded's Flesh Flies seem to cause issues with CE. Judging by the error message (included below), CE cannot calculate the pawn's hitbox due to the sprite's texture being fully transparent.

- They cannot be fired at; while the game does acknowledge the command (the gray line from pawn to the target), the firing operation is cancelled as soon as the game is unpaused. Tested with Lee Enfield, Mossberg, Molotov Coctail and Flamethrower
- They can't be suppressed (tested with Mossberg by force-firing at the wall behind the swarm) nor damaged by stray bullets; projectiles fly straight through the swarm
- They CAN be killed by splash damage (lightning, explosions, flames); Molotov can kill them by being thrown at the ground next to them. Flamethrower cannot be force-fired at the ground.
- They CAN be targetted and killed in melee
- They cannot be targetted by turrets
- They don't trigger traps/IEDs, though that is probably intentional since they're a swarm of flies

While the swarm being difficult/impossible to kill with conventional firearms seems to be the design goal of VGE's team, not being able to aim a flamethrower at them is an issue.

Maybe forcefully assigning the swarm a generous hitbox and giving them a lot of slashing/blunt armor would be one way to go about fixing it? It would also make it harder to kill them in melee, which would make sense. Their description literally tells the player to kill them with fire.
 
**Expected behavior**
What did you expect to happen?

Being able to aim directly at the swarm.

**To reproduce**
Dev spawn pawn "Flesh flies" and try to fire at it with any ranged weapon.  That said, for the error message to pop up on load, all you need to do is to have CE and Vanilla Genetics Expanded loaded.

**Screenshots & log dumps**
https://pastebin.com/ZtUEzZB3 <- log of the relevant error stack

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Vanilla Genetics Expanded is not yet patched to work with Combat Extended.

**Comment by PrestonTaylor** [comment]
Does the exception on loading prevent anything else from working or can it be safely ignored assuming we don't care about the flesh flies?

**Comment by Terkontar** [comment]
I haven't run into any other issues related to it, and truth be told I've been playing somewhat extensively since first submitting the report after lperkins asked me to. I encountered the flies a couple of times, and as of year 6 my colony's save still isn't bricked. If memory serves, the game doesn't even spit out the error upon actually encountering the flies during gameplay, as long as the devmode is turned off.

As far as I can tell, it seems safe to ignore.
