### ISSUE TITLE
[Bug]: Absence of Royalty DLC breaks Vanilla Armour Expanded compatibility

### ISSUE THREAD

**Issue by FORMless000** [CombatExtended-Continued/CombatExtended#1624]
Rimworld version: 1.3
Combat Extended version: 4.6
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win10
Your mod list: No Royalty, with CE and VAE

**Description**
Absence of Royalty DLC cause the Vanilla Armour Expanded patch "Armor_Spacer.xml" to fail, because when there's no royalty variations of new marine armors from VAE, the patch simply can't find the thing and fail, therefore normal VAE marine armors won't get patched.

With Royalty DLC nothing will go wrong, but I just don't like that DLC, and I'm sure there are players think the same.

To fix it simply separate the patch into two PatchOperationFindMod: one for the basic trooper/siegebreaker armor, and another one for the royalty variations.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by ItsSamGray** [comment]
This issue is already fixed in the dev build.
