### ISSUE TITLE
[Bug]: CE + Medieval Overhaul Shields Different Layer and Drastically Different Stats

### ISSUE THREAD

**Issue by mountainofcheezo** [CombatExtended-Continued/CombatExtended#1670]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.3
Combat Extended version: 4.7
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows
Your mod list:
Rimedieval - Medieval Royalty
VFE Medieval
Medieval Royalty Faction (Continued)
Medieval Overhaul
Combat Extended
Combat Extended Armor
Combat Extended Melee
Medieval - Vanilla

**Description**
Shields are using different layers and have dramatically different armor values, effects. e.g.,
Heater Shield from Medieval Overhaul: 
![image](https://user-images.githubusercontent.com/54007896/178164271-267c35ee-2d59-4431-80f5-b4db66434e7c.png)

Basic Heater Shield:
![image](https://user-images.githubusercontent.com/54007896/178164292-dacbf038-3daa-408f-bcc8-efab4959c840.png)

**Expected behavior**
What did you expect to happen?

**To reproduce**
Spawn some shields and check them out.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x ] Confirmed that my game version and load order are correct.
- [ x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by ItsSamGray** [comment]
Please try the combination with the latest dev build of CE and report back since MO has had an update and its patch was updated recently.

**Comment by ItsSamGray** [comment]
Medieval Overhaul shields are all patched for CE, you might be playing on an older version of CE than the latest dev build.
