### ISSUE TITLE
[Bug]: VWE - Makeshift causing log spam (game forces to a pause) when using with CE

### ISSUE THREAD

**Issue by feeddanoob** [CombatExtended-Continued/CombatExtended#1682]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.3
Combat Extended version: latest dev
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows 11
Your mod list:
<details>
   <summary> load order </summary>
    <li>brrainz.harmony</li>
<li>ludeon.rimworld</li>
<li>ludeon.rimworld.royalty</li>
<li>ludeon.rimworld.ideology</li>
<li>unlimitedhugs.hugslib</li>
<li>void.charactereditor</li>
<li>hahkethomemah.simplepersonalities</li>
<li>hahkethomemah.simplepersonalities.module2</li>
<li>brrainz.achtung</li>
<li>roolo.almostthere</li>
<li>kentington.saveourship2</li>
<li>sarg.alphaships</li>
<li>spoonshortage.adogsaidanimalprosthetics</li>
<li>vanillaexpanded.achievements</li>
<li>owlchemist.cherrypicker</li>
<li>oskarpotocki.vanillafactionsexpanded.core</li>
<li>sarg.alphaanimals</li>
<li>vanillaexpanded.vaeaccessories</li>
<li>oskarpotocki.vfe.insectoid</li>
<li>rimfridge.kv.rw</li>
<li>lwm.deepstorage</li>
<li>oskarpotocki.vfe.mechanoid</li>
<li>vanillaexpanded.vwe</li>
<li>oskarpotocki.vanillafactionsexpanded.medievalmodule</li>
<li>oskarpotocki.vfe.pirates</li>
<li>vanillaexpanded.vcef</li>
<li>vanillaexpanded.vcefaddon</li>
<li>vanillaexpanded.vtexe.sos2</li>
<li>oskarpotocki.vanillafactionsexpanded.settlersmodule</li>
<li>vanillaexpanded.vwec</li>
<li>vanillaexpanded.vwehw</li>
<li>vanillaexpanded.vwel</li>
<li>vanillaexpanded.vweq</li>
<li>vanillaexpanded.vweft</li>
<li>vanillaexpanded.vweg</li>
<li>vanillaexpanded.vwenl</li>
<li>ceteam.combatextended</li>
<li>dylan.animalgear</li>
<li>owlchemist.animalgear.equipment</li>
<li>fluffy.animaltab</li>
<li>mrcool92.agoc</li>
<li>oblitus.animalslogic</li>
<li>revolus.animalsarefun</li>
<li>automatic.autolinks</li>
<li>meltup.beautifuloutdoors</li>
<li>voult.betterpawncontrol</li>
<li>chippedchap.blueprinttotalstooltip</li>
<li>crashm.colorcodedmoodbar.11</li>
<li>brrainz.cameraplus</li>
<li>owlchemist.cleanpathfinding</li>
<li>ceteam.combatextendedarmors</li>
<li>ceteam.combatextendedguns</li>
<li>com.lpprogramming.rimworld.cefixes</li>
<li>ceteam.combatextendedmelee</li>
<li>n7huntsman.combatextendedshields</li>
<li>mlie.combatreadinesscheck</li>
<li>avilmask.commonsense</li>
<li>yoann.commonsenseopportunisticcleaningpatch</li>
<li>squirtingelephant.cofigurableroomstats</li>
<li>mlie.convertthenenslave</li>
<li>mlie.convertthenrecruit</li>
<li>kikohi.cybernetic</li>
<li>troopersmith1.deathrattle</li>
<li>sumghai.defensivemachinegunturretpack</li>
<li>unlimitedhugs.defensivepositions</li>
<li>mlie.dismisstrader</li>
<li>mlie.drugpolicyfix</li>
<li>com.github.alandariva.moreplanning</li>
<li>unlimitedhugs.allowtool</li>
<li>dubwise.dubsmintmenus</li>
<li>dubwise.dubsmintminimap</li>
<li>bs.performance</li>
<li>dubwise.dubsperformanceanalyzer</li>
<li>mlie.enterhere</li>
<li>falconne.bwm</li>
<li>uuugggg.everybodygetsone</li>
<li>syrchalis.traitvalue</li>
<li>fuglypump.fallouttraits</li>
<li>fluffy.followme</li>
<li>ratys.rtfuse</li>
<li>neceros.fuseplus</li>
<li>roolo.whatthehack</li>
<li>roolo.giddyupcore</li>
<li>roolo.giddyupbattlemounts</li>
<li>roolo.giddyupcaravan</li>
<li>roolo.giddyupmechanoids</li>
<li>roolo.giddyuprideandroll</li>
<li>telefonmast.graphicssettings</li>
<li>arandomkiwi.huntforme</li>
<li>jaxe.bubbles</li>
<li>oskarpotocki.vfe.vikings</li>
<li>kit.vfeweapons</li>
<li>lbeaston.adogsaideasypatcher</li>
<li>smashphil.loadinginprogress</li>
<li>m00nl1ght.mappreview</li>
<li>notfood.mendandrecycle</li>
<li>name.krypt.rimworld.moddiff</li>
<li>modsyncrw.kv.rw</li>
<li>dubwise.rimefeller</li>
<li>vanillaexpanded.vfea</li>
<li>vanillaexpanded.vfepower</li>
<li>vanillaexpanded.vfesecurity</li>
<li>dra.morerimefellercompat</li>
<li>telardo.nolaggybed</li>
<li>mlie.noversionwarning</li>
<li>vanillaexpanded.vcooke</li>
<li>vanillaexpanded.vmemese</li>
<li>harkon.gunnut.core</li>
<li>harkon.gunnut.fnscar</li>
<li>harkon.ceaddon.cegunsvanillaexpandedconsistencypatch</li>
<li>feeddanoob.noobedit</li>
<li>mehni.numbers</li>
<li>ogre.ogrestack</li>
<li>com.bymarcin.architecticons</li>
<li>proxyer.optionalicons4ai</li>
<li>fed1splay.pawntargetfix</li>
<li>fluffy.pharmacist</li>
<li>supes.powerlogic.core</li>
<li>spdskatr.projectrimfactory</li>
<li>spdskatr.projectrimfactory.drones</li>
<li>avilmask.psychicharmonizerlagfix</li>
<li>hatti.qualitybuilder</li>
<li>ogliss.thewhitecrayon.quarry</li>
<li>jgh.quarry</li>
<li>malteschulze.rimmsqol</li>
<li>sandy.rpgstyleinventory.avilmask.revamped</li>
<li>ratys.rtsolarflareshield</li>
<li>woolstrand.realruins</li>
<li>mlie.realistichumansounds</li>
<li>vanillaexpanded.ui</li>
<li>jaxe.rimhud</li>
<li>automatic.recipeicons</li>
<li>uuugggg.replacestuff</li>
<li>vanillaexpanded.vfecore</li>
<li>garethp.replacestuffcompatibility</li>
<li>uuugggg.tdpack</li>
<li>vinalx.researchpalforked</li>
<li>scorpio.resourcedictionary</li>
<li>rupal.rimpymodmanagerdatabase</li>
<li>dubwise.rimatomics</li>
<li>trugerman.rimatomicssospatch</li>
<li>bardez.automated.autoclave</li>
<li>rimsenal.evp</li>
<li>rimsenal.core</li>
<li>mrkociak.morewthmechimplants</li>
<li>rimsenal.federation</li>
<li>seohyeon.bestdrugpolicy</li>
<li>roolo.searchanddestroy</li>
<li>uuugggg.sharetheload</li>
<li>blues.shortcircuit</li>
<li>erdelf.showmoddesignators</li>
<li>petetimessix.simplesidearms</li>
<li>owlchemist.smartfarming</li>
<li>sarg.smartspeed</li>
<li>dhultgren.smarterconstruction</li>
<li>legodude17.smartdecon</li>
<li>weilbyte.snapout</li>
<li>scherub.stonecuttingextended</li>
<li>mlie.stufflist</li>
<li>ghxx.techadvancing</li>
<li>mlie.uselessfilter</li>
<li>oskarpotocki.vanillaexpanded.ideologypatches</li>
<li>oskarpotocki.vanillaexpanded.royaltypatches</li>
<li>seos.vfe.mechanoids.tab</li>
<li>hg.addons.vfemnhn</li>
<li>vanillaexpanded.vaeas</li>
<li>vanillaexpanded.vaeau</li>
<li>vanillaexpanded.vaebf</li>
<li>vanillaexpanded.vaecd</li>
<li>vanillaexpanded.vaecaves</li>
<li>vanillaexpanded.vaed</li>
<li>vanillaexpanded.vaeendandext</li>
<li>vanillaexpanded.vaeed</li>
<li>vanillaexpanded.vaeis</li>
<li>vanillaexpanded.vaetf</li>
<li>vanillaexpanded.vaetr</li>
<li>vanillaexpanded.vaets</li>
<li>vanillaexpanded.vaet</li>
<li>vanillaexpanded.vappe</li>
<li>mory.vapsos</li>
<li>vanillaexpanded.varme</li>
<li>vanillaexpanded.vcookestews</li>
<li>vanillaexpanded.vcookesushi</li>
<li>oskarpotocki.vfe.classical</li>
<li>puremj.mjrimmods.vanillafixhaulafterslaughter</li>
<li>vanillaexpanded.vfeart</li>
<li>vanillaexpanded.vfefarming</li>
<li>vanillaexpanded.vfemedical</li>
<li>vanillaexpanded.vfeproduction</li>
<li>vanillaexpanded.ideo.dryads</li>
<li>vanillaexpanded.viehar</li>
<li>vanillaexpanded.ideo.iconsandsymbols</li>
<li>vanillaexpanded.ideo.relicsandartifacts</li>
<li>vanillaexpanded.vpersonaweaponse</li>
<li>vanillaexpanded.vplantse</li>
<li>archoran.utils.vpeautoplow</li>
<li>vanillaexpanded.vplantsemore</li>
<li>vanillaexpanded.vanillasocialinteractionsexpanded</li>
<li>vanillaexpanded.vtexe</li>
<li>vanillaexpanded.vanillatradingexpanded</li>
<li>vanillaexpanded.vwems</li>
<li>vanillaexpanded.vwetb</li>
<li>mlie.variousspaceshipchunk</li>
<li>murmur.walllight</li>
<li>mehni.pickupandhaul</li>
<li>codeoptimist.jobsofopportunity</li>
<li>orion.xevarimhair</li>
<li>smashphil.xmlpatchhelper</li>
<li>notfood.yasp</li>
<li>mlie.morefactioninteraction</li>
<li>orion.hospitality</li>
<li>vanillaexpanded.vbrewe</li>
<li>vanillaexpanded.vbrewecandt</li>
<li>frozensnowfox.complexjobs</li>
<li>frozensnowfox.vanillabionicsexpansion</li>
<li>fuu.autostriponhaul</li>
<li>harkon.gunnut.gaussrifle</li>
<li>harkon.gunnut.aachoneybadger</li>
<li>carnysenpai.enableoversizedweapons</li>
<li>harkon.gunnut.chapter1</li>
<li>harkon.gunnut.chapter2</li>
<li>harkon.gunnut.coltanaconda</li>
<li>harkon.gunnut.community</li>
<li>harkon.gunnut.dtmdrx</li>
<li>harkon.gunnut.krissvector</li>
<li>harkon.gunnut.ksgshotgun</li>
<li>harkon.gunnut.rugermini</li>
<li>harkon.gunnut.sigsauerngsw</li>
<li>harkon.gunnut.sovietsmgs</li>
<li>harkon.gunnut.ukrainianfirearms</li>
<li>harkon.gunnut.m97trenchgun</li>
<li>vanillaexpanded.vfearchitect</li>
<li>vanillaexpanded.vfespacer</li>
<li>harkon.veaddon.vanillaexpandedextraembrasures</li>
<li>moretraitslots.kv.rw</li>
<li>recolorstockpile.kv.rw</li>
<li>savestoragesettings.kv.rw</li>
<li>tradingspot.kv.rw</li>
<li>mlie.wikirim</li>
<li>cp.rimmunation.2.clothing</li>
<li>cp.rimmunation.2.security</li>
<li>syrchalis.lightradius</li>
<li>taranchuk.performanceoptimizer</li>
<li>krkr.rocketman</li>
</details>

**Description**
Provide a concise description of the issue or concern. What happened?
A raid happened and my pawn equipped a makeshift shotgun with the slug ammo type. My game then would not unpause until I unequipped the gun. I created a separate map and tried with other makeshift weapons, I only found that the shotgun and pistol causes the game to freak out.

**Expected behavior**
What did you expect to happen?
When using the makeshift shotgun loaded with either slug or buck ammo and attacking a wall I expect it to fire shots.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Equip a makeshift shotgun or a makeshift pistol with any ammo, buck, slug, fmj, etc., and target a fireable object, like a wall or an animal.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here.
A github log is provided.
This is the one where it happened on a save I was playing.
https://gist.github.com/515f451e5b34265f81c3f231be67554d

This is the one where it happened on a test map.
https://gist.github.com/9d9ef3bf94a71a7cc8b9365af9049946

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by feeddanoob** [comment]
okay here is a log with Harmony, Hugs, CE, VEF, and VWE - Makeshift installed

https://gist.github.com/6133c66c88f8d7ef4bc56c59d9d288bc

there are two errors at the bottom, the first was just from equipping the shotgun the first time, the second was trying to shoot the shotgun with a slug.
I tried shooting the shotgun with a buck but the same type of error showed. The pistol one worked like expected unlike in my previous test.

**Comment by perkinslr** [comment]
This looks related... `[MVCF] Found equipment with more than one ranged attack while that feature is not enabled. Enabling now. This is not recommend. Contact the author of Vanilla Weapons Expanded - Makeshift and ask them to add a MVCF.ModDef. `

It looks like something is enabling a second verb on the makeshift gun, and that verb is not properly patched for CE.  Just speculation on my part.  I'll see if I can reproduce it here in a bit.

**Comment by feeddanoob** [comment]
RE better pawn control error:
I think I fixed it using the method https://steamcommunity.com/workshop/filedetails/discussion/1541460369/3416559391444879136/
