### ISSUE TITLE
[Warning]Warning at the startup

### ISSUE THREAD

**Issue by Raik3l** [CombatExtended-Continued/CombatExtended#1691]
Load:
Core
DLCs
Combat Extended.

There are two warnings at the startup:
1. Type ITab_Inventory probably needs a StaticConstructorOnStartup attribute, because it has a field _iconEditAttachments of type Texture2D. All assets must be loaded in the main thread.
2. Type GizmoAmmoStatus probably needs a StaticConstructorOnStartup attribute, because it has a field FullTex of type Texture2D. All assets must be loaded in the main thread.

**Comment by SamaelGray** [comment]
Solved.
