### ISSUE TITLE
[Bug]: Unable to shoot through Medieval Overhaul (MO) Castle Embrasures

### ISSUE THREAD

**Issue by arvalaan** [CombatExtended-Continued/CombatExtended#1705]
**Specifications**
Rimworld version: 1.3.3389
Combat Extended version: Latest Dev Snapshot as of 2nd of August 17:51 GMT+2
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows 11
Your mod list: Harmony, Core, Royalty, Ideology, HugsLib, LWM's Deep Storage, Vanilla Expanded Framework, [SYR] Processor Framework, Medieval Overhaul, Combat Extended

**Description**
A pawn, equipped with a War Bow and Great Arrows is not shooting at pawns he/she is targeting when standing behind Castle Embrasures.

**Expected behavior**
Expected the Castle Embrasure to function the same as the CE Embrasures, namely that a Pawn can shoot when taking cover behind it.

**To reproduce**
Use the above-mentioned mod list, position Pawn with War Bow and Arrows behind Castle Embrasure, then target (friendly) other pawn and observe; nothing happens.
**Screenshots & log dumps**
![image](https://user-images.githubusercontent.com/9444629/182418644-a605675f-4fc0-451f-9693-80ee7dd9a8f7.png)
![image](https://user-images.githubusercontent.com/9444629/182418901-70681bbd-5270-4d09-ba76-8a095db1f6d1.png)
(Clementine was not harmed in this process)

No errors are popping up.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by mountainofcheezo** [comment]
I have the same issue.

**Comment by ANA7332** [comment]
Same.

**Comment by ANA7332** [comment]
Thanks!

**Comment by ANA7332** [comment]
> I fixed it myself by adding a new XML file to the Medieval Overhaul patch filed in Combat Extended.
> 
> Path: SteamLibrary\steamapps\common\RimWorld\Mods\CombatExtended\Patches\Medieval Overhaul\MO_Buildings.xml
> 
> Contents:
> 
> ```
> <?xml version="1.0" encoding="utf-8" ?>
> <Patch>
> 
>   <Operation Class="PatchOperationFindMod">
>     <mods>
>       <li>Medieval Overhaul</li>
>     </mods>
>     <match Class="PatchOperationSequence">
>       <operations>
> 
>                 
>         <li Class="PatchOperationReplace">
>             <xpath>Defs/ThingDef[defName="DankPyon_CastleWallEmbrasures"]/fillPercent</xpath>
>             <value>
>                 <fillPercent>0.7</fillPercent>      
>             </value>
>         </li>
> 
>         </operations>
> 	</match>
> 	</Operation>
> 
> </Patch>
> ```
> 
> The issue here being that the Castle Embrasures are too high (apparently). This patches them to be the same height as the embrasures that are included in CE.

Thanks!
