### ISSUE TITLE
[Patch Request]: Medieval Overhaul

### ISSUE THREAD

**Issue by mountainofcheezo** [CombatExtended-Continued/CombatExtended#1708]
Medieval Overhaul

[**Link to mod download (preferably Steam workshop or Github):**](https://steamcommunity.com/sharedfiles/filedetails/?id=2553700067)

**Description:**
Bunch of medieval weapons, armors, etc.

Please make musket balls craftable at either workbench or at anvil, right now they are only craftable at fueled smithy. Thanks.

**Content:**
What does the new mod contain? Check all that apply.
- [x ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [x ] New factions.
- [ x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x ] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [ x] Confirmed there are no other open Patch Requests for this mod.
- [ x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x ] **Have completed this template accurately and completely.**
- [ x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [ x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by ItsSamGray** [comment]
Most of the mod is patched, some new stuff seem to have been added which need a patch.
One of the new things is a castle embrasure which its cover height is not patched.

**Comment by mountainofcheezo** [comment]
Sorry if the tag was incorrect, I’m hoping to fix the fact that you can’t craft musket balls at anvil or crafting table. I’ve fixed it on my local copy, am I allowed to edit it on the GitHub?
