### ISSUE TITLE
[Discussion]: Ammo crafting work cost rework.

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#1744]
Different ammo type categories have the same crafting work cost. FMJ, AP and HP rounds have the same cost while realistically AP rounds should be harder and take more time to craft.
The same is kinda true for AP-I and HE ones that should require more work.
A readjustment to the ammo spreadsheet in regards to ammo crafting work cost would be helpful.

**Comment by T-rexsuper1** [comment]
I agree. I personally use a mod that makes ammo crafting more balanced because 500 rounds for 20 steel for any basic ammo type is kinda bs.

**Comment by ItsSamGray** [comment]
> I agree. I personally use a mod that makes ammo crafting more balanced because 500 rounds for 20 steel for any basic ammo type is kinda bs.

This is directed towards the work amount needed to craft ammo, not the materials.
