### ISSUE TITLE
[Discussion]: Red Horse and Rimmu-Nation Patches Consolidation

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#178]
The Red Horse and Rimmu-Nation mods are something of a headache due to the fact that multiple mods use the same defName. I believe the most practical thing to do would be to consolidate the patch files as much as possible, starting the patch sequence by finding any of a long list of mods and then checking conditionally for each item. 
```
<Operation Class="PatchOperationFindMod">
<mods>
   <li>[RH] Faction: War Mongrels</li>
</mods>
  <match Class="PatchOperationSequence">
   <operations>

<li Class="PatchOperationConditional">
    <xpath>/Defs/WorldObjectDef[defName="ANY_RH_GUN"]</xpath>
    <match Class="CombatExtended.PatchOperationMakeGunCECompatible">
     ....
     ....
     ....
    </match>
</li>

<li Class="PatchOperationConditional">
    <xpath>/Defs/WorldObjectDef[defName="ANOTHER_RH_GUN"]</xpath>
    <match Class="CombatExtended.PatchOperationMakeGunCECompatible">
     ....
     ....
     ....
    </match>
</li>

</operations>
</match>
</Operation>
</Patch>
```
While it would be quite a bit of work to set up, it would reduce the work necessary to create new patches, would completely prevent duplicates, and might even be a net improvement in load time.

**Comment by onigamii** [comment]
This seems to be the best option because i noticed that most RH faction mods just copy-paste the gun defs and all we have now is just the same patch just on different files
