### ISSUE TITLE
[Patch Request]:HALO: Rimworld Auxiliary Combat Armory

### ISSUE THREAD

**Issue by Vyncis** [CombatExtended-Continued/CombatExtended#181]
**Mod name:**
HALO: Rimworld Auxiliary Combat Armory

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=1961456342

**Description:**
HALO:RACA adds a series of halo themed charge weapons. 11 assault rifles/pistols/smgs/etc. 2 shotguns. 1 rocket launcher (currently functional). 1 grenade launcher

(**Unsure if useful for patching purposes but some info about how it doesn't work currently:** The mod doesn't result in significant red errors or crash the game. Charge weapons cannot be equipped, attempting to do so automatically unequips them. They can be equipped via the loadout system, where they aim but do not fire.)

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Comment by N7Huntsman** [comment]
An integrated patch for this mod has already been added.
