### ISSUE TITLE
[Patch Request]: CE patch for "Kurin, The Three Tailed Fox [I3's Addon] (KTTFI3A)"

### ISSUE THREAD

**Issue by hararam-12** [CombatExtended-Continued/CombatExtended#183]
**Mod name: Kurin, The Three Tailed Fox [I3's Addon] (KTTFI3A)**

**Link to mod download (preferably Steam workshop or Github): https://steamcommunity.com/sharedfiles/filedetails/?id=2156596056**

**Description:**
KTTFI3A adds new weapons, pawnkinds, scenarios and apparels, which have to be patched with CE.

**Content:**
What does the new mod contain? Check all that apply.
- [ y ] New weapons.
- [ n ] New animals, humanoids, or other creatures.
- [ n ] New factions.
- [ y ] New armor or apparel.

I have already done some work with CE patch for KTTFI3A, it has errors, but briefly - it works.

[CE_KTTFI3A.zip](https://github.com/CombatExtended-Continued/CombatExtended/files/4982106/CE_KTTFI3A.zip)

**Comment by N7Huntsman** [comment]
Already patched. https://github.com/CombatExtended-Continued/CombatExtended/tree/Development/Patches/Kurin
