### ISSUE TITLE
[Bug]: Revert the reload time and magazine capacity entries separation

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#1843]
What it says on the tin, the two aforementioned info were separated in this PR https://github.com/CombatExtended-Continued/CombatExtended/pull/971 which cause an inconvenience when reading the two stats, the old method of showing them was much more readable.

**Comment by Safairette** [comment]
Relevant links: [the removal commit](https://github.com/CombatExtended-Continued/CombatExtended/commit/39d5f810de02d0735a0d161b6e394e5524889df5#diff-8204995b072065d028092bfbe20f16b23760e76114e656f7fbb23dd828d9ff3d)
