### ISSUE TITLE
[Discussion]: CE's mechanoid gun retextures

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#1865]
The current mechanoid weapon retextures that exist in CE are kinda problematic in several ways.

First, they clash with modded mechanoid guns that all adhere to a preset vanilla scheme, no matter what and how we do, meaning retexturing them again in a different style, it's still not the same gun.
Second, they look very cursed and bad when mounted on turrets since they are not top down.
Third, the color scheme is not right which ties into the first point.
Fourth, not every little thing in the game should be touched or changed by CE, it is correct that the vanilla conventional guns have a new texture in CE but they still are the same gun but better looking, barring the rocket launchers which we all agree in them looking bad and don't have a modded counterpart to clash with.
Fifth, the new mechanoid gun textures are not retextured and have the vanilla texture which retexturing them in the same existing style or a new one which would replace them all would still tie into the fourth and first issue.

My proposed idea is to remove them entirely and leave the mechanoid guns have the vanilla texture to save ourselves the hassle and stay consistent with the 100500 mech gun textures out there, mech guns are top-down like turret guns and have a distinct and iconic look which should not be touched.

**Comment by Safairette** [comment]
I suggest this compromise:
 - I retexture the Inferno Cannon, Charge Lance and possibly the Bolt Projector to follow the vanilla color scheme and keep the more realistic proportions we have in our artstyle
 - After that we make separate textures for the guns to be used in turrets, following the turret texture conventions
 
That way we can preserve our artstyle while minimizing visual conflicts with other mods
