### ISSUE TITLE
[Discussion]: Legendary and Masterwork guns

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#1867]
Since guns in CE don't benefit from quality as much as in vanilla for some guns even less than others, especially damage-wise, it might be a good idea to introduce a slight damage boost (5% and 10% for legendary and masterwork quality respectively) to high quality guns to simulate a better muzzle velocity resulting in more damage dealt by the gun. 
The current accuracy boost does not matter for precision guns which are already almost capped accuracy-wise and quests can have high quality guns as rewards which are sub-par in comparison to other rewards.

This'd make spending inspirations on guns a bit more viable in comparison to armor pieces which scale greatly with quality.

**Comment by sumghai** [comment]
Sounds good to me!

**Comment by T-rexsuper1** [comment]
Agreed
