### ISSUE TITLE
[Patch Request]: SRTS Expanded and variants

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#187]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**

**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**

**Title should be:** [Patch Request]: (Mod Name)

**Mod name:** SRTS Expanded

**Link to mod download (preferably Steam workshop or Github):** https://github.com/Neceros/SRTS-Expanded

**Description:**
The mod (and others based upon it, like Rimheli) provides different forms of air transport. Most significantly, some of these aircraft are capable of being loaded with mortar shells to perform bombing runs. I think ideally, it would be possible to dictate in .xml an ammo set (like for turrets) in order to be able to dictate different munitions (and munition types) for different craft.

If that proves to be impractical, hopefully the existing framework for loading the aircraft can be made compatible with CE.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel. (I'm told the apparel has already been patched)

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
An interesting development. I spoke w/ Smash Phil, and it seems a rework of SRTS is on the horizon, including the bomb-dropping mechanic. There's the intention to make it more modder-friendly, which should hopefully simplify the task on our end. Smash should touch base on the CE discord regarding this in the future, when the rework is closer to being realized (Smash estimated around the Oct. - Nov. timeframe).

So, for the time being, this item can sit.

**Comment by N7Huntsman** [comment]
Relevant, from Smash Phil:
```
A bit of clarification...
Both Neceros and I work on SRTS. Right now he's waiting for me to finish the vehicle framework because I said I would integrate the code I wrote for reusable shuttles / bombing into it... so you can have shuttles somewhat similar to SoS2, but with less bugs (as well as some other new features).
Neceros has nothing to do with vehicles apart from being an extremely valued beta tester and hype man, so please don't go and bug him with questions unless he's cool with it. He tends to know what's goin on with it more than anyone else besides me.

So going forward it's 3 completely separate mods.
Vehicles (name TBD)
SRTS (will have dependency on Vehicles)
Vanilla Vehicles Expanded

Oskar will have his own release which I'm sure includes plenty of new vehicles to add to the framework, cause I'm only adding like 5 or 6 land vehicles.
So yea he is expanding on something... my framework. 
SRTS isn't on the backburner per se, it's just being integrated  into the vehicle framework so there's sea air and land vehicles (Boats is getting absorbed into it as well). Mechanics will be drastically different than what the two mods (boats and srts) currently offer. I mean functionally speaking they're the same but there have been so many changes / improvements since 1.1 dropped so you can expect many of the bugs / issues that currently exist to be fixed. Then I have all of my vehicle mods in one place and can let people just build off them. 

Oskar and I will work closely on his expansion for my framework so it can be unique and fun, but that's all I'll really spoil.  Now you guys have your definitive answers.
```

**Comment by Breadbox2k19** [comment]
https://github.com/AluminumAlman/SRTS-Expanded

Pasting the CE compatible SRTS fork here, just in case I forgot where it is.
