### ISSUE TITLE
[Bug]: Thousand repeating error messages with Combat Extended in the error lines.

### ISSUE THREAD

**Issue by Chance713** [CombatExtended-Continued/CombatExtended#1879]
[Bug]: Thousand repeating error messages with Combat Extended in the error lines.

**Specifications**
Rimworld version: 1.3.3389 rev40
Combat Extended version: Newest Steam release as of today (last updated Aug 20th)
Combat Extended source: Steam
Your operating system: Windows 10 Home 64-bit (10.0, Build 18363) (18362.19h1_release.190318-1202)
Your mod list:
[Mod list length: 128]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
Animals Logic [https://steamcommunity.com/sharedfiles/filedetails/?id=1098354593]
Better ModMismatch Window [https://steamcommunity.com/sharedfiles/filedetails/?id=1872244972]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Better ground-penetrating scanner [https://steamcommunity.com/sharedfiles/filedetails/?id=2809972387]
Bounded Roof Build Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=1104718095]
Bulk Smelting [https://steamcommunity.com/sharedfiles/filedetails/?id=2060240608]
Bulk Stonecutting [https://steamcommunity.com/sharedfiles/filedetails/?id=2556049999]
Camera+ [https://steamcommunity.com/sharedfiles/filedetails/?id=867467808]
Cargo container [https://steamcommunity.com/sharedfiles/filedetails/?id=2725808118]
Character Editor [https://steamcommunity.com/sharedfiles/filedetails/?id=1874644848]
Clean Pathfinding [https://steamcommunity.com/sharedfiles/filedetails/?id=2603765747]
Compact Hediffs [https://steamcommunity.com/sharedfiles/filedetails/?id=2031734067]
De-generalize Work [https://steamcommunity.com/sharedfiles/filedetails/?id=2011655761]
Defensive Positions [https://steamcommunity.com/sharedfiles/filedetails/?id=761219125]
Designator Shapes [https://steamcommunity.com/sharedfiles/filedetails/?id=1235181370]
Common Sense [https://steamcommunity.com/sharedfiles/filedetails/?id=1561769193]
Dubs Break Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=1722398508]
Dubs Central Heating [https://steamcommunity.com/sharedfiles/filedetails/?id=2619214952]
More Planning 1.3 [https://steamcommunity.com/sharedfiles/filedetails/?id=2551225702]
Allow Tool [https://steamcommunity.com/sharedfiles/filedetails/?id=761421485]
Dubs Mint Menus [https://steamcommunity.com/sharedfiles/filedetails/?id=1446523594]
Dubs Paint Shop [https://steamcommunity.com/sharedfiles/filedetails/?id=1579516669]
Dubs Performance Analyzer [https://steamcommunity.com/sharedfiles/filedetails/?id=2038874626]
Dubs Rimatomics [https://steamcommunity.com/sharedfiles/filedetails/?id=1127530465]
Fences And Floors (Continued) [https://steamcommunity.com/sharedfiles/filedetails/?id=2012420113]
Fluffy Breakdowns (1.3 Update) [https://steamcommunity.com/sharedfiles/filedetails/?id=2584064444]
Follow Me [https://steamcommunity.com/sharedfiles/filedetails/?id=715759739]
Vanilla Furniture Expanded - Security [https://steamcommunity.com/sharedfiles/filedetails/?id=1845154007]
Fortifications - Industrial [https://steamcommunity.com/sharedfiles/filedetails/?id=2561619583]
Fortification Industrial -Nuclear Dawn [https://steamcommunity.com/sharedfiles/filedetails/?id=2733185331]
Fortifications - Medieval [https://steamcommunity.com/sharedfiles/filedetails/?id=2501486827]
Go Explore! [https://steamcommunity.com/sharedfiles/filedetails/?id=1814100216]
Impassable Chest-deep Water [https://steamcommunity.com/sharedfiles/filedetails/?id=1674624795]
List Everything [https://steamcommunity.com/sharedfiles/filedetails/?id=1706669545]
Map Reroll [https://steamcommunity.com/sharedfiles/filedetails/?id=761315214]
Map Preview [https://steamcommunity.com/sharedfiles/filedetails/?id=2800857642]
Mass Graves [https://steamcommunity.com/sharedfiles/filedetails/?id=1542386771]
Meals On Wheels [https://steamcommunity.com/sharedfiles/filedetails/?id=1323773476]
Metal Don't Burn (UNOFFICIAL 1.3 PATCH) [https://steamcommunity.com/sharedfiles/filedetails/?id=2557145474]
Misc. Training [https://steamcommunity.com/sharedfiles/filedetails/?id=717575199]
Vanilla Furniture Expanded - Power [https://steamcommunity.com/sharedfiles/filedetails/?id=2062943477]
More Linkables [https://steamcommunity.com/sharedfiles/filedetails/?id=1103809207]
Music Manager [https://steamcommunity.com/sharedfiles/filedetails/?id=2229205672]
Achtung! [https://steamcommunity.com/sharedfiles/filedetails/?id=730936602]
LWM's Deep Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1617282896]
[JDS] Simple Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=1961098970]
Netrve's DeepStorage GUI [https://steamcommunity.com/sharedfiles/filedetails/?id=2169841018]
P-Music [https://steamcommunity.com/sharedfiles/filedetails/?id=725130005]
Pick Up And Haul [https://steamcommunity.com/sharedfiles/filedetails/?id=1279012058]
Camping Tent [https://steamcommunity.com/sharedfiles/filedetails/?id=2407128339]
Post-apocalyptic Shelters [https://steamcommunity.com/sharedfiles/filedetails/?id=2444147091]
Prison Labor [https://steamcommunity.com/sharedfiles/filedetails/?id=1899474310]
Quarry [https://steamcommunity.com/sharedfiles/filedetails/?id=2007576583]
Vanilla Apparel Expanded — Accessories [https://steamcommunity.com/sharedfiles/filedetails/?id=2521176396]
Vanilla Factions Expanded - Pirates [https://steamcommunity.com/sharedfiles/filedetails/?id=2723801948]
Vanilla Factions Expanded - Settlers [https://steamcommunity.com/sharedfiles/filedetails/?id=2052918119]
Vanilla Weapons Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814383360]
Vanilla Weapons Expanded - Heavy Weapons [https://steamcommunity.com/sharedfiles/filedetails/?id=2329126791]
Vanilla Weapons Expanded - Frontier [https://steamcommunity.com/sharedfiles/filedetails/?id=2454918139]
Vanilla Weapons Expanded - Grenades [https://steamcommunity.com/sharedfiles/filedetails/?id=2194472657]
Vanilla Weapons Expanded - Non-Lethal [https://steamcommunity.com/sharedfiles/filedetails/?id=2454918354]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
RPG Style Inventory Revamped [https://steamcommunity.com/sharedfiles/filedetails/?id=2478833213]
RT Fuse [https://steamcommunity.com/sharedfiles/filedetails/?id=728314182]
Realistic Rooms [1.3] [https://steamcommunity.com/sharedfiles/filedetails/?id=2553724273]
Replace Stuff [https://steamcommunity.com/sharedfiles/filedetails/?id=1372003680]
TD Enhancement Pack [https://steamcommunity.com/sharedfiles/filedetails/?id=1339135272]
ResearchPal - Forked [https://steamcommunity.com/sharedfiles/filedetails/?id=2351393394]
Blueprints [https://steamcommunity.com/sharedfiles/filedetails/?id=708455313]
Vanilla UI Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2749945924]
RimHUD [https://steamcommunity.com/sharedfiles/filedetails/?id=1508850027]
RimPy Mod Manager Database [https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158]
RimSaves [https://steamcommunity.com/sharedfiles/filedetails/?id=1713367505]
RimThemes [https://steamcommunity.com/sharedfiles/filedetails/?id=1668983184]
RunAndGun [https://steamcommunity.com/sharedfiles/filedetails/?id=1204108550]
Search and Destroy [https://steamcommunity.com/sharedfiles/filedetails/?id=1467764609]
Share The Load [https://steamcommunity.com/sharedfiles/filedetails/?id=1356838246]
Simple sidearms [https://steamcommunity.com/sharedfiles/filedetails/?id=927155256]
Smart Speed [https://steamcommunity.com/sharedfiles/filedetails/?id=1504723424]
Smarter Construction [https://steamcommunity.com/sharedfiles/filedetails/?id=2202185773]
Callouts [https://steamcommunity.com/sharedfiles/filedetails/?id=2362736503]
Interaction Bubbles [https://steamcommunity.com/sharedfiles/filedetails/?id=1516158345]
SpeakUp [https://steamcommunity.com/sharedfiles/filedetails/?id=2502518544]
Stabilize [https://steamcommunity.com/sharedfiles/filedetails/?id=2023407836]
Stack XXL [https://steamcommunity.com/sharedfiles/filedetails/?id=826366050]
Subsurface Conduit [https://steamcommunity.com/sharedfiles/filedetails/?id=1609226728]
Trait Rarity Colors [https://steamcommunity.com/sharedfiles/filedetails/?id=1751884355]
Vanilla Animals Expanded — Cats and Dogs [https://steamcommunity.com/sharedfiles/filedetails/?id=1823540489]
Vanilla Apparel Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1814987817]
Vanilla Backstories Expanded [https:// no link (local mod)]
Vanilla Base Generation Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2830358905]
Vanilla Cooking Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308519]
Vanilla Cooking Expanded - Stews [https://steamcommunity.com/sharedfiles/filedetails/?id=2134312965]
Vanilla Events Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1938420742]
Vanilla Expanded - Ideology Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2566669771]
Vanilla Expanded - Royalty Patches [https://steamcommunity.com/sharedfiles/filedetails/?id=2260012940]
Vanilla Fishing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1914064942]
Vanilla Furniture Expanded - Medical Module [https://steamcommunity.com/sharedfiles/filedetails/?id=1718191613]
Vanilla Furniture Expanded - Production [https://steamcommunity.com/sharedfiles/filedetails/?id=1880253632]
Vanilla Hair Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1888705256]
[KV] Path Avoid [https://steamcommunity.com/sharedfiles/filedetails/?id=1180719857]
Vanilla Outposts Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2688941031]
Vanilla Plants Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2134308522]
Vanilla Skills Expanded [https:// no link (local mod)]
Vanilla Social Interactions Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2439736083]
Vanilla Trading Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2785616901]
Vanilla Weapons Expanded - Makeshift [https://steamcommunity.com/sharedfiles/filedetails/?id=2419690698]
Vanilla Weapons Expanded - Tribal [https://steamcommunity.com/sharedfiles/filedetails/?id=2454918552]
Wall Light [https://steamcommunity.com/sharedfiles/filedetails/?id=1423699208]
What Is My Purpose [https://steamcommunity.com/sharedfiles/filedetails/?id=1346064449]
What's That Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2258431182]
World Map Beautification Project [https://steamcommunity.com/sharedfiles/filedetails/?id=2314407956]
Rimefeller [https://steamcommunity.com/sharedfiles/filedetails/?id=1321849735]
Vanilla Books Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2193152410]
Vanilla Brewing Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2186560858]
[FSF] Complex Jobs [https://steamcommunity.com/sharedfiles/filedetails/?id=2069684319]
Vanilla Furniture Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=1718190143]
Vanilla Furniture Expanded - Farming [https://steamcommunity.com/sharedfiles/filedetails/?id=1957158779]
[FSF] No Default Shelf Storage [https://steamcommunity.com/sharedfiles/filedetails/?id=945085502]
Vanilla Traits Expanded [https://steamcommunity.com/sharedfiles/filedetails/?id=2296404655]
[KV] More Trait Slots [https://steamcommunity.com/sharedfiles/filedetails/?id=1508292711]
[SYR] Set Up Camp [https://steamcommunity.com/sharedfiles/filedetails/?id=1470065926]
RocketMan - Performance Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928]

**Description**
Before launching a colony, when clicking on the map or other equivalent option will send as many repeating errors as it can until the log limit is reached.  This happens almost every time I click on something else.  When I get to choosing colonists most if not all models will be missing their heads (other than that nothing else is different from normal).  Then if the game is started and the landing sequence plays where colonists are supposed to be deposited into the world through drop pods, it instead runs very slowly and every entity (animals, colonists, and drop pods) is frozen.  The colonists never land from the sky to the ground and all animals are frozen in place.

**Expected behavior**
I expected the game to just run as is always does, but no error messages other than from the main menu are logged once the colony starts.

**To reproduce**
Run the game with this mod set up.  Have dev mode enabled to see error log pop up.  Try to start a new colony, seeing as most colonist you can choose from are headless, and then start the game.

**Screenshots & log dumps**
Screenshots: 
![Screenshot (3)](https://user-images.githubusercontent.com/114265086/192066721-faaf9cf1-5c1a-4744-83fd-4af77275e157.png)
![Screenshot (4)](https://user-images.githubusercontent.com/114265086/192066732-84fe2033-08a8-4d04-9970-8a7ccda870f3.png)
![Screenshot (2)](https://user-images.githubusercontent.com/114265086/192066739-e94fe851-403f-4cbc-8a4a-2102b4c84d8d.png)

Log: (https://gist.github.com/67a7ba64304b871727d81d89b9ffed01) 

**Complete the following checklist**
I hereby verify that I have done the following:
- [Y] Confirmed that my game version and load order are correct.
- [Y] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [Y] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [N] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by perkinslr** [comment]
That looks to be in CE_DebugTooltipHelper.cs, but *not* in the base component update.  Try turning off the ShowExtraTooltips option in CE's settings and see if the problem goes away (it should).

**Comment by Chance713** [comment]
> That looks to be in CE_DebugTooltipHelper.cs, but _not_ in the base component update. Try turning off the ShowExtraTooltips option in CE's settings and see if the problem goes away (it should).
So there should be a "Combat Extended" section in mod settings? If so, then my game doesn't have it.

**Comment by perkinslr** [comment]
Note that the mod options pane kinda repeats.  The modds are alphabetical for mods that open their own settings pane,  followed by mods that just expand their options section.  CE should be in the former, listed as `Combat Extended`.  If it is not there, try verifying your game files, but I would be surprised it functions at all in that case.

**Comment by Chance713** [comment]
Thanks, that seemed to work.
