### ISSUE TITLE
[Bug]: missing dependencies

### ISSUE THREAD

**Issue by JaneQ14** [CombatExtended-Continued/CombatExtended#1894]
**Specifications**
Rimworld version: 1.3.3389 rev40
Combat Extended version: v4.8-Hotfix
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows 10
Your mod list: https://ibb.co/0QrBtXN

**Description**
missing invalid package.

**Expected behavior**
Game loads without errors

**To reproduce**
Start game with mods from my list. I didn't change anything in the settings

**Screenshots & log dumps**
https://ibb.co/chmMddC

**Complete the following checklist**
I hereby verify that I have done the following: YES
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by AluminumAlman** [comment]
> Your mod list: https://ibb.co/0QrBtXN

For anyone who's too lazy to check the image, it's Harmony, Core, Ideology, Royalty, (Fluffy's) Mod Manager, CE, CE Armors, CE Guns and CE Melee.

**Comment by N7Huntsman** [comment]
The only dependency that Combat Extended has is Harmony. I'd recommend a fresh install of CE, and see if the issue persists.

**Comment by ItsSamGray** [comment]
Classic (Fluffy's) Mod Manager issue...

**Comment by JaneQ14** [comment]
Yea, Thanks for your answer. It's Mod Manager issue, after removing this mod, no errors show up. Thanks!
