### ISSUE TITLE
[Discussion]: RW 1.1 to 1.2 Update

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#190]
This issue is to track changes between Rimworld 1.1 and 1.2, with particular concern for issues that affect Combat Extended. Please add items/issues to the list as you find them.

## Core

**Apparel_Utility.xml:**
- New Psychic Insanity Lance and Psychic Shock Lance apparel will need the standard treatment.
 
## Royalty

**Apparel_Packs.xml:**
- New Jump Pack and Broadshield pack (a deployable bubble shield) will need the standard treatment.

**Apparel_Various.xml:** 
- The new Phoenix and Grenadier armors include integrated weapons (an incendiary bolt launcher, and a grenade launcher, respectively) that will likely require some special attention in addition to normal patch work.
- Locust armor includes a jump pack, but shouldn't require special treatment.

**Comment by kbatbouta** [comment]
`CompReloadable` added for the new armor, Grenades projectiles changed and pawn render internal is broken and the menu maker need just to have the patched function retargeted.

**Comment by LockdownX7** [comment]
RW1.2-Update branch should now be C# compatible with the 1.2 release candidate. XML changes outlined above still need someone to go through them, and you'll also need to decide what ammo/projectiles the new reloadable armors should use (the ones I assigned to them were just for testing purposes, overwrite them as you like).

A note about reloadable armors: Right now you can only pick a single AmmoDef and projectile for the armor to shoot, not an entire CE AmmoSet, as the implementation of reloadable apparel is largely unchanged from vanilla. While porting features from CE's Comp_AmmoUser into CompReloadable is technically feasible, it would involve a fair bit of extra effort, so if anyone else has the time and inclination to tackle that, go for it.

**Comment by onigamii** [comment]
I feel that something like 40x46mm grenades or similar would work fine for the armors.

**Comment by N7Huntsman** [comment]
Mission Accomplished.
