### ISSUE TITLE
[Discussion]: Update Combat Extended for Rimworld 1.4 + Biotech DLC

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#1906]
A general tracking sheet for fixes, changes, new content, and other things to be worked on or looked into for the upcoming Rimworld content. Add anything else for the list in comments.

The public 1.4 changelog can be found here: https://bit.ly/3egvrGz

# Rimworld 1.4
**New Turrets:**
  - [ ] Fire foam - sprays fires with firefoam once activated by a colonist.
  - [ ] Rocket swarm - when triggered, blankets a wide area with missiles.

**New gas system and health conditions:**
  - [ ] Evaluate interactions with CE black smoke system.

**Other New Content:**
  - [x] Patch new firefoam popper belt.
  - [ ] New “tend (without medicine)” option added to drafted pawns. Ensure this doesn't interfere with the stabilize option on the right-click menu.

**UI:**
  - [ ] Options menu was overhauled. Confirm CE mod options formatted and working as intended.

**Misc.:**
 - [ ] "Starting colonists can begin with certain possessions." 
   - Colonists can spawn with ranged weapons. However, they are limited to a max of two possessions which includes any drugs they are addicted to. If they spawn with a ranged gun and a drug, ammo patched into their backgrounddef will not spawn.
   - These items are dropped on the ground as a starting item, so adding ammo to the colony pawnkind doesn't work.
   - It _might_ to be possible for possessions like weapons to appear randomly on backstories--this means it may not be possible to just xml patch the ammo in for all cases.
 - [ ] "Colonists can be ordered to re-arm turrets while drafted." Ensure this doesn't interfere with any CE turret behavior.
 - [ ] "Moved ranged weapon, melee weapon, armor, clothing and art stock gen to a tagged based system and adjusted market value selection weight for all items." Ensure this doesn't interfere with pawnkind inventory generation for non-colony pawns.

**Technical:**
 - [ ] "Replaced `CrownType` with `headTypeDef`."
 - [ ] "Allow defs to specify `Action<>, Func<>, etc.` as a data type for members."
 - [ ] "Allow open-ended ranges for `IntRange in defs, eg: "~10" to represent values <= 10 and "10~" to represent values >= 10`."
 - [ ] "Merged LanguageWorker.PostProcesssedKeyedTranslation() and LanguageWorker.PostProcessed()." Ensure this doesn't cause issues with any CE translations.
 - [ ] "Made Projectile.DamageAmount and Projectile.ArmorPenetration virtual for better modder support." Any likely use/impact for CE?
 - [ ] "vanilla shield belts were changed from an Apparel subclass to a Comp".

- **Bug Fixes:**
  - [x] "Fix: Stranger in black can have 0 shooting skill." Evaluate removing CE's skill patch on Stranger in Black.
  - [ ] "Fix: Explosive projectiles disappear when impacting a shield. They now detonate when impacting." Any impact on CE?

# Biotech
- **Babies**
 - [ ] New apparel.

- **Colony Mechanoids**
  - [ ] New laborer and combat mech types.
  - [ ] New mechanoid weapons.

**- Pollution and Gas System**
  - [ ] Patch new vanilla gas mask added.

**- Gene Modding**
  - [ ] Pawn breathe weapons.

**Comment by SamaelGray** [comment]
Some discoveries:
https://discord.com/channels/278818534069501953/322827713335394304/1027993627751874681
https://discord.com/channels/278818534069501953/322827713335394304/1027994504181063821

**Comment by SamaelGray** [comment]
About the Stranger in Black's shooting skill range, it is still very overtuned in the base game, out patch is much more realistic and conservative.
Tho I have mentioned my opinions on the non-Royalty pawns that have a preset skill range to ison again, he said that they will consider the suggestions, we will see what comes out of it.

**Comment by T-rexsuper1** [comment]
Gas masks are not vanilla. Gas masks are biotech only. Devs said it's okay to keep gas masks in mods that already had them.

**Comment by Loweg** [comment]
> New “tend (without medicine)” option added to drafted pawns. Ensure this doesn't interfere with the stabilize option on the right-click menu.

Both vanilla tending and stabilizing appear to be working as intended.

> Options menu was overhauled. Confirm CE mod options formatted and working as intended.

The CE mod options menu is working as intended and is identical in appearance to previous versions.

> "Colonists can be ordered to re-arm turrets while drafted." Ensure this doesn't interfere with any CE turret behavior.

I'm not very familiar with vanilla turret behavior, but the tests I performed worked identically in 1.3 and 1.4.

> "Fix: Explosive projectiles disappear when impacting a shield. They now detonate when impacting." Any impact on CE?

Both CE and vanilla explosive weapons are working perfectly.

**Comment by N7Huntsman** [comment]
Closing this issue since we've got the bulk of the update complete and are down to more specific items.
