### ISSUE TITLE
[Discussion]: Gun quality and jamming for repeating weapons

### ISSUE THREAD

**Issue by CMDR-Bill-Doors** [CombatExtended-Continued/CombatExtended#1929]
I always wanted gun quality to actually matter, and what gun quality should affect? reliability, whether the gun jams easily etc.

My proposal for a jamming mechanism is: each time a shot is fired, there's a chance to immediately stop current burst. This chance is direct related to gun quality (and hitpoint, if someone wants it), say, 10% for awful, 5% for poor, 1% for normal. And this jamming mechanism should only apply to weapons of industrial or below (because, spacer magic), or if a modExtension is specified (see below)

And for special cases (say, minigun, L85, or some very unreliable spacer gun if someone intend to balance it with jamming), a modExtension may be added, to disable or enable jamming for this gun, or to set jamming chance multiplier

theoratically this should make players want to get rid of poor guns or damaged guns asap.

Pros:  should be NPC AI friendly since it don't involve any jobs.

Cons: still needs patching for special cases, doesn't make good guns better, doesn't have effect on non-repeating weapons.

**Comment by N7Huntsman** [comment]
Weapon jamming and reliability is not something core CE is going to see--at least, certainly not within any short or medium timeframe.

The chief issue is that it's an intense level of micro. Morever, it's something the player doesn't have the proper utilities to deal with. For instance, there's no way for the player to dictate weapon/item quality in loadouts--the pawn just grabs a weapon/item of that type, regardless of all else.
