### ISSUE TITLE
Add 90mm recoilless rifle cartridge (HEAT and Canister) to the ammodef for M67 recoilless rifle

### ISSUE THREAD

**Issue by DeadCarl** [CombatExtended-Continued/CombatExtended#1975]
I've been thinking about making a Vietnam weapons mod and it includes the M67 recoilless rifle. However in the current CE ammunition database the 90mm recoilless rifle rounds are not actually included.
I've made a special canister shot that reflects the real-life counterpart used in Vietnam. Should we add this kind of ammunition to the mod?

**Comment by albertbokor** [comment]
added
