### ISSUE TITLE
New tox gun ammo bug

### ISSUE THREAD

**Issue by PlaYerBr001** [CombatExtended-Continued/CombatExtended#1982]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.
The new toxic guns have its wrong ammo and its shooting a 7.51 ammo type
Rimworld version: 1.4
Combat Extended version:
Combat Extended source (Steam, GitHub, etc.): 
Your operating system: windowns 7
Your mod list:

**Description**
Provide a concise description of the issue or concern. What happened?
New tox weapon shooting wrong ammo type(shooting 7.51 instead of gas ammo)

**Expected behavior**
What did you expect to happen?
To the new weapon have the toxic gas ammo

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Spawn a tox launcher with ammo actived, and try to shoot it, it will shoot a 7.51 ammo type

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [ ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by PlaYerBr001** [comment]
1.

**Comment by SamaelGray** [comment]
The tox weapons are currently unpatched resulting in them being autopatched.

**Comment by SamaelGray** [comment]
The tox weapons are currently unpatched resulting in them being autopatched.
