### ISSUE TITLE
[Bug]: Mechs killed by prometheum fire re-ignite on resurrection

### ISSUE THREAD

**Issue by trikanyo** [CombatExtended-Continued/CombatExtended#2000]
**Specifications**
Please provide the following.

Rimworld version: 1.4.3534
Combat Extended version: Dev Snapshot
Combat Extended source (Steam, GitHub, etc.): Github (downloaded dev snapshot 2022-10-31)
Your operating system: Windows 10
Your mod list: https://rentry.co/yr7to

**Description**
When killing mechs using weapons that prometheum soak the soak hediff remains on death. When resurrected via apocriton it remains, they spontaneously reignite and then die again.

**Expected behavior**
For them to not reignite on resurrection.

**To reproduce**
1. Shoot a mech with a flamethrower and jellied prometheum
2. Bait apocriton into resurrecting it.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by albertbokor** [comment]
~~leave it for the funni~~

**Comment by SamaelGray** [comment]
Fixed in https://github.com/CombatExtended-Continued/CombatExtended/pull/2048
