### ISSUE TITLE
[Discussion]: Rimworld 1.4 + Biotech Known Issues/To-Do

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#2012]
## Known Issues:
- ~~WorldGen errors associated with Humanoid Alien Races patch.~~
- ~~Player (not in dev mode) can see the magazine gizmo for non-colony humanoids.~~
- ~~The magazine gizmo doesn't show on colony-mechs.~~
- ~~When resurrected, mechanoids will keep the Prometheum-Soaked hediff, causing them to immediately burst into flames when they resurrect.~~
- ~~`forcedAmmoCategory` for pawnkind ammo loadouts does not ignore `generateAllowChance`. It is desirable for it to do so to allow the forced spawning of faction-specific ammo types like 40mm Toxic grenades.~~
- ~~When using `forcedAmmoCategory`, pawnkinds may sometimes spawn with a weapon that doesn't use the required ammo type at all, throwing an error and failing to generate the pawn. In this case, it's preferable to ignore the required ammo category and spawn normally (a dev mod log message noting when this happens may be useful for troubleshooting in some cases but isn't needed). https://pastebin.com/DHAGKNeD~~
- ~~Biotech gas mask renders over hats, even without VEF.~~
- ~~Headgear layer rendering broken with VEF. Facial hair/weapon layers appear incorrect. Related to Vanilla Expanded Framework.~~
- ~~Error when selecting non-colony mechinator pawns that have a ranged weapon equipped. https://pastebin.com/3xTf9YUF~~

## To-Do:
- ~~Support for Biotech abilities. Specifically, the vampire spine projectile armor penetration.~~
-  (Lower priority) Better support for giving ammo to weapons that spawn as "possessions". Current xpath implementation is fragile.
- ~~Support for new Firefoam and Rocket turrets.~~
- ~~Add generic ammo settings to mech ammo.~~

**Comment by race19991** [comment]
Suggest giving the Tunneler Higher  Blunt Armor Penetration. It can crush uranim, should be able to at least crack a mechaoid armor.

**Comment by Safairette** [comment]
Would also add a potential loadout/automatic ammo pickup for colony mechs to the list of things to add
Was probably the most requested feature from the beta feedback

**Comment by N7Huntsman** [comment]
> Would also add a potential loadout/automatic ammo pickup for colony mechs to the list of things to add Was probably the most requested feature from the beta feedback

No doubt, but it has in the past been something we've been unsuccessful in implementing. Perhaps we can make another pass once the initial Biotech/1.4 support is out--maybe Biotech has implemented the player makes in a way that makes it more feasible.
