### ISSUE TITLE
[Discussion]:Virus total 1 detected result

### ISSUE THREAD

**Issue by cofecofe3** [CombatExtended-Continued/CombatExtended#2031]
Hi, downloaded latest snapshot build, what could be wrong if MalwareBytes detected Malware.Heuristic.1008? As I know, is well-trusted antivirus software, so, thats looks strange
https://www.virustotal.com/gui/file/2fd0059fdb257d23d6ca42cd49506ec306556e9acb869bbc4a6683648a58a4e2

**Comment by albertbokor** [comment]
I assume it's a missing cert issue, everything is clear and traceable out on the github, no reason or way really to put in intentionally malicious code

**Comment by cofecofe3** [comment]
Oh, alright, thanks for respond!
