### ISSUE TITLE
[Discussion]: Ballisticweave

### ISSUE THREAD

**Issue by SamaelGray** [CombatExtended-Continued/CombatExtended#2045]
Proposal to add Ballisticweave to CE instead of using Devilstrand in all the armor recipes, a Kevlar-looking fabric.
It'd have the same armor values as Devilstrand but will have 3 recipes to convert other armored fabrics into it in (input:output) ratios of 2:1, 1:1 and 1:2 for materials less armored than Devilstrand, same-ish as Devilstrand and more armored than Devilstrand so that the issue of having a ton of Hyperweave and not being able to make power armor gets alleviated as well.
The recipes would accept a mix of items (only fabrics, no leathers with the exception of things like Thrumbofur) like how Patchleather in vanilla does and would be done in the tailoring bench. 
Apart from vanilla items that will be added to the recipe from the get go, modded items will be patched into the recipe in their own mod's patch files.
We could also introduce a bulk recipe to craft Ballisticweave too for QoL purposes.

**Comment by DeadCarl** [comment]
Good idea. Flak armor is divided into plate carrier, which only require metals and is lighter, but can only protect vital organs, and full body armor, which requires ballisticweave and metal, way heavier but protects your whole body. Ballistic weave is made from cotton or leather combined with chemfuel and neutromine, or made from devilstrand and chemfuel

**Comment by SamaelGray** [comment]
Vetoed.
