### ISSUE TITLE
[Bug]: All non-hostile pawns spawn in with gas masks

### ISSUE THREAD

**Issue by SomeGuy6858** [CombatExtended-Continued/CombatExtended#2062]
Rimworld version: 1.4
Combat Extended version: 1.4.5.0
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows
Your mod list: All Vanilla Expanded + EPOE Forked + SRTS [1.4] + Harmony + Wall Light + Rocketman + Achtung + Alpha Animals + Pick Up And Haul + Elite Bionics Framework

**Description**
Every Pawn that is spawned in from a non raid related event is wearing a gas mask, including starting pawns.

**Expected behavior**
I'm not sure if this was intended so non-hostile pawns don't get sick from pollution, so I figured I would post.

**To reproduce**
Any quest that sends pawns to your map, starting colonist selection should show it as well.

**Screenshots & log dumps**
https://imgur.com/a/bDfKpyI
(Two pawns spawned by a "hold this prisoner" type of quest)

**Complete the following checklist**
I hereby verify that I have done the following:
- [Yes] Confirmed that my game version and load order are correct.
- [Yes]Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [Yes] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [Yes] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Already resolved in the dev snapshot.
