### ISSUE TITLE
[Bug]: Gives compatibility and corruption errors right after install

### ISSUE THREAD

**Issue by goreal818** [CombatExtended-Continued/CombatExtended#2093]
**Specifications**
I7-4720hq
GTX 970m
16gb ram

Rimworld version:1.43541
Combat Extended version: 1.4.5
Github
Windows 10
Your mod list:
Hugslib, harmony, Combat extended

When I try to enable CE I get the errors; "Error in ParallelFor(): System.IO.DirectoryNotFoundException: Could not find a part of the path" as well as multiple "Failed to find Rimworld.statdef named" such as "Failed to find RimWorld.StatDef named MuzzleFlash. There are 211 defs of this type loaded." It then says successfully recovered from errors and loaded play data but CE doesn't work and disables the mods.
I also get an error for hugslib but both harmony and hugslib run without issue when CE isn't enabled

I expect the mod to load properly without disabling everything

I do not know how to reproduce

![CEbug2](https://user-images.githubusercontent.com/57872578/203190086-7c5d8029-309e-4388-868e-094f88747bb3.PNG)
![CEbug3](https://user-images.githubusercontent.com/57872578/203190088-06eecc5f-439e-4b0e-9dfe-759dfc5f47fc.PNG)
![CEbug](https://user-images.githubusercontent.com/57872578/203190089-15b5bed3-094d-4156-a762-c6a18f65d3d6.PNG)

**Comment by lKameRUNl** [comment]
It's not a CE bug, update your DLCs. You get this because rimworld got updated, and your DLCs are not. Tested yesterday, got same errors, updated DLCs, all gone.
