### ISSUE TITLE
[Patch Request]: Patch is obsolete and can be safely deleted for [Fuu] Uncompromising Tribal Faction

### ISSUE THREAD

**Issue by tenguin** [CombatExtended-Continued/CombatExtended#2106]
**Mod name:**
 [Fuu] Uncompromising Tribal Faction

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2571594852

**Description:**
The patch is no longer needed since I have redesigned the mod to be compatible with CE on my side.

The current patch that exists in the "Patches/Uncompromising Tribal Faction" folder is obsolete and will throw errors on launch, That entire folder can be safely deleted now.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
Hi Tenguin,

Thanks for reaching out and thank you for the update from your end. I've gone ahead and opened up a PR removing the patch (#2108 ), but looking through the Uncompromising Tribal Factions mod files, I'm admittedly not certain the patch is entirely unneeded if the custom flame greatbow is intended to use ammo, as I'm not seeing anything in the mod itself that patches the weapon for CE. Plus, the new pawnkinds will need patched to specifically spawn with fire arrows.

**Comment by tenguin** [comment]
Oh, I have the CE compatibility file ready on my local machine, just not uploaded on Steam/Github yet.

Since it's rather simple, copying from what you did with the Impids, I thought it'd be easier to keep it maintained on my end since you're already swamped with compatibility requests ;p

Here's my intended compatibility patch if you're curious: https://pastebin.com/EfMPmn1A
