### ISSUE TITLE
[Bug]: XML error: Duplicate XML node name combatPower (Militor)

### ISSUE THREAD

**Issue by xuvvy** [CombatExtended-Continued/CombatExtended#2141]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:  1.4.3563
Combat Extended version: 1.4.5.0
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 11
Your mod list: Harmony, Core, Royalty, Ideology, Biotech, Vanilla Backgrounds Expanded, HugsLib, Combat Extended

**Description**
The error appears at game startup.

**Expected behavior**
There should not be an error.

**To reproduce**
Launch the latest version of the game with the latest version of CE.

**Screenshots & log dumps**
https://pastebin.com/RRGmCdrU

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Already fixed in the dev build.
