### ISSUE TITLE
[Bug]: EXTREMELY annoying unequipping bug

### ISSUE THREAD

**Issue by NukeMND** [CombatExtended-Continued/CombatExtended#2143]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: Person unequips normal fire weapons,  CONSTANTLY unequips any fire weapons i give, ammo is disabled

**Specifications**
Please provide the following.

Rimworld version: 1.4.3525
Combat Extended version: 5
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows 11
Your mod list: Rocketman, Hospitality, Rimatomics and Rimfeller, Gastronomy. +Biotech, Ideology, Royalty

**Description**
Provide a concise description of the issue or concern. What happened?

**Expected behavior**
What did you expect to happen?

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [ ] Confirmed that my game version and load order are correct.
- [ ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
You are not really meant to be playing with the ammo system disabled, it's there for testing purposes.
Please consider using the Generic Ammo system instead of disabling ammo altogether as it is intended for people that don't wan to manage a lot of ammo types, Ce is not meant to be played with no ammo.

**Comment by SamaelGray** [comment]
Fixed in #2433
