### ISSUE TITLE
[Bug]: Diabolus seems to be immortal

### ISSUE THREAD

**Issue by Kypsis** [CombatExtended-Continued/CombatExtended#2144]
Rimworld version: 1.4.3563
Combat Extended version: 5.0
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: macOs Ventura
Your mod list: CombatExtended, Rah's Vanilla Turrets Expansion

**Description**
Trying to kill Diabolus as with Mechanitor background and using a killbox with 4 turrets, Diabolus gets down to 20ish % hp then shoots back up to 50 - 70% and then can get down to 30% again until he takes no damage anymore. 

**Expected behavior**
Being able to kill Diabolus.

**To reproduce**
Try to kill Diabolus with turrets.

**Screenshots & log dumps**
-
Speculation: the damage seems to be applied in batches per some unit of time (vs per projectile)? Is the leftover damage after it should kill Diabolus added back as health? 

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
This happens because lost body parts don't contribute towards the total HP of a pawn hence the occasional jump in the total HP you see.

**Comment by Kypsis** [comment]
Wait a minute, do I understand correctly that if for whatever reason I'm attacking an already destroyed body part I am in effect not dealing any damage any more?
