### ISSUE TITLE
[Bug]: XML error: Duplicate XML node name combatPower in this XML block

### ISSUE THREAD

**Issue by sondanielshah** [CombatExtended-Continued/CombatExtended#2156]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.4.3569 (64 bit)
Combat Extended version: 1.4.5.0
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Win11 64
Your mod list: Harmony, Hugslib, CE (thats it)

**Description**
Provide a concise description of the issue or concern. What happened?

XML error: Duplicate XML node name combatPower in this XML block: <PawnKindDef ParentName="LightMechanoidKind"><defName>Mech_Militor</defName><label>militor</label><race>Mech_Militor</race><combatPower>45</combatPower><lifeStages><li><bodyGraphicData><texPath>Things/Pawn/Mechanoid/Militor</texPath><maskPath>Things/Pawn/Mechanoid/AllegianceOverlays/Mech_Slugger</maskPath><shaderType>CutoutWithOverlay</shaderType><graphicClass>Graphic_Multi</graphicClass><drawSize>1.25</drawSize><shadowData><volume>(0.3, 0.4, 0.3)</volume><offset>(0,0,-0.25)</offset></shadowData></bodyGraphicData></li><li><bodyGraphicData><texPath>Things/Pawn/Mechanoid/MilitorAncient</texPath><maskPath>Things/Pawn/Mechanoid/AllegianceOverlays/Mech_Slugger</maskPath><shaderType>CutoutWithOverlay</shaderType><graphicClass>Graphic_Multi</graphicClass><drawSize>1.25</drawSize><shadowData><volume>(0.3, 0.4, 0.3)</volume><offset>(0,0,-0.25)</offset></shadowData></bodyGraphicData></li></lifeStages><weaponTags><li>MechanoidGunShortRange</li></weaponTags><combatPower>90</combatPower><modExtensions><li Class="CombatExtended.LoadoutPropertiesExtension"><primaryMagazineCount><min>5</min><max>6</max></primaryMagazineCount></li></modExtensions></PawnKindDef>
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.XmlInheritance:CheckForDuplicateNodes (System.Xml.XmlNode,System.Xml.XmlNode)
Verse.XmlInheritance:ResolveXmlNodeFor (Verse.XmlInheritance/XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodesRecursively (Verse.XmlInheritance/XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodesRecursively (Verse.XmlInheritance/XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodesRecursively (Verse.XmlInheritance/XmlInheritanceNode)
Verse.XmlInheritance:ResolveXmlNodes ()
Verse.XmlInheritance:Resolve ()
Verse.LoadedModManager:ParseAndProcessXML (System.Xml.XmlDocument,System.Collections.Generic.Dictionary`2<System.Xml.XmlNode, Verse.LoadableXmlAsset>)
Verse.LoadedModManager:LoadAllActiveMods ()
Verse.PlayDataLoader:DoPlayLoad ()
Verse.PlayDataLoader:LoadAllPlayData (bool)
Verse.Root/<>c:<Start>b__6_1 ()
Verse.LongEventHandler:RunEventFromAnotherThread (System.Action)
Verse.LongEventHandler/<>c:<UpdateCurrentAsynchronousEvent>b__27_0 ()
System.Threading.ThreadHelper:ThreadStart_Context (object)
System.Threading.ExecutionContext:RunInternal (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object,bool)
System.Threading.ExecutionContext:Run (System.Threading.ExecutionContext,System.Threading.ContextCallback,object)
System.Threading.ThreadHelper:ThreadStart ()

**Expected behavior**
I keep getting this Red line issue at startup when using CE. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [ Y] Confirmed that my game version and load order are correct. 
- [ Y] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ Y] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ Y] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Already fixed in the dev build.
