### ISSUE TITLE
[Bug]: HeavyAmmo has both CE_HeavyAmmo and CE_Ammo trade tags.

### ISSUE THREAD

**Issue by JanWitczak** [CombatExtended-Continued/CombatExtended#2162]
**Specifications**

Rimworld version: 1.4
Combat Extended version: 5.0
Combat Extended source (Steam, GitHub, etc.): Steam

**Description**
Due to wrong capitalization of inherit attribute, HeavyAmmoBase inherits CE_Ammo trade tag from AmmoBase.

**Expected behavior**
HeavyAmmoBase should only have CE_HeavyAmmo trade tag.

**To reproduce**
Write a utility that prints out trade tags of a chosen heavy ammo type,
or spawn a combat caravan, it might spawn with a number of shells unachievable by the stock generator for trade tag CE_HeavyAmmo.

**Screenshots & log dumps**
Printout of trade tags for 81mm HE shell with mod as is.
![inherit](https://user-images.githubusercontent.com/56643578/206577750-5834f3df-67e2-43b7-b5d0-5fdfec96cf63.png)
Printout of trade tags for 81mm HE shell with capitalized Inherit="False" attribute in HeavyAmmoBase def.
![Capitalised Inherit](https://user-images.githubusercontent.com/56643578/206577764-a344d061-02d6-45b2-9219-0350e85c9c1b.png)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Thanks for finding the issue with the Heavy Ammo's trading tag.

**Comment by JanWitczak** [comment]
No problem. As a heads up, fixing this causes trade stocks to not generate heavy ammo at all, and I could not find the reason for that behavior.
