### ISSUE TITLE
[Bug]: Animals with native ranged attack can't have the CombatExtended.Verb_ShootCE verbClass

### ISSUE THREAD

**Issue by Juanfrank** [CombatExtended-Continued/CombatExtended#22]
Rimworld version: Latest
Combat Extended version: Latest, including the https://github.com/CombatExtended-Continued/CombatExtended/tree/bugfix/sights-without-equipment branch
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows 10
Your mod list: https://pastebin.com/iCWNh97k (RimPy won't open for me)

**Description**
First off, I'm not sure if this goes into the Patch or the Bug category, so please bear with me if I labelled it wrongly.

After applying the CombatExtended.Verb_ShootCE to several animal pawns added by the Alpha Animals mod (currently being developed by Breadbox2k19 and myself), upon doing the "aiming" animation, the creature doesn't launch anything and several red errors show up in the dev log.

This seems to suggest, by trial and error, and as discussed in the Discord:
- That the CombatExtended.Shoot_CE seems to look for Gun specific attributes in the statBases node, such as the SightEfficiency and others, which of course do not apply to pawns that shoot things by themselves.  https://pastebin.com/BPDVLHYm
- Upon changing the .dll as provided by Madara Uchiha, brother of Izuna, the error switches over to the Sway value. https://pastebin.com/J9pEpmEB
- Again, the latest update seems to look for 'something else' which I'm not quite sure since I don't know anything about C#. https://pastebin.com/7BHgawyF

**Expected behavior**
- Projectiles launched as defined by the CombatExtended.ToolCE in the tools attributes for the race defined by the XML.
- Without the CombatExtended.VerbShoot_CE (using the standard VerbShoot verbClass) the attacks do come out and damage as expected, however using vanilla calculations for hit chance DnD style.

**To reproduce**
 1. Define any gunless ranged attack of a pawn, with the tools and verbs nodes.
 2. Make it shoot at something.
 3. Watch in awe as the warmup graphics show up, and then nothing comes out.
 4. Watch your dev log stop recording due to spam.

**Screenshots & log dumps**
  - Posting latest: https://pastebin.com/7BHgawyF

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.

The following do not apply to the current reported "bug" (which isn't a bug per se, more like a compatibility development)
- [-] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [-] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
I believe this is addressed by #21

**Comment by Juanfrank** [comment]
This test includes post- https://github.com/CombatExtended-Continued/CombatExtended/pull/21

**Comment by Juanfrank** [comment]
As requested, used the mod again with the corresponding #21 branch.

`Exception ticking AA_Dunealisk773526 (at (103, 0, 129)): System.InvalidCastException: Specified cast is not valid.
  at CombatExtended.Verb_LaunchProjectileCE.TryCastShot () [0x0006a] in <a51f50d11b784d89bb2c6c31070466d0>:0 
  at CombatExtended.Verb_ShootCE.TryCastShot () [0x00022] in <a51f50d11b784d89bb2c6c31070466d0>:0 
  at (wrapper dynamic-method) Verse.Verb.DMD<DMD<TryCastNextBurstShot_Patch0>?-836307840::TryCastNextBurstShot_Patch0>(Verse.Verb)
  at Verse.Verb.WarmupComplete () [0x00013] in <36108d57f84d49cabdae818c2a53fc38>:0 
  at CombatExtended.Verb_LaunchProjectileCE.WarmupComplete () [0x0006e] in <a51f50d11b784d89bb2c6c31070466d0>:0 
  at CombatExtended.Verb_ShootCE.WarmupComplete () [0x0009e] in <a51f50d11b784d89bb2c6c31070466d0>:0 
  at Verse.Stance_Warmup.Expire () [0x00000] in <36108d57f84d49cabdae818c2a53fc38>:0 
  at Verse.Stance_Busy.StanceTick () [0x00017] in <36108d57f84d49cabdae818c2a53fc38>:0 
  at (wrapper dynamic-method) Verse.Stance_Warmup.DMD<DMD<StanceTick_Patch1>?2022899712::StanceTick_Patch1>(Verse.Stance_Warmup)
  at Verse.Pawn_StanceTracker.StanceTrackerTick () [0x00018] in <36108d57f84d49cabdae818c2a53fc38>:0 
  at (wrapper dynamic-method) Verse.Pawn.DMD<DMD<Tick_Patch1>?-516541696::Tick_Patch1>(Verse.Pawn)
  at Verse.TickList.Tick () [0x0015c] in <36108d57f84d49cabdae818c2a53fc38>:0 
Verse.Log:Error(String, Boolean)
Verse.TickList:Tick()
Verse.TickManager:DoSingleTick()
Verse.TickManager:TickManagerUpdate()
Verse.Game:UpdatePlay()
Verse.Root_Play:Update()`

**Comment by N7Huntsman** [comment]
The fix by #21 partially resolves the issue by assigning default values to creatures' equipment. So while functional, it remains to be determined if these are "good" default values, and it may be preferable to find a way to be able to assign these stats to pawns and be able to read them from there.

**Comment by N7Huntsman** [comment]
Resolved with #21
