### ISSUE TITLE
[Bug]: Various xml patches errors

### ISSUE THREAD

**Issue by Taranchuk** [CombatExtended-Continued/CombatExtended#2258]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: latest
Combat Extended version: latest from steam
Combat Extended source (Steam, GitHub, etc.): steam
Your operating system: windows
Your mod list: https://rentry.co/ypupq

**Description**
Provide a concise description of the issue or concern. What happened?
Received bunch of xml errors

**Expected behavior**
No xml errors ideally
**To reproduce**
Launch the game

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
https://gist.github.com/HugsLibRecordKeeper/09cbf27edc6bbdb8694fba51c3e2a19a

Here are the xml errors:
[Combat Extended - Start of stack trace]
Verse.PatchOperationReplace(xpath="Defs/VFECore.Abilities.AbilityDef[defName="AAVPE_VenomSpit"]/range"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Vanilla Psycasts Expanded): Error in <match>
Verse.PatchOperationFindMod(Alpha Animals): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Alpha Animals\AA_VPE\AbilityDefs\AbilityDefs_Patch.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Combat Extended - Start of stack trace]
Verse.PatchOperationReplace(xpath="Defs/HediffDef[defName="AAVPE_StrengthenBlackHive"]/stages/li/statOffsets/ArmorRating_Blunt"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Vanilla Psycasts Expanded): Error in <match>
Verse.PatchOperationFindMod(Alpha Animals): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Alpha Animals\AA_VPE\HediffDefs\Hediffs_Patch.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Combat Extended - Start of stack trace]
Verse.PatchOperationAddModExtension(xpath="/Defs/ThingDef[defName="AA_BlackScarab_Temporary"]"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Vanilla Psycasts Expanded): Error in <match>
Verse.PatchOperationFindMod(Alpha Animals): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Alpha Animals\AA_VPE\ThingDefs_Races\Races_BlackHive_Psycasts.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Combat Extended - Start of stack trace]
Verse.PatchOperationAdd(xpath="/Defs/ThingDef[defName="AA_BlackLarvae"]/statBases"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Vanilla Psycasts Expanded): Error in <match>
Verse.PatchOperationFindMod(Alpha Animals): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Alpha Animals\AA_VPE\ThingDefs_Races\Races_BlackLarva.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Combat Extended - Start of stack trace]
Verse.PatchOperationAdd(xpath="/Defs/ThingDef[defName="AAVPE_BlackQueen"]/statBases"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Vanilla Psycasts Expanded): Error in <match>
Verse.PatchOperationFindMod(Alpha Animals): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Alpha Animals\AA_VPE\ThingDefs_Races\Races_BlackQueen.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Combat Extended - Start of stack trace]
Verse.PatchOperationAddModExtension(xpath="/Defs/ThingDef[defName="AA_OcularOriginator"]"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Vanilla Psycasts Expanded): Error in <match>
Verse.PatchOperationFindMod(Alpha Animals): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Alpha Animals\AA_VPE\ThingDefs_Races\Races_OcularOriginator.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Combat Extended - Start of stack trace]
Verse.PatchOperationAddModExtension(xpath="/Defs/ThingDef[defName="AA_Summoned_Eyeling"]"): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Ideology): Error in <match>
Verse.PatchOperationFindMod(Vanilla Psycasts Expanded): Error in <match>
Verse.PatchOperationFindMod(Alpha Animals): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Alpha Animals\AA_VPE\ThingDefs_Races\Races_Summoned_Eyeling.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

[Combat Extended - Start of stack trace]
Verse.PatchOperationReplace(xpath="Defs/ThingDef[defName = "VFEP_WarcasketGun_SalvagedLaserEradicator" or defName = "VFEP_WarcasketGun_LaserBlaster"]/tools
          "): Failed to find a node with the given xpath
Verse.PatchOperationSequence: Error in the operation at position=1
Verse.PatchOperationFindMod(Vanilla Weapons Expanded - Laser): Error in <match>
Verse.PatchOperationFindMod(Vanilla Factions Expanded - Pirates): Error in <match>
[End of stack trace]
The top operation is the one that failed, the ones below it are the parents
Source file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\2890901044\Patches\Vanilla Factions Expanded - Pirates\ThingDefs_Misc\Addon Weapons\VWELRangedWarcasket.xml
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Make sure you have a clean installation of CE, I have all the mods listed here and am not getting red errors at launch.

**Comment by Taranchuk** [comment]
I do have the new steam version and I can get the red errors. Still can reproduce them in a minimal mod order

**Comment by Taranchuk** [comment]
![image](https://user-images.githubusercontent.com/24846741/210207168-c092bdaa-fb0e-48ad-b204-50b94df7b5a5.png)
These are the mods that I have installed, I do wonder what versions you have though

**Comment by SamaelGray** [comment]
All my mods are updated too, try completely deleting CE's folder and resub to it, steam can mess updates up.

**Comment by Taranchuk** [comment]
I just did. The same thing.

**Comment by SamaelGray** [comment]
Have you tried the same folder deleting method for VPE and AA?

**Comment by SamaelGray** [comment]
No errors here.
![image](https://user-images.githubusercontent.com/56392968/210207945-007368e0-ae2f-45de-acb8-9d0722e0d057.png)
![image](https://user-images.githubusercontent.com/56392968/210207952-23a671e9-213a-41e2-8392-7990b62df530.png)

**Comment by Taranchuk** [comment]
I just uninstalled all steam mods and redownloaded and I still have the errors. Also in your screenshot all mods are local, while I was reporting about steam versions.

**Comment by SamaelGray** [comment]
Uninstall as in deleting the whole folders and resubbing to them?
My mods are all local but up to date to the steam versions, there is no difference between them.

**Comment by sumghai** [comment]
@SamaelGray As a vote of confidence, CE v1.4.5.1 loads for me without errors.
