### ISSUE TITLE
There is a compatibility problem.

### ISSUE THREAD

**Issue by SitriCC** [CombatExtended-Continued/CombatExtended#2262]
I don't know why. The compatibility of EMSM_AutoBoltRifle fails, but the above Gun_AABolter is successful. Is it a writing error? If so, how should I write it?

I just started learning to program and have not touched XML before.

This is the patch.
[Bolt.txt](https://github.com/CombatExtended-Continued/CombatExtended/files/10333415/Bolt.txt)

This is the source file.
[EMIM_BoltWeapon.txt](https://github.com/CombatExtended-Continued/CombatExtended/files/10333418/EMIM_BoltWeapon.txt)

Cannot upload XML, I had to change to TXT, sorry.

**Comment by N7Huntsman** [comment]
I'm not sure what mod the `Gun_AABolter` comes from, but it's not in that included EMIM file. That's not necessarily a problem, but you should be aware of that.

As for the second patch, the issue you're running into is that the `EMSM_AutoBoltRifle` Def doesn't actually contain all of the elements that the `CombatExtended.PatchOperationMakeWeaponCECompatible` operation is looking for--all the `verbProperties` and stuff.

That's contained within `Name="EMSM_AutoBoltRifleBase"`. Unfortunately, can't use a `Name`, it needs to be pointed at a `defName`. However, all that CE patch operation really is is a bunch of Add and Replace patch operations that add and replace the vanilla stuff with the stuff CE needs. So, you'll just need to use those operations instead.
