### ISSUE TITLE
[Bug]:Sidearms are not biocoded

### ISSUE THREAD

**Issue by CMDR-Bill-Doors** [CombatExtended-Continued/CombatExtended#2269]
[Bug]: Sidearms are not biocoded on pawns that biocodes weapons.

Rimworld version: 1.4
Combat Extended version:1.4.5.1
Combat Extended source (Steam, GitHub, etc.):steam
Your operating system:win 10
Your mod list:CE

**Description**
Sidearms are not affected by a pawnkind's biocode-ness.

**Expected behavior**
Sidearms that can be biocoded, either determined by the pawnkind itself or a seperate bool in the mod extension.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Repost from discord: It should adhere to the pawn's biocoding rule imo and automatically make the sidearm biocoded if the pawn's gear are biocoded
