### ISSUE TITLE
[Patch Request]: Science Never Stops: Ambition of the Cosmic

### ISSUE THREAD

**Issue by RobinSc006** [CombatExtended-Continued/CombatExtended#228]
Mod name: Science Never Stops: Ambition of the Cosmic

Link to mod download: https://steamcommunity.com/sharedfiles/filedetails/?id=1802857253

Description:
The mod adds a bunch of end game content like new materials, power generation and hydroponics. It also adds weapons, turrets and armor that are currently completely incompatible with Combat Extended. 

Content:
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and GitHub for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] Have completed this template accurately and completely.
- [x] Understand that putting in a Patch Request does not guarantee a patch will be made.
- [x] Agree that I will not directly contact contributors to ask about patch requests.

**Comment by onigamii** [comment]
Author made a patch himself: https://steamcommunity.com/sharedfiles/filedetails/?id=2298661324

**Comment by tprussak** [comment]
The author's patch has been abandoned as of June 2022, this should probably be reopened, though any patch can likely use the Author's patch as a starting point.
