### ISSUE TITLE
MultiplayerCompat; random desyncs when firing a weapon, minigun works best to ruin your MP experience

### ISSUE THREAD

**Issue by EugeneRimworld** [CombatExtended-Continued/CombatExtended#2318]
**Specifications**

Rimworld version: 1.4.3613
Combat Extended version: 1.4.5.1
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows 10
Your mod list:
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
    <li>rwmt.multiplayer</li>
    <li>rwmt.multiplayercompatibility</li>
    <li>ceteam.combatextended</li>
    <li>ceteam.combatextendedarmors</li>
    <li>ceteam.combatextendedguns</li>
    <li>ceteam.combatextendedmelee</li>
    <li>n7huntsman.combatextendedshields</li>
    <li>thewirelord354.conduitdeconstruct</li>
    <li>tikubonn.dontblockdoor</li>
    <li>edb.preparecarefully</li>
    <li>notfood.mendandrecycle</li>
    <li>twistedpacifist.reasonablecomponents</li>
    <li>uuugggg.replacestuff</li>
    <li>thyphenrex.rexsarmorretexture</li>
    <li>frozensnowfox.filthvanisheswithrainandtime</li>
**Description**
It seems like guns with a lot of bullets causes de-syncs. Idk what exactly happens, but I tested it with 3 pawns with miniguns hitting a wall. I got not a lot of de-syncs hitting a wall, but as soon as they start to attack something in open and bullets travel to the furthest parts of a map, im getting de-syncs much more often. Situation becomes better if pawns use rifles or pistols, weapons that dont spam bullets in general.

**Expected behavior**

**To reproduce**
Create dev quicktest map, spawn 3 minigun + bullets, host that map, let a second client connect to it.

**Screenshots & log dumps**
https://pastebin.com/7PF6vVec ////host traces
https://pastebin.com/i0enzEQP ////local logs
https://pastebin.com/9BCqS3XW ////local traces
https://pastebin.com/5zzRHfLd ////desync info

**Complete the following checklist**
I hereby verify that I have done the following:
- [ x ] Confirmed that my game version and load order are correct.
- [ x ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ x ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ x ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SokyranTheDragon** [comment]
Is this still relevant? I've just tested and I can't reproduce this. I've tried to reproduce it by shooting at walls, pawns, different objects, both close and far. And including different firing/targeting modes. Everything was fine on my end.
