### ISSUE TITLE
[Patch Request]: More Injuries

### ISSUE THREAD

**Issue by PlaYerBr001** [CombatExtended-Continued/CombatExtended#2324]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**

**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**

**Title should be:** [Patch Request]: (Mod Name)

**Mod name:** More Injuries

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2892012512&searchtext=More+injuries

**Description:**
Provide a brief overview of what content the mod adds or modifies. Specify what content in particular you believe requires a patch to be compatibly with Combat Extended.

Wherever pawns got some type o damage on the torso, a message in the Debug Log appears
"Added injury to Torso but it should be impossible to hit it".

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [ ] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X ] Confirmed there are no other open Patch Requests for this mod.
- [X ] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X ] **Have completed this template accurately and completely.**
- [X ] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X ] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by PlaYerBr001** [comment]
the recreate the problem just shot pawns on the torso

**Comment by SamaelGray** [comment]
This is an old issues with More Injuries itself, not a CE thing.
