### ISSUE TITLE
[Bug]:Perfomance issues with turrets

### ISSUE THREAD

**Issue by MaxDorob** [CombatExtended-Continued/CombatExtended#2394]
[Bug]: Perfomance issues with turrets

**Specifications**

Rimworld version:
Combat Extended version: Copied from repository around 4 days ago.
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system:
Win 10
Ryzen 7 5800x3d
32GB Ram
RTX 3060 
Your mod list: ~100 mods. Check linked hugs-logs

**Description**
A few turrets can decrease your TPS. Transpiled method BestAttackTarget average time is 14ms. And that calls a lot times for 9 turrets. (Check screenshots for Dubs analyzer report)

**To reproduce**
Dont know. Check screenshots.

**Screenshots & log dumps**
https://gist.github.com/HugsLibRecordKeeper/0513d8d309cf8a7c0e72b23d121afc28
https://imgur.com/a/mmQ15Kr

**Complete the following checklist**
I hereby verify that I have done the following:
- [V] Confirmed that my game version and load order are correct.
- [V] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [V] Confirmed I am not running any mods with known incompatibilities with Combat Extended.

**Comment by SamaelGray** [comment]
Set your turrets to Hold-Fire when not in use. This is a base game issue that is already optimized by 50% in CE, we can't do much about it at this point.
