### ISSUE TITLE
[Bug]: error with you are running CE uncompiled

### ISSUE THREAD

**Issue by H0nok4** [CombatExtended-Continued/CombatExtended#2406]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)
![image](https://user-images.githubusercontent.com/45478238/226958320-41933ea9-a712-48f9-a2a1-e13023ea26b2.png)
is my first time install CE and didnt work,
**Specifications**
Please provide the following.

Rimworld version:
Combat Extended version: v5.2
Combat Extended source (Steam, GitHub, etc.):
Your operating system:
Your mod list:
![image](https://user-images.githubusercontent.com/45478238/226958777-8fa714a3-e28f-493f-a16b-949ef10d1f34.png)

**Expected behavior**
no error

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [ ] Confirmed that my game version and load order are correct.
- [ ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
As the message says, either download the latest dev snapshot from the this link or sub to the steam workshop item.

https://combatextended.lp-programming.com/CombatExtended-latest.zip
