### ISSUE TITLE
[Patch Request]: WVC - Xenotypes and Genes

### ISSUE THREAD

**Issue by FayFlightee** [CombatExtended-Continued/CombatExtended#2441]
**Mod name:** WVC - Xenotypes and Genes

**Link to mod download:** https://steamcommunity.com/sharedfiles/filedetails/?id=2886992038&searchtext=WVC+-+Genes

**Description:**
Provides many, **many** genes. But some may need patching, specifically the mecha-claws and scythe tails in particular.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons. (Does genes-added attacks count? I'm assuming so.)
- [x] New animals, humanoids, or other creatures. (maybe? It's new genes and xenotypes)
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
External patch exists, linked in the main mod's description.
