### ISSUE TITLE
[Bug]: Prestige Armor is missing toxic sensitivity and smoke sensitivity attributes

### ISSUE THREAD

**Issue by FGRemastered** [CombatExtended-Continued/CombatExtended#247]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.2
Combat Extended version: latest as of 2020/08/29
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win10x64
Your mod list: very long/no relevant mods except CE and Add-ons

**Description**
Prestige Armor is missing smoke and toxic sensitivity nullification which their normal counterparts have

**Expected behavior**
I expected them to have the same or slightly nerfed versions of the aforementioned attributes

**To reproduce**
spawn a prestige cataphract armor (helmet)

**Screenshots & log dumps**
Unnecessary 

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Fixed in the dev branch. Thanks.
