### ISSUE TITLE
[Bug]: Wrong ammos at spawn

### ISSUE THREAD

**Issue by Kalmorph** [CombatExtended-Continued/CombatExtended#2480]
**Specifications**
Rimworld version: 1.4.3704
Combat Extended version: 1.4.5.2
Combat Extended source (Steam, GitHub, etc.): Steam Workshop
Your operating system: Windows Pro Edition 10

**Description and Expected Behaviour**
When randomizing pawns before start, they can have an additional gun and their respective ammo, but if using the *Simplified Ammo* setting, they will only show the original/complex one, and ended not spawning the ammo at start.
Eg: Got a pawn with 'bodyguard' background, and spawned with an M1911 with ".45 ACP" ammo. Since I was using the simplified ammo settings, it should be "pistol cartridge (FMJ).

**To reproduce**
Set simplified ammo ON, restart, create a new colony, and when choosing new pawns, randomize it until one with a gun appears. Start the game, and the ammo will vanish, making only the gun to spawn.

**Screenshots & log dumps**
I don't believe it's necessary, but let me know if it really needs it.

**Comment by N7Huntsman** [comment]
It is important that you restart your game after toggling the simplified ammo option on/off for the changes to take place. Did you do this?

**Comment by Kalmorph** [comment]
Just a heads-up since this bug still happens on latest RW and CE version (Im lazy to get all numbers, 100% sure i got my RW in latest version on Steam and using CE from Workshop version atm)

**Comment by databobek** [comment]
I can confirm the issue:
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/26349586/e500d281-453c-4e41-a3c7-4fc005ad8ee8)
notice that caliber is pistol but the .45 is not hidden. .45 will spawn in caravans and on pawns but non-generic ammo is not usable with the guns.


all of these ammunitions should not be visible with generic on.
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/26349586/64d1ec9a-3dec-4c7b-9a99-c8da4f45577a)

**Comment by Maple38** [comment]
Also having this bug, but I toggled generic ammo on _after_ starting the save.
