### ISSUE TITLE
[Bug]: Combat Extended and Rabbie - The Moonrabbit Race

### ISSUE THREAD

**Issue by Nubasik** [CombatExtended-Continued/CombatExtended#255]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: RimWorld v1.2.2739
Combat Extended version: Version: 1.2.3.1 (the last)
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Win7x64
Your mod list:
Harmony
Core, Royalty
HugsLib
Humanoid Alien Races
Combat Extended
Hats Display Selection
Rabbie - The Moonrabbit Race

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
Log - https://gist.github.com/HugsLibRecordKeeper/b23934befde24e34efc29a578346d32c

**Complete the following checklist**
I hereby verify that I have done the following:
- [+] Confirmed that my game version and load order are correct.
- [+] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [+] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by onigamii** [comment]
This is an error on Rabbie's side, they add their own weaponTag to the minigun when CE removes the minigun weaponTags it's a harmless error. I contacted the author hopefully they fix it soon.
