### ISSUE TITLE
[Bug]: Wrong value about the pawn stats(Weapon handling)

### ISSUE THREAD

**Issue by Surgeol** [CombatExtended-Continued/CombatExtended#2554]
Rimworld version: 1.4.3704
Combat Extended version: 1.4.5.3
Combat Extended source: Steam Workshop
Your operating system: Windows 10

Your mod list(only three): 
- Harmony
- Core
- Combat Extended

**Description**
I'm not sure if this value is normal, as I've never noticed this stats(weapon handling) before. Check the picture below.
<details><summary>CLICK ME</summary>

![Screenshot](https://github.com/CombatExtended-Continued/CombatExtended/assets/35412032/b2b2d7ef-c0a3-4557-aea6-e16a41c842e0)
</details>

**To reproduce**
Just start a new game via quicktest, and check the _Weapon handling_ stats of any pawn. The value may not necessarily be very large, it can also be small, but you can be felt not belong to the normal range.

**Screenshots & log dumps**
I have checked the log, there are no warn/error message during my test. Also I'll post my CE settings.
<details><summary>CLICK ME</summary>

![Settings](https://github.com/CombatExtended-Continued/CombatExtended/assets/35412032/670f4fc6-70b4-4007-a814-7c70c99d7a98)
</details>

I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
This is known and a normal behavior, the values apart from the first one are the remnants of the vanilla range-based accuracy stats which does not exist in CE.
