### ISSUE TITLE
[Bug]: Combat Extended and Rimworld Altered Carbon

### ISSUE THREAD

**Issue by Nubasik** [CombatExtended-Continued/CombatExtended#256]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: RimWorld v1.2.2739
Combat Extended version: Version: 1.2.3.1 (the last)
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Win7x64
Your mod list:
Harmony
Core, Royalty
HugsLib
Combat Extended
Rimworld Altered Carbon

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
Log - https://gist.github.com/HugsLibRecordKeeper/b5c6ae0fedecbe09b0e82696311e43ef

**Complete the following checklist**
I hereby verify that I have done the following:
- [+] Confirmed that my game version and load order are correct.
- [+] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [+] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by onigamii** [comment]
If you dared to read the damned changelog you'd notice that this is intended and it's harmless.
