### ISSUE TITLE
[Patch Request]: Dub's Bad Hygiene (water bottle inventory infinite loops)

### ISSUE THREAD

**Issue by FatalError42O** [CombatExtended-Continued/CombatExtended#2565]
Dub's Bad Hygiene
https://steamcommunity.com/sharedfiles/filedetails/?id=836308268

**Description:**

Problem:
Pawns will get stuck in an infinite loop dropping water bottles from their inventory, and subsequently picking them up (as enforced by Dub's Bad Hygiene).

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by SamaelGray** [comment]
You either use DBH's forced setting or disable it and use CE's inventory system.
