### ISSUE TITLE
[Bug]: Debug Log error upon start

### ISSUE THREAD

**Issue by KixShadowx** [CombatExtended-Continued/CombatExtended#2579]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.4.3704
Combat Extended version: 1.4.5.3
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 11
Your mod list: Harmony, Core, Royalty, Ideology, Biotech, CE, Glittertech in this order

**Description**
After starting the Debug Log pops up with the error line (screenshot)

**To reproduce**
Launch the game. I tried if loading Glittertech over CE fixes it but same error.

**Screenshots & log dumps**
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/138239729/66794e9f-c426-4562-b236-4f4cc85bbcf7)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Gonna need a Hugslog foe that.

**Comment by KixShadowx** [comment]
I hope this helps :)

https://pastebin.com/FdBDe6m9

**Comment by SamaelGray** [comment]
Just checked glittertech's CE patch and that duplicate node or even the patch that alters that does not exist in CE.
Do a fresh install of both CE and Glittertech (unsub and remove the old files manually then resub), it should fix the issue.

**Comment by KixShadowx** [comment]
I did as you said but it's still not working. I also tried the version from Github. (not the def version but the one from the link posted in the readme file)
I still get the same two errors.

**Comment by SamaelGray** [comment]
can you check and see if Glittertech has a built-in CE patch in its potential Patches folder?
