### ISSUE TITLE
[Patch Request]: EdB Prepare Carefully - Clothing Layers

### ISSUE THREAD

**Issue by HerbertFalsevor** [CombatExtended-Continued/CombatExtended#2594]
**Mod name:** EdB Prepare Carefully

**Link to mod download (preferably Steam workshop or Github):** 
https://steamcommunity.com/sharedfiles/filedetails/?id=735106432&searchtext=edb

**Description:**
I have noticed that EdB does not allow the selection of multiple CE-Patched clothes due to a category mismatch. Examples are: 
Rimeffect: https://steamcommunity.com/sharedfiles/filedetails/?id=2479560696
RH2 Faction: Utilitarian: https://steamcommunity.com/sharedfiles/filedetails/?id=2942350062&searchtext=RH2
RH2 Faction: Bounty Hunters:: https://steamcommunity.com/sharedfiles/filedetails/?id=2889605556&searchtext=RH2

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.
- [x] Misc -> EdB clothing layers appear to not be compatibile with CE ones. Helmets/Armours often get lost.

https://pastebin.com/99qNEJAC

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by SamaelGray** [comment]
You should not use EDB Prepare Carefully period, it straight-up bricks saves...
