### ISSUE TITLE
[Bug]:Regarding the SupportedThirdPartyMods, the patches in CE are not properly taking effect for mods by ayameduki (such as Xenoorca Race).

### ISSUE THREAD

**Issue by 605466024** [CombatExtended-Continued/CombatExtended#2609]
Rimworld version:1.4.3704 rev896
Combat Extended version:1.4.5.3
Combat Extended source:SteamWorkShop
Your operating system:windows10
Your mod list:
Harmony/HumanoidAlienRaces/
racemod created by the mod author ayameduki(Solark Race/SilkieraRace/SacleanRace......)
CombatExtended 

**Description**
Although the following mods, (Solark Race/Silkiera Race/Saclean Race/Xenoorca Race/Idhale Race/Littluna Race/Neclose Race/Nearmare Race), are included in SupportedThirdPartyMods, they are not compatible with CE. The reason is that when the author, ayameduki, upgraded these mods from 1.3 to 1.4, they changed the line "ModMetaData><name>[1.3]Solark Race</name" to "ModMetaData><name>[1.4]Solark Race</name". After replacing the patches files in the CE's "patches" folder from 1.3 to 1.4, these mods can be recognized and are now compatible.

However, there are still some issues. Rimworld reported partial error logs, specifically in the pawnkind.xml file in the pawnkinddefs. CE is unable to generate Backpacks for pawns in these mods.

**To reproduce**
I replaced all instances of [1.3] with [1.4] in the XML files related to mods in CE\Patches. For example, in the file CE\Patches\Xenoorca Race\PawnKindDefs\Xenoorca_PawnKind.xml, I changed [1.3] to [1.4] in the line "mods>[1.3]Xenoorca Race</mods". Other parts are functioning correctly, such as the contents in Bodies and Hediffs. However, there are error prompts in the pawnkinddefs section.

**Expected behavior**
I'm not sure why only the pawnkinddefs section (and some thingdefs races) is causing errors. How can I make these sections work correctly? Or, I would like CE to officially update these patches to version 1.4 to ensure full compatibility with these mods.

**Screenshots & log dumps**
![log](https://github.com/CombatExtended-Continued/CombatExtended/assets/115719163/60fd0683-7809-4341-acfd-707b23aaa837)

**Complete the following checklist**
I hereby verify that I have done the following:
- [√] Confirmed that my game version and load order are correct.
- [√] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [√] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [√] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by 605466024** [comment]
Oh, by the way, all the mentioned mods are from the latest version on Steam Workshop (as of July 10th, 2023).which is specifically for RimWorld version 1.4

**Comment by N7Huntsman** [comment]
These issues were resolved in the dev build by #2547 and will be added to the Steam version with the next release. If you want to resolve the issue now, you can make a local copy of CE and grab the updated patches for those mods from the Github dev branch.
