### ISSUE TITLE
[Bug]:Biotech cast patch doesn't work with explosive projectiles.

### ISSUE THREAD

**Issue by SaltyKarl** [CombatExtended-Continued/CombatExtended#2653]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:1.4.3704 rev896
Combat Extended version:1.4.5.3
Combat Extended source (Steam, GitHub, etc.):GitHub dev snapshot
Your operating system: Windows 11
Your mod list: https://pastebin.com/UNtNKDEP

**Description**
Provide a concise description of the issue or concern. What happened?
When biotech cast try to launch a projectile with explosive property it doesn't cast and the pawn frozen in place, and log spam red errors.

**Expected behavior**
What did you expect to happen?
the cast launches the projectile and it explodes.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
use the Biotech Expansion - Mythic's brilliantblast at anything

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
https://pastebin.com/UppKH6Jy

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Thorbane** [comment]
Pretty sure this is a targeting issue.  Current code attempts to find the location of the pawn specified by the LocalTargetInfo object, and throws NRE's when it doesn't have one.  As is the case when a cell is targeted instead of a thing.
