### ISSUE TITLE
[Bug]: Red Inventory Job error when Bow equipped and picking up arrows

### ISSUE THREAD

**Issue by quianalevitt** [CombatExtended-Continued/CombatExtended#2661]
**Specifications**
Rimworld version: 1.4.3704 rev896 Steam
Combat Extended version: 1.4.5.3 - From GitHub Bot Build on 07/25
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win 11
Your mod list: See HugsLog

**Description**
Drop down any bow that consumes neo arrows/ammo.  Have pawn equip bow.  Drop down stack of arrows of any type.  If pawn attempts to pick up arrows, it will cause error spam with Invalid count 0, setting to 1. Job was TakeInventory.  This error spam will vanish if the arrows are forbidden and pawn ordered to manually collect arrows.

**Expected behavior**
Pawn to pick up either amount they wanted by automatic ammo load, or when ordered to do so manually.

**Screenshots & log dumps**
https://gist.github.com/HugsLibRecordKeeper/581299c9f34b41aaa25db31e4762e71a

**Complete the following checklist**
I hereby verify that I have done the following:
- [X ] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by gago234** [comment]
Just discovered this problem too. Here is the problem:
[https://github.com/CombatExtended-Continued/CombatExtended/pull/2624/files](url)

maxAmmoToPickup  is 0 with bows, so I changed it into something like:
`job.count = (maxAmmoToPickup > 0) ? Mathf.Min(numToCarry, maxAmmoToPickup) : numToCarry / 4;`

The / 4 could be done definitely smarter though. At least they don't load their inventories full with arrows.
