### ISSUE TITLE
[Bug]: Unloading the turret is an infinite activity yielding endless stacks of ammo

### ISSUE THREAD

**Issue by databobek** [CombatExtended-Continued/CombatExtended#2718]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.4.3704
Combat Extended version: 1.4.5.4
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list: https://rentry.co/ybvgo

**Description**
I changed the type of ammo in a turret. Pawn came up and unloade the turret which caused:
```
JobDriver threw exception in toil unnamed's initAction for pawn D-E6-9C driver=JobDriver_ReloadTurret (toilIndex=3) driver.job=(ReloadTurret (Job_14616238) A=Thing_Turret_Mortar8255426 B=Thing_Shell_81mmIncendiary_PGK_TC8659508)
System.NullReferenceException: Object reference not set to an instance of an object
  at (wrapper dynamic-method) Verse.GenDrop.Verse.GenDrop.TryDropSpawn_Patch1(Verse.Thing,Verse.IntVec3,Verse.Map,Verse.ThingPlaceMode,Verse.Thing&,System.Action2<Verse.Thing, int>,System.Predicate1<Verse.IntVec3>,bool)
  at RimWorld.GenThing.TryDropAndSetForbidden (Verse.Thing th, Verse.IntVec3 pos, Verse.Map map, Verse.ThingPlaceMode mode, Verse.Thing& resultingThing, System.Boolean forbidden) [0x00000] in <95de19971c5d40878d8742747904cdcd>:0 
  at CombatExtended.CompAmmoUser.TryUnload (Verse.Thing& droppedAmmo, System.Boolean forceUnload) [0x0025c] in <7b4e4f24c08642ccb86c06b4e8ac35ff>:0 
  at CombatExtended.JobDriver_ReloadTurret+<>cDisplayClass11_0.<MakeNewToils>b3 () [0x000d4] in <7b4e4f24c08642ccb86c06b4e8ac35ff>:0 
  at (wrapper dynamic-method) Verse.AI.JobDriver.Verse.AI.JobDriver.TryActuallyStartNextToil_Patch0(Verse.AI.JobDriver)
```

After which the turret kept the ammo it had, while "copy" of the ammo inside was placed on the ground, ad infinitum.

**Expected behavior**
I expected that pawn will be able to change the type of ammo in the turret.

**To reproduce**
Change type of ammo in a turret that already has ammo. Pawn will come up and try to unload the existing ammo, on which an error is thrown and the stack drops on the ground but does not empty the turret.

**Screenshots & log dumps**
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/26349586/7cbc36c7-2c25-400b-a73b-777f1a9eeef3)

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success. (not relevant)

**Comment by SamaelGray** [comment]
Your mod list is rather big and this is not a behavior of CE under normal situations, make sure you can replicate it with minimal mods, it definitely is a mod conflict.

**Comment by Yolsos** [comment]
It's not a mod conflict unfortunately, I ran with just CE, Core, DLC, and harmony but got the same behavior.

**Comment by SamaelGray** [comment]
Rebuild the turret, it's a one-time issue.

**Comment by databobek** [comment]
confirmed the solution

**Comment by databobek** [comment]
actually it only worked on the first time

![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/26349586/bf679085-7e96-4e80-bddb-adbfa4f0dc0d)

**Comment by irRegularGuy646** [comment]
I can confirm the issue, rebuilding the turret only temporarily fixes the issue by creating a turret with no ammo in it. expending all the remaining ammo has the same effect.
