### ISSUE TITLE
[Bug]: [VF] [VVE] On save reload, auto-reloading settings default to 25 for all vehicles with guns

### ISSUE THREAD

**Issue by databobek** [CombatExtended-Continued/CombatExtended#2719]
Complete the template below. Reports that do not follow the template will be deleted.
Title should be: [Bug]: (Short description of bug)

Specifications
Please provide the following.

Rimworld version: 1.4.3704
Combat Extended version: 1.4.5.4
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list: https://rentry.co/ybvgo

**Description**
I set a vehicle to reload automatically to 305. I saved. I reloaded. The auto-reloading is set to 25 now.

**Expected behavior**
I expected the auto-reloading setting to stay at 305.

**To reproduce**
Set auto-reloading setting to not 25, save game, reload that save game, check the sttings.

**Screenshots & log dumps**
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/26349586/b9a7515c-28b8-4386-b697-33c700798ce2)
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/26349586/b3726052-8165-43b4-bd03-0cd4b7e3673b)

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success. (not relevant)

**Comment by SamaelGray** [comment]
Have you managed to replicate this without CE?
It does not seem anything related to CE.

**Comment by databobek** [comment]
I assumed it's a CE function (because of ammo) sorry, might've been wrong about that.  Please close if that's the case.

**Comment by databobek** [comment]
It is not related to VE or VVE or CE, sorry for raising this in error. Does not occur on minimum modlist.
