### ISSUE TITLE
[Bug]: Ranged weapon unequipped when reloaded without ammunition

### ISSUE THREAD

**Issue by seasidesand** [CombatExtended-Continued/CombatExtended#2790]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.4.3704 rev874
Combat Extended version: 1.4.5.4
Combat Extended source (Steam, GitHub, etc.): Steam (using RimPy)
Your operating system: Windows 11
Your mod list: Harmony Core Combat Extended

**Description**
Provide a concise description of the issue or concern. What happened?
Ranged weapon is unequipped if you reload it without any ammunition on the pawn.

**Expected behavior**
What did you expect to happen?
Weapon remaining equipped and nothing else.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Pick up a short bow. Do not pick up arrows yet. Press reload.
The bow should disappear and now you cannot use it, even if you manually pick up arrows. (Also the pawn doesn't seem to pick up arrows on his own, see: #2789)
You must equip the bow again.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
https://cdn.discordapp.com/attachments/743002393675038753/1156013823283699782/image.png
https://cdn.discordapp.com/attachments/743002393675038753/1156013851091943424/image.png
https://cdn.discordapp.com/attachments/743002393675038753/1156013871287513188/image.png

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
This is normal behavior, pawns stow away their empty weapon and switch to a melee weapon.
