### ISSUE TITLE
[Patch Removal Request]: Remove Turk's Guns patch from CE

### ISSUE THREAD

**Issue by TurklerRS** [CombatExtended-Continued/CombatExtended#2807]
**Mod name: Turk's Guns**

**Link to mod download (preferably Steam workshop or Github): None, see below**

**Description:**
Quite a while ago, back in 1.3, I released a mod called Turk's Guns. It was on the workshop and was quickly patched on CE's end. I eventually took down the mod as I felt the mod was quite poor in quality, not up to my standards. I was using local copies of every mod at the time, and while switching over to 1.4, I nuked my entire mods folder without much thought. I did not realize this at the time, but this destroyed the only local copy I had of the mod. With the Steam Workshop version removed and local copy gone, the mod no longer exists. The patch can safely be removed from Combat Extended's built-in patches.

**Comment by N7Huntsman** [comment]
Done.
