### ISSUE TITLE
[Bug]: Gizmos triggered twice for Ratkin Subject race

### ISSUE THREAD

**Issue by fifea** [CombatExtended-Continued/CombatExtended#2808]
**Specifications**
Please provide the following.

Rimworld version: 1.4.3704
Combat Extended version: v5.4-Hotfix
Combat Extended source (Steam, GitHub, etc.): Both
Your operating system:
Your mod list:

- Harmony
- Core
- Royalty
- Ideology
- Biotech
- Hugslib
- Camera+
- CharacterEditor
- HumanoidAlienRaces
- NewRatkinPlus
- CombatExtended

**Description**
Gizmos like the aim mode and target modes are triggered twice if the pawn race is Ratkin_Su. Since there are 4 states for the target mode gizmo, only "Body" and "Legs" are selectable, skipping "Head" and "Automatic".

I added some logging to confirm [ChangeTargetMode()](https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs#L212) is called twice on every click.

I also confirmed that regular Ratkin pawns only calls the function once.

**Expected behavior**
Clicking on target mode only calls `ChangeTargetMode` once.

**To reproduce**
Create a pawn with race = "Ratkin Subject" and arm them with a ranged weapon.  Set Shooting to >8, try to change target mode.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.

**Comment by Theblessedwant** [comment]
Just to clarify, are you using the github version or the steam version, since you listed both. I dont seem to be having this issue on my end 
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/57470753/aeb6bc88-79fe-406f-b7b4-f8c0d8ea7f22)
