### ISSUE TITLE
[Patch Request]: Altered Carbon update

### ISSUE THREAD

**Issue by BigBarza** [CombatExtended-Continued/CombatExtended#2835]
**Mod name:** Altered Carbon: Ultratech Unleashed

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2196278117

**Description:**
The mod already has a patch. However, a recent update added new armors and broke the existing patch for the protector armor (helmet is still patched properly)

**Content:**
(That is relevant for this request)
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by katanacrimson** [comment]
Helmet is *not* being patched properly, from what I can see.

```

**Comment by BigBarza** [comment]
Figured this stuff out after some time in the discord.
PR for this issue: #2838

**Comment by BigBarza** [comment]
Patch has been merged, closing the issue.
Note for myself: figure out how to link PRs to issues to close them automatically.
