### ISSUE TITLE
[Bug]: CE 5.5 issues with vanila Extended?

### ISSUE THREAD

**Issue by DancingWind** [CombatExtended-Continued/CombatExtended#2858]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)
latest update has soem errors

**Specifications**
Please provide the following.

Rimworld version: 1.4
Combat Extended version: 5.5
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: W11 x64
Your mod list:
Mods:
- Id: brrainz.harmony
  Name: Harmony
  SteamWorkshopId: 2009463077
- Id: ludeon.rimworld
  Name: Core
  SteamWorkshopId: 0
- Id: ludeon.rimworld.royalty
  Name: Royalty
  SteamWorkshopId: 0
- Id: ludeon.rimworld.ideology
  Name: Ideology
  SteamWorkshopId: 0
- Id: ludeon.rimworld.biotech
  Name: Biotech
  SteamWorkshopId: 0
- Id: ccl.patchoperation.highlander
  Name: PatchOperationHighlander
  SteamWorkshopId: 2552002158
- Id: vanillaexpanded.backgrounds
  Name: Vanilla Backgrounds Expanded
  SteamWorkshopId: 2775017012
- Id: unlimitedhugs.hugslib
  Name: HugsLib
  SteamWorkshopId: 818773962
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
  SteamWorkshopId: 2023507013
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
  SteamWorkshopId: 1718190143
- Id: vanillaexpanded.vfespacer
  Name: Vanilla Furniture Expanded - Spacer Module
  SteamWorkshopId: 2028381079
- Id: edb.preparecarefully
  Name: EdB Prepare Carefully
  SteamWorkshopId: 735106432
- Id: frozensnowfox.efficientutilities
  Name: '[FSF] Efficient Utilities'
  SteamWorkshopId: 951619111
- Id: fluffy.fluffybreakdowns
  Name: Fluffy Breakdowns
  SteamWorkshopId: 726244033
- Id: daniledman.hardworkinganimals
  Name: Hardworking animals 1.4
  SteamWorkshopId: 933324235
- Id: zal.moretradeships
  Name: More Trade Ships (Continued)
  SteamWorkshopId: 2892108461
- Id: fluffy.medicaltab
  Name: Medical Tab
  SteamWorkshopId: 715565817
- Id: notfood.mendandrecycle
  Name: MendAndRecycle
  SteamWorkshopId: 735241897
- Id: fluffy.modmanager
  Name: Mod Manager
  SteamWorkshopId: 1507748539
- Id: mehni.pickupandhaul
  Name: Pick Up And Haul
  SteamWorkshopId: 1279012058
- Id: hatti.qualitybuilder
  Name: QualityBuilder
  SteamWorkshopId: 754637870
- Id: neitsa.preparelanding
  Name: Prepare Landing
  SteamWorkshopId: 1095331978
- Id: lucifer.realisticrooms
  Name: Realistic Rooms Rewritten
  SteamWorkshopId: 2558042766
- Id: ogliss.thewhitecrayon.quarry
  Name: Quarry
  SteamWorkshopId: 2007576583
- Id: fluffy.fluffyrelations
  Name: Relations Tab
  SteamWorkshopId: 709317151
- Id: uuugggg.replacestuff
  Name: Replace Stuff
  SteamWorkshopId: 1372003680
- Id: jaxe.rimhud
  Name: RimHUD
  SteamWorkshopId: 1508850027
- Id: rimsenal.core
  Name: Rimsenal - Core
  SteamWorkshopId: 725947920
- Id: mlie.rationalromance
  Name: '[RF] Rational Romance (Continued)'
  SteamWorkshopId: 2013144996
- Id: syrchalis.setupcamp
  Name: '[SYR] Set Up Camp'
  SteamWorkshopId: 1470065926
- Id: adaptive.storage.framework
  Name: Adaptive Storage Framework
  SteamWorkshopId: 3033901359
- Id: unlimitedhugs.allowtool
  Name: Allow Tool
  SteamWorkshopId: 761421485
- Id: mlie.animalfeedtrough
  Name: Animal Feed Trough (Continued)
  SteamWorkshopId: 2071757940
- Id: fluffy.animaltab
  Name: Animal Tab
  SteamWorkshopId: 712141500
- Id: katavrik.crashlanding
  Name: Crash Landing
  SteamWorkshopId: 2289694750
- Id: vanillaexpanded.achievements
  Name: Vanilla Achievements Expanded
  SteamWorkshopId: 2288125657
- Id: vanillaexpanded.vwe
  Name: Vanilla Weapons Expanded
  SteamWorkshopId: 1814383360
- Id: vanillaexpanded.vweg
  Name: Vanilla Weapons Expanded - Grenades
  SteamWorkshopId: 2194472657
- Id: ceteam.combatextended
  Name: Combat Extended
  SteamWorkshopId: 2890901044
- Id: fluffy.colonymanager
  Name: Colony Manager
  SteamWorkshopId: 715565262
- Id: zylle.childboodbackstories
  Name: Childhood Backstories
  SteamWorkshopId: 3000770956
- Id: void.charactereditor
  Name: Character Editor
  SteamWorkshopId: 1874644848
- Id: mlie.centralizedclimatecontrol
  Name: Centralized Climate Control (Continued)
  SteamWorkshopId: 2007268173
- Id: fluffy.areaunlocker
  Name: Area Unlocker
  SteamWorkshopId: 725153576
- Id: fluffy.blueprints
  Name: Blueprints
  SteamWorkshopId: 708455313
- Id: erdelf.humanoidalienraces
  Name: Humanoid Alien Races
  SteamWorkshopId: 839005762
- Id: orion.hospitality
  Name: Hospitality
  SteamWorkshopId: 753498552
- Id: ratys.rtfuse
  Name: RT Fuse
  SteamWorkshopId: 728314182
- Id: ryder.satisfiedstorage
  Name: SatisfiedStorage
  SteamWorkshopId: 2003354028
- Id: petetimessix.simplesidearms
  Name: Simple sidearms
  SteamWorkshopId: 927155256
- Id: dhultgren.smarterconstruction
  Name: Smarter Construction
  SteamWorkshopId: 2202185773
- Id: mlie.smartervisitors
  Name: Smarter Visitors
  SteamWorkshopId: 3012491521
- Id: smashphil.vehicleframework
  Name: Vehicle Framework
  SteamWorkshopId: 3014915404
- Id: vanillaexpanded.vanillatraitsexpanded
  Name: Vanilla Traits Expanded
  SteamWorkshopId: 2296404655
- Id: vanillaexpanded.vanillatradingexpanded
  Name: Vanilla Trading Expanded
  SteamWorkshopId: 2785616901
- Id: vanillaexpanded.vtexe
  Name: Vanilla Textures Expanded
  SteamWorkshopId: 2016436324
- Id: oskarpotocki.vanillavehiclesexpanded
  Name: Vanilla Vehicles Expanded
  SteamWorkshopId: 3014906877
- Id: oskarpotocki.vanillavehiclesexpandedtier3
  Name: Vanilla Vehicles Expanded - Tier 3
  SteamWorkshopId: 3047892432
- Id: vanillaexpanded.vwel
  Name: Vanilla Weapons Expanded - Laser
  SteamWorkshopId: 1989352844
- Id: vanillaexpanded.vwenl
  Name: Vanilla Weapons Expanded - Non-Lethal
  SteamWorkshopId: 2454918354
- Id: vanillaexpanded.vanillasocialinteractionsexpanded
  Name: Vanilla Social Interactions Expanded
  SteamWorkshopId: 2439736083
- Id: vanillaexpanded.vanillaanimalsexpanded
  Name: Vanilla Animals Expanded
  SteamWorkshopId: 2871933948
- Id: vanillaexpanded.vaecaves
  Name: Vanilla Animals Expanded — Caves
  SteamWorkshopId: 2576512001
- Id: vanillaexpanded.vappe
  Name: Vanilla Apparel Expanded
  SteamWorkshopId: 1814987817
- Id: vanillaexpanded.vaeaccessories
  Name: Vanilla Apparel Expanded — Accessories
  SteamWorkshopId: 2521176396
- Id: vanillaexpanded.varme
  Name: Vanilla Armour Expanded
  SteamWorkshopId: 1814988282
- Id: vanillaexpanded.vanillabackstoriesexpanded
  Name: Vanilla Backstories Expanded
  SteamWorkshopId: 2861806869
- Id: vanillaexpanded.basegeneration
  Name: Vanilla Base Generation Expanded
  SteamWorkshopId: 2830358905
- Id: vanillaexpanded.vbookse
  Name: Vanilla Books Expanded
  SteamWorkshopId: 2193152410
- Id: vanillaexpanded.vbrewe
  Name: Vanilla Brewing Expanded
  SteamWorkshopId: 2186560858
- Id: vanillaexpanded.vbrewecandt
  Name: Vanilla Brewing Expanded - Coffees and Teas
  SteamWorkshopId: 2275449762
- Id: vanillaexpanded.vcooke
  Name: Vanilla Cooking Expanded
  SteamWorkshopId: 2134308519
- Id: vanillaexpanded.vcookestews
  Name: Vanilla Cooking Expanded - Stews
  SteamWorkshopId: 2134312965
- Id: vanillaexpanded.vcef
  Name: Vanilla Fishing Expanded
  SteamWorkshopId: 1914064942
- Id: vanillaexpanded.vcookesushi
  Name: Vanilla Cooking Expanded - Sushi
  SteamWorkshopId: 2158539170
- Id: vanillaexpanded.vee
  Name: Vanilla Events Expanded
  SteamWorkshopId: 1938420742
- Id: oskarpotocki.vanillaexpanded.ideologypatches
  Name: Vanilla Expanded - Ideology Patches
  SteamWorkshopId: 2566669771
- Id: oskarpotocki.vanillaexpanded.royaltypatches
  Name: Vanilla Expanded - Royalty Patches
  SteamWorkshopId: 2260012940
- Id: vanillaexpanded.vfearchitect
  Name: Vanilla Furniture Expanded - Architect
  SteamWorkshopId: 2608762624
- Id: vanillaexpanded.vfeart
  Name: Vanilla Furniture Expanded - Art
  SteamWorkshopId: 1968134023
- Id: vanillaexpanded.vfefarming
  Name: Vanilla Furniture Expanded - Farming
  SteamWorkshopId: 1957158779
- Id: vanillaexpanded.vfemedical
  Name: Vanilla Furniture Expanded - Medical Module
  SteamWorkshopId: 1718191613
- Id: murmur.walllight
  Name: Wall Light
  SteamWorkshopId: 1423699208
- Id: vanillaexpanded.skills
  Name: Vanilla Skills Expanded
  SteamWorkshopId: 2854967442
- Id: vanillaexpanded.vplantse
  Name: Vanilla Plants Expanded
  SteamWorkshopId: 2134308522
- Id: vanillaexpanded.vplantsemushrooms
  Name: Vanilla Plants Expanded - Mushrooms
  SteamWorkshopId: 3006389281
- Id: vanillaexpanded.vplantsesucculents
  Name: Vanilla Plants Expanded - Succulents
  SteamWorkshopId: 2198652536
- Id: vanillaexpanded.vgeneticse
  Name: Vanilla Genetics Expanded
  SteamWorkshopId: 2801160906
- Id: vanillaexpanded.vfepower
  Name: Vanilla Furniture Expanded - Power
  SteamWorkshopId: 2062943477
- Id: vanillaexpanded.vfeproduction
  Name: Vanilla Furniture Expanded - Production
  SteamWorkshopId: 1880253632
- Id: vanillaexpanded.vfepropsanddecor
  Name: Vanilla Furniture Expanded - Props and Decor
  SteamWorkshopId: 2102143149
- Id: vanillaexpanded.vfesecurity
  Name: Vanilla Furniture Expanded - Security
  SteamWorkshopId: 1845154007
- Id: vanillaexpanded.ideo.iconsandsymbols
  Name: Vanilla Ideology Expanded - Icons and Symbols
  SteamWorkshopId: 2552609458
- Id: vanillaexpanded.vmemese
  Name: Vanilla Ideology Expanded - Memes and Structures
  SteamWorkshopId: 2636329500
- Id: vanillaexpanded.ideo.relicsandartifacts
  Name: Vanilla Ideology Expanded - Relics and Artifacts
  SteamWorkshopId: 2564895018
- Id: vanillaexpanded.outposts
  Name: Vanilla Outposts Expanded
  SteamWorkshopId: 2688941031
- Id: mrhydralisk.voedeliverylogistics
  Name: 'Vanilla Outposts Expanded: Delivery Logistics'
  SteamWorkshopId: 3006726393
- Id: owlchemist.seedspleaselite
  Name: 'SeedsPlease: Lite'
  SteamWorkshopId: 2586052937
- Id: owlchemist.smartfarming
  Name: Smart Farming
  SteamWorkshopId: 2619652663
- Id: vanillaexpanded.viehar
  Name: Vanilla Ideology Expanded - Hats and Rags
  SteamWorkshopId: 2567387768
- Id: vanillaexpanded.viesas
  Name: Vanilla Ideology Expanded - Splits and Schisms
  SteamWorkshopId: 2573138902
- Id: mlie.stufflist
  Name: Stuff List (Continued)
  SteamWorkshopId: 2798767227
- Id: fluffy.worktab
  Name: Work Tab
  SteamWorkshopId: 725219116
- Id: gt.sam.tilledsoil
  Name: Tilled Soil
  SteamWorkshopId: 725747149
- Id: codeoptimist.jobsofopportunity
  Name: While You're Up / PUAH+
  SteamWorkshopId: 2034960453
- Id: dubwise.dubsmintmenus
  Name: Dubs Mint Menus
  SteamWorkshopId: 1446523594
- Id: notfood.morethancapable
  Name: More Than Capable
  SteamWorkshopId: 1803932954
- Id: lc.cheatspot
  Name: '[LYN] Cheat Spot'
  SteamWorkshopId: 2295451181

**Description**
Provide a concise description of the issue or concern. What happened?
Today CE updated in workshop

**Expected behavior**
What did you expect to happen?

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Post update bug onm launch

**Screenshots & log dumps**
https://pastebin.com/LEPJy73f

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Known issue. Fixed by #2854.
