### ISSUE TITLE
[Bug]: Gas Mask debuff healed by healer mech serum

### ISSUE THREAD

**Issue by AC-S22-03** [CombatExtended-Continued/CombatExtended#2865]
**Specifications**

Rimworld version:
Combat Extended version: 1.4.5.5 (latest)
Combat Extended source (Steam, GitHub, etc.): steam
Your operating system: windows 10
Your mod list:
Harmony
Core
Royalty
Ideology
Biotech
Combat Extended

**Description**
i had a colonist with dementia and gas mask equipped. i used a healer mech serum and it healed the debuff of the mask

**Expected behavior**
i expected it to heal the dementia that the colonist had

**To reproduce**
Just equip a colonist with a gas mask (the biotech or the CE mask) and add any ailment (i tested it with dementia) and the serum heals the debuff from the mask

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Drunkender** [comment]
Defs/HediffDefs/Hediffs_CE.xml
Needs
<EverCurableByItem>False</EverCurableByItem>
in
<defName>WearingGasMask</defName>

**Comment by N7Huntsman** [comment]
Good catch, I've PR'd a fix.
