### ISSUE TITLE
[Bug]: Wrong similarTo tags on some calibers

### ISSUE THREAD

**Issue by TurklerRS** [CombatExtended-Continued/CombatExtended#2873]
**Specifications**
Please provide the following.

Rimworld version:
Combat Extended version: Latest dev version downloaded from github, Version: 1.4.5.5 according to the about.xml file
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows
Your mod list:
1. Harmony
2. [Vanilla and DLCs]
3. Combat Extended

**Description**
Pull 2854 (https://github.com/CombatExtended-Continued/CombatExtended/pull/2854/commits/f924d9898aff62a45fa9e34fa5a026d6c13f66e6) fixed some issues regarding the similarTo field used for generic ammo. While many calibers were fixed, AmmoSet_66mmThermalBolt and AmmoSet_80x256mmFuel still use the old AmmoSet_MechShell.

This problem can be fixed by simply replacing the instances of AmmoSet_MechShell with AmmoSet_MechShell_Demo.

**Expected behavior**
AmmoSet_66mmThermalBolt and AmmoSet_80x256mmFuel to be converted into generic Mech Shells with the generic ammo setting enabled.

**To reproduce**
Simply launch the game with the generic ammo setting enabled and check any weapons that use either AmmoSet_66mmThermalBolt or AmmoSet_80x256mmFuel.

**Screenshots & log dumps**
[Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. ](https://gyazo.com/882b6d0b4af2abdc513b8c00399fdd16)

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SamaelGray** [comment]
Both the 66mm thermal bolts and 80mm fuel cells are correctly assigned to the generic mech shell ammo, the demo shells were specifically made for things similar to the thump cannon weapon which has FSX in its recipe instead of Prometheum.
The problem of the various mech ammo types not converting into their correct generic ammo type lies elsewhere.
