### ISSUE TITLE
[Patch Request]: Fantasy Metals Reforged

### ISSUE THREAD

**Issue by Zero-Requiem22** [CombatExtended-Continued/CombatExtended#289]
Fantasy Metals Reforged

https://steamcommunity.com/sharedfiles/filedetails/?id=2173422423&searchtext=fantasy+metals 

**Description:**
This Mod adds about 6 new ores/material that can be used to craft the already existing Structures, Weapons and Armor.

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by N7Huntsman** [comment]
Patched added by #291
