### ISSUE TITLE
[Patch Request - Update]:Archotech Weaponry

### ISSUE THREAD

**Issue by fluctuatingpulses** [CombatExtended-Continued/CombatExtended#2897]
Archotech Weaponry
https://steamcommunity.com/sharedfiles/filedetails/?id=2959623724)

Already patched, but could use an update

Such as:
*Patch for the Archotech Voidlauncher
  [Maybe the less-lethal variant could be an HE warhead either spreading void toxin/necrosis, with the lethal mode being a high-penetration HEAT/EFP warhead)
*Patch for melee damage on weapons which may have not been patched for melee damage
[Just the Archotech Sniper, Archotech Rifle, & Archotech Voidlauncher as far as I can tell]

I hereby verify that I have done all of the following:
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by SaltyKarl** [comment]
Can confirm archorifle and sniper are missed in melee patch but Voidlauncher's melee tools are patched at least in xml, as for Voidlauncher's range patch will not work with it's tracking mechanic.
