### ISSUE TITLE
[Patch Request]: Save Our Ship 2 - Extensions

### ISSUE THREAD

**Issue by CerberusHellHound** [CombatExtended-Continued/CombatExtended#290]
**Title should be:** [Patch Request]: (Mod Name)

**Mod name:** Save Our Ship 2 - Extensions

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2125698178

**Description:**
An extension to the already patched SOS2 mod (well, I do believe it is? It's in the patch folder). Adds various spacer and archotech devices, weapons and machines as well as turrets for your SOS2 ship. 

**Content:**
What does the new mod contain? Check all that apply.
- [X] New weapons.
- [X] New animals, humanoids, or other creatures.
- [X] New factions.
- [X] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [ ] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by Breadbox2k19** [comment]
Considered outdated for whatever reason.
