### ISSUE TITLE
[Bug]: Trenches from vanilla expanded do not work

### ISSUE THREAD

**Issue by iv2b** [CombatExtended-Continued/CombatExtended#293]
**Specifications**

Rimworld version: 1.2.2753
Combat Extended version: 1.2.3.1
Combat Extended source (Steam, GitHub, etc.): steam
Your operating system: w10
Your mod list:  Harmony, core, royalty, hugslib, combat extended, Vanilla Furniture Expanded - Security

**Description**
Trenches do not provide any defensive bonus, they only slow pawns who enter or leave them.
No bonus is mentioned in the tooltip, cover and target height do not change when attacking pawn in a trench.

**Expected behavior**
I'd expect some cover bonus, ideally lowering the pawn height when not firing, allowing them to fire unhindered while providing full coverage when standing still when used in conjunction with embrasures/sandbags/barricades/etc.

**To reproduce**
Build a trench.

**Screenshots & log dumps**
N/A

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Alicecomma** [comment]
Although there were team discussions at some point, nobody did work on it.

The easiest implementations are to override the minimum heights of things:
- Lower minimum pawn height if standing on a certain building/terrain (currently buildings raise pawns)
- Change projectile code so a height of 0f doesn't destroy the bullet, rather that a height of minimum terrain height does

But you definitely need to take into account at least one situation:
- Ensure the **border** of 0f terrain is hit when a projectile impacts from a lower-than-0f terrain

**Comment by perkinslr** [comment]
Done.  Likely edge cases to find, but overall now functional.
