### ISSUE TITLE
[Patch Request]: Half-Life Weapons Pack

### ISSUE THREAD

**Issue by HerbertFalsevor** [CombatExtended-Continued/CombatExtended#2955]
**Mod name:** Half-Life Weapons Pack

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2449584633&searchtext=half+life

**Description:**
Adds a bunch of weapons from half life 1, 2 and alyx. Pulse weapons included.

Requires patching in terms of damage, used ammo types (AR2 probs own pulse ammo, or at least charge ammo) range and reload speeds. Auto-patch sadly doesn't work too well for it.

It adds 3 pieces of armor (chestpieces afaik) that would need to be patched in accordance to tier (HEV Mk III, IV and V)

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by N7Huntsman** [comment]
There's a 3rd party patch floating around the workshop.
