### ISSUE TITLE
[Bug]: Unable to shoot downed pawns

### ISSUE THREAD

**Issue by ViralReaction** [CombatExtended-Continued/CombatExtended#2968]
**Specifications**
Unable to accurately hit pawns that have been downed.

Rimworld version:
Combat Extended version: 5.6
Combat Extended source : Steam and Github
Your operating system: Windows 10

**Description**
Downed pawns are unable to be shot accurately. Most time will miss downed pawn, unless utilizing a weapon that will in in an area such as a LMG.

**Expected behavior**
Pawn be hit by bullet.

**To reproduce**
Force shoot down pawn with CE assembly after [https://github.com/CombatExtended-Continued/CombatExtended/pull/2949](https://github.com/CombatExtended-Continued/CombatExtended/pull/2949) merger. If you grab a .dll prior to the merger, no issues hitting downed pawns.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by TkabRft** [comment]
Overall accuracy also feels weird: 
I have pawn with 20 skill and augments (206% manipulation, 144% sight), using KPV (0.01 degree of spread) and shooting at standing still (my own drafted) pawn in torso with single, aimed shots at 10 tiles of range - and hit ZERO TIMES from 100+ shots

**Comment by N7Huntsman** [comment]
Addressed in the 5.6 hf.
