### ISSUE TITLE
[Bug]: Asari & Reapers colossus lacks body tools patch and cannibal gun and marauder gun crash ui when info opened

### ISSUE THREAD

**Issue by databobek** [CombatExtended-Continued/CombatExtended#2975]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:1.4.3901 rev238
Combat Extended version: 1.4.5.7
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows 10
Your mod list:
[Mod list length: 9]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
Combat Extended [https:// no link (local mod)]
Ideology [Official DLC] [https:// no link (local mod)]
Biotech [Official DLC] [https:// no link (local mod)]
Vanilla Expanded Framework [https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Rim-Effect: Asari & Reapers [https:// no link (local mod)]
XML Extensions [https://steamcommunity.com/sharedfiles/filedetails/?id=2574315206]

**Description**
Asari & Reapers colossus lacks body tools patch - seems to have never had it?
cannibal gun and marauder gun crash ui when info opened

**Expected behavior**
i expected the guns to be properly patched like in 1.4.5.5
I expected colossus to have a body patch (even though it never had it :) )

**To reproduce**
Load combat extended and asari & reapers
spawn RE_Husk_Colossus, open info tab (red error)
spawn RE_Husk_Marauder, click on gear, click on gun info tab (UI Crashes)
spawn RE_Husk_Cannibal, click on gear, click on gun info tab (UI Crashes)

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Resolved
