### ISSUE TITLE
[Bug]: Guns without an assigned AmmoSet bug out the info panel.

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#2989]
**Specifications**
Please provide the following.

Rimworld version:
Combat Extended version: 5.6 hotfix.
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windows 10
Your mod list: Harmony, Core, DLCs, Combat Extended

**Description**
If a weapon has the `AmmoUser` field but does not have the `ammoSet` field (or the field is empty), it creates an error when trying to view weapon information. Upon opening the weapon info panel to view caliber, stats, and other information, the panel is blank and the error log starts spewing errors.

**Expected behavior**
Expected the weapon to fire from a magazine without requiring ammo to reload, and expected to be able to view weapon stats normally.

**To reproduce**
In the weapon XML, remove the `ammoSet` tag or leave the field empty. Leave the `ammoUser` tag there. Launch game, spawn the weapon in question, and then try to open the weapon's info panel.

**Screenshots & log dumps**
Error log: https://pastebin.com/NhVwixiE

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Thorbane** [comment]
Offending missing null check found.  Fixed.

Now it only fails to fire.

**Comment by Thorbane** [comment]
Offending null check in TryCastShot found & fixed.
