### ISSUE TITLE
[Patch Request]: Definitely More Cannons

### ISSUE THREAD

**Issue by cal066** [CombatExtended-Continued/CombatExtended#300]
Mod name: Definitely More Cannons

Link to mod download: https://steamcommunity.com/sharedfiles/filedetails/?id=1541884213

**Description:**
A mod that adds more cannon turrets, both manned and unmanned separated into several different types. Intended to be used as an extension of vanilla turrets.

**Content:**
What does the new mod contain? Check all that apply.
- [X] New weapons.
- [X] New animals, humanoids, or other creatures.
- [ ] New factions.
- [X] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
This mod is currently for RW version 1.1

**Comment by cal066** [comment]
This mods works as far as I know for 1.2, is there a policy to only work with mods tagged for 1.2?
If so, please go ahead and close this.
