### ISSUE TITLE
[Patch Request]: FCP - Classic Laser Weapons

### ISSUE THREAD

**Issue by Inazuma00** [CombatExtended-Continued/CombatExtended#3005]
[Patch Request]: FCP - Classic Laser Weapons

FCP - Classic Laser Weapons

https://steamcommunity.com/sharedfiles/filedetails/?id=2608148101

The Fallout Collaboration Project is a complete overhaul of Rimworld to include all things Fallout and create the beloved universe in the best possible way.

This is the FCP Classic Laser Weapons Pack, expect changes in the future to function and how to obtain them as well as crafting changes. These amazing Weapons were made by IcingWithCheeseCake! Now you can turn your enemies into a pile of ash!

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by N7Huntsman** [comment]
FCP maintains its own CE patches, which can be found here: https://steamcommunity.com/sharedfiles/filedetails/?id=2559257628
