### ISSUE TITLE
[Bug]: Mech high-shield does not intercept mortar rounds

### ISSUE THREAD

**Issue by thunder-zl** [CombatExtended-Continued/CombatExtended#3010]
**Specifications**
Rimworld version: 1.4.3901
Combat Extended version: 1.4.5.6
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 11 Pro Version 22H2 OS build 22621.3155
Your mod list: just CE, CE guns and CE shields
```
<?xml version="1.0" encoding="utf-8"?>
<ModsConfigData>
  <version>1.4.3901 rev238</version>
  <activeMods>
    <li>brrainz.harmony</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
    <li>ceteam.combatextended</li>
    <li>ceteam.combatextendedguns</li>
    <li>n7huntsman.combatextendedshields</li>
  </activeMods>
  <knownExpansions>
    <li>ludeon.rimworld.royalty</li>
    <li>ludeon.rimworld.ideology</li>
    <li>ludeon.rimworld.biotech</li>
  </knownExpansions>
</ModsConfigData>
``` 

**Description**
Mech clusters with Mech High Shield are always being hit with mortars, bypassing the shield.  
~~Don't get me wrong, I hate the damn thing, but it kinda makes mech clusters too easy~~

**Expected behavior**
I expect the shield to intercept mortar rounds

**To reproduce**
Create new colony with 1 pawn, spawn a mech cluster using dev commands, make sure it has the high shield in it (active state).
Spawn 81mm mortar and shoot the shield

**Screenshots & log dumps**
Test setup:
![20240229184150_1](https://github.com/CombatExtended-Continued/CombatExtended/assets/161780708/510cb395-3244-42ee-b78b-1fde51f331c4)
Mortar rounds go through the shield unaffected waking up mechs and dealing damage:
![20240229184248_1](https://github.com/CombatExtended-Continued/CombatExtended/assets/161780708/8433f061-abb2-4c77-9d96-933955d73f0f)
Damaged mechanoid inside the shield zone:
![20240229184305_1](https://github.com/CombatExtended-Continued/CombatExtended/assets/161780708/6222092e-731e-4d3f-b53c-af3daec01c37)

**Complete the following checklist**
I hereby verify that I have done the following:
- [+] Confirmed that my game version and load order are correct.
- [+] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [+] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [+] Disabled Combat Extended and attempted to reproduce the behavior without success.

P.S.
Without CE shells explode at the shield boundary:
![20240229190952_1](https://github.com/CombatExtended-Continued/CombatExtended/assets/161780708/6ec3d2a2-76be-41f9-ae32-fe24e54f0cad)

**Comment by skycrossercat** [comment]
Can confirm this, you can just mortar them to death (high shield in the picture is set to intercept non-hostile).
![螢幕擷取畫面 2024-09-04 115150](https://github.com/user-attachments/assets/49276b6a-b62c-40ee-9682-f019060f8d7a)
