### ISSUE TITLE
[Discussion]: 1.5 RW Update + Anomaly DLC

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#3024]
This issue is to track the changes between the Rimworld 1.4 and 1.5 update and the Anomaly DLC, particularly changes that may require attention for Combat Extended. The full list of changes can be found [here](https://docs.google.com/document/d/e/2PACX-1vSgQmFRFk0FATWTjyZkKRq4oa58sQps4D0kE_uoyKR1y3ZXJT1nIMZSsno7T8cfG-Y6B8lVL3QFnbwQ/pub).

# Core

**Items / Weapons**
- ~~Books: Add appropriate bulk.~~ (Done)
- ~~Schematics: Tie into CE research projects as needed.~~
- ~~Bionic jaw prosthetic: Check for new tools and patch as needed.~~ (No associated tool.)
- ~~New vanilla weapon art.~~
- ~~Added thought for pyros using flame weapons: Make sure CE incendiary weapons are included.~~ (Works as intended)

**Mechanics**
- Crawling: Evaluate behavior in relation to crawling and cover-seeking behavior. Prone targets are also harder to shoot in vanilla, though this should already be reflected in CE mechanics.
- Damage to buildings from fire now scales with their flammability: Ensure all CE structures have appropriate flammability values.

**Rendering**
- Evaluate impact of rendering changes to Combat Extended pawn rendering and hitboxes.
  - Pawn rendering rewritten to parent/child node system. [Technical details here.](https://docs.google.com/document/d/e/2PACX-1vRpvIu49_CpHFMCk-8vLuzIsLqbFFDnf0DNFlYRpwAYXjNlYH6ZudPoox7Gj6K8wuCLPDCWkWEGARrO/pub)
  - Pawn rendering is now multithreaded.

**Technical**
- Added disableImpassableShotOverConfigError: Evaluate how this may affect stuff like CE mortars and the like.
- IsFlesh is now a bool in the race's FleshTypeDef, instead of hardcoded. This will require some changes to CE EMP and Stun handling.
- More control over flecks/motes via XML. New options may be worth exploring for CE systems.

**World**
- Game now supports maps without an associated world tile. Ensure this doesn't cause issues with various CE map interactions (inventory, artillery, etc.)

## Biotech
- ~~Acid spray no longer does damage over time. Ensure this is reflected in CE.~~ (No impact on our patches.)
- Attached turrets on pawns now have a stat entry. Ensure these are correctly populated with CE info.
- MeleeDamageFactor is no longer tied to Biotech.
- ~~Light mechs no longer have "left" and "right" sensors/arms, since they don't have multiples. Ensure this hasn't broken any xml patches.~~ (No impact on our body patches.)

# Anomaly

**XML Work:**
- [x] Ranged attack abilities*
- [x] New creature bodies
- [x] New DamageDefs
- [x] New implants
- [x] New pawnkinds
- [x] New utility packs*
- [x] New scenario
- [x] New weapons
- [x] New apparel
- [x] New creatures
- [x] New resources
- [x] New turrets*
- [x] New mortar shell
- [x] Fleshmass spitter

*awaiting code support

**Coding Work:**
- [x] CE version of vanilla ThingClass: `Projectile_SpawnsThing`
- [x] CE version of vanilla verbClass: `Verb_LaunchProjectileStaticOneUse`
- [x] Support for new `projectileFields`: `spinRate`, `landedEffecter`, `spawnsThingDef`.
- [x] Improvements to `CompProperties_UnderBarrel`
  - [x] Allow underbarrel and primary weapon to share the same magazine.
  - [x] Allow the underbarrel gizmo label to be defined in xml for each specific weapon.
  - [x] Fix underbarrel weapon burst shot count.

**Comment by SamaelGray** [comment]
`      <li Class="CompProperties_Stunnable">
        <affectedDamageDefs>
          <li>Stun</li>
          <li>EMP</li>
        </affectedDamageDefs>
      </li>`

Has been added for turrets as a comp.

**Comment by SamaelGray** [comment]
There is the `renderSkipFlags` node (set to None) for headgear like the Gunlink that is probably going to be useful for CE's NV headgear.

**Comment by DrZHOU32319** [comment]
1.5的bete下载源不见了

**Comment by sumghai** [comment]
@DrZHOU32319, please only use English on this issue tracker here, as most of the collaborators here communicate in English.

The 1.5 beta for Combat Extended can be downloaded from the official Combat Extended Discord Server ( https://discord.gg/safyWuA), but please note that it is for testing purposes only.

**Comment by DrZHOU32319** [comment]
Yes sir！

**Comment by LiteralMushroom** [comment]
The 'The RW 1.5 Development branch can be found here.' link is outdated, it doesn't link you anywhere useful and just gives you this error instead:
![Fix This](https://github.com/CombatExtended-Continued/CombatExtended/assets/79603707/3d3ea29d-f8a9-4d85-a386-3e5ef7509047)

The actual dev branch is '1.5alpha' now, I think.

**Comment by N7Huntsman** [comment]
Everything for 1.5 is now just on the `Development` branch, and you can download a built version from the pinned 'dev build' issue.

**Comment by sentix001** [comment]
when is release planned u think?

thanks for such great work

**Comment by LegitGamer1017** [comment]
> when is release planned u think?
> 
> thanks for such great work

it comes when it comes

**Comment by AluminumAlman** [comment]
> Crawling: Evaluate behavior in relation to crawling and cover-seeking behavior. Prone targets are also harder to shoot in vanilla, though this should already be reflected in CE mechanics.
In vanilla, pawns may only crawl if they are downed, which means that the body proportions when prone are automatically applied to crawling pawns.
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/34545746/dba9f8dd-ac18-4487-9810-298abdfe451b)

**Comment by N7Huntsman** [comment]
**Misc. To Do:**
- Natural Armor Repair Job Improvements.
  - Assign job to Crafting work type.
  - Prevent job doing done while drafted to avoid undesirable behavior (i.e ignoring forbidance).
- New Anomaly bioferrite ammo type.

**Comment by Jan-Blasiak** [comment]
Is BF ammo going to have some special effects like acid burn or psychically lowering consciousness?

Or is it going to be just be AP+?
