### ISSUE TITLE
[Bug]: With Zombieland and Combat Extended both installed, surgery does not remove parts or complete properly

### ISSUE THREAD

**Issue by Tostov** [CombatExtended-Continued/CombatExtended#307]
**Specifications**

Rimworld version: 1.2.2753
Combat Extended version: 3.2
Combat Extended source (Steam, GitHub, etc.):
Your operating system: Windows
Your mod list:
Harmony
Core
Royalty
Hugslib
Zombieland
Combat Extended
**Description**
When harvesting a lung, the operation completes, the game spawns the lung on the ground but the original pawn is left unchanged from this, i.e. they don't lose the lung that was harvested.

On startup of the map, the game throws a null reference error as well

**Expected behavior**
After the surgery completes, the lung should be removed from the pawn, rather than remaining.

**To reproduce**
Load a modlist with combat extended and zombieland. Que up any surgery which removes a body part. The surgery will complete, but the part will not be removed from the operated on pawn's hediffs, though if an item should be spawned when the body part is removed it still will be.

**Screenshots & log dumps**
![294100_20201007152530_1](https://user-images.githubusercontent.com/57082718/95291510-07ebe380-08b3-11eb-8e6a-ce15d0074d7c.png)
Errors appearing on startup

![294100_20201007153639_1](https://user-images.githubusercontent.com/57082718/95291539-13d7a580-08b3-11eb-956a-055fd1762920.png)
Lorean's heart is harvested and on the floor, but she still lives and hasn't even lost her heart in her health tab. The operation is also still qued

![294100_20201007153648_1](https://user-images.githubusercontent.com/57082718/95291569-20f49480-08b3-11eb-8c3d-d3a80657f5ff.png)
Failing the surgery still does damage however

Log here:
https://gist.github.com/HugsLibRecordKeeper/f44a833d44f0d8a7add494acc6586052

May be related to this old issue:
https://github.com/CombatExtendedRWMod/CombatExtended/issues/741

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended. - This appears to be a conflict between zombieland and combat extended
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by LockdownX7** [comment]
Is this still happening in the current version of CE / Zombieland? Haven't been able to reproduce it.

**Comment by Breadbox2k19** [comment]
Seems to have been patched.
