### ISSUE TITLE
[Discussion]: Does enable to input the 2 material effect multiplier value in most appeal item? 

### ISSUE THREAD

**Issue by choi4624** [CombatExtended-Continued/CombatExtended#3077]
**Note: These are to be used for discussions related to Combat Extended, primarily by team members and other contributors. Not for feedback, requests, etc. Off-topic chatter will be deleted.**
 
Modded hemlet (as example Miho, the celetial fox) using variant material. plasteel & ceramic & 1 other metal 
![2024-04-11_161349](https://github.com/CombatExtended-Continued/CombatExtended/assets/23658398/58d6bf64-b27a-47ba-8e94-422137377f82)
But adjust RHA value is only affected by 'metal' instead. Patch apply manually base 4mm RHA to setting. But most of non(or old) patched appeals have bad works in defend. 

![2024-04-11_162935](https://github.com/CombatExtended-Continued/CombatExtended/assets/23658398/89d2ec0d-df74-43fd-b234-945b4e72d936)
![2024-04-11_162926](https://github.com/CombatExtended-Continued/CombatExtended/assets/23658398/a5d1148f-06c6-4889-8a71-e43b90082076)

In normal rimworld system, there is only 1 major source allowed to setting appeals defend. This is no problem in normal battle system. Trumbo shirts is always good item even using marine armor.  

But combat extended has high difference in fiber & non-fiber materials. And mixed source armor need manual patch.(Most modded item miss to treat this is armor or clothes or others) 
Does it have to change the 2 or more materials apply toughness in making appeals? 

May be this is an example 

![2024-04-11_163221](https://github.com/CombatExtended-Continued/CombatExtended/assets/23658398/a6c0f582-deb6-4396-8c1d-488dca914d07)
Fabric has 50% of multiplier in 1st material. And steel has 50% multiplier as 2nd material. 

May be XML apply change like this. Sorry I can't find how to setting the Multiplier in C# file. 
please show the "**" area 

```XML
<!-- ========== HeavyShield_Big =========== -->
				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="RK_HeavyShield_Big"]/statBases/StuffEffectMultiplierArmor</xpath>
					<value>
						**<StuffEffectMultiplierArmor>5</StuffEffectMultiplierArmor>** 
// this is total Multiplier of main & sub materials value 
						**<StuffEffectmajor>0.7</StuffEffectmajor>**						
                                               **<StuffEffectminor>0.3</StuffEffectmajor>**
// If the value does not contain this. major is 70% of Effect and minor is 30% effect. If sub material is not existed, only Effect major 100% effect multiplier. 
					</value>
				</li>

  // Base value is always allowed 
				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="RK_HeavyShield_Big"]/statBases/ArmorRating_Sharp</xpath>
					<value>
						<ArmorRating_Sharp>2</ArmorRating_Sharp>
					</value>
				</li>
				<li Class="PatchOperationReplace">
					<xpath>Defs/ThingDef[defName="RK_HeavyShield_Big"]/statBases/ArmorRating_Blunt</xpath>
					<value>
						<ArmorRating_Blunt>3</ArmorRating_Blunt>
					</value>
				</li>

```
```XML
<Operation Class="PatchOperationAdd">
		<xpath>Defs/ThingDef[@Name="OA_RK_ApparelBase"]/statBases</xpath>
		<value>
			<Bulk>1</Bulk>
			<WornBulk>0.7</WornBulk>
		</value>
	</Operation>

	<Operation Class="PatchOperationAdd">
		<xpath>Defs/ThingDef[@Name="OA_RK_ApparelBase"]/statBases</xpath>
		<value>
						**<StuffEffectMultiplierArmor>10</StuffEffectMultiplierArmor>** 
// This is total Multiplier of main & sub materials value 
						**<StuffEffectmajor>0.7</StuffEffectmajor>**						
                                               **<StuffEffectminor>0.3</StuffEffectmajor>**
                                               **<StuffEffectMultiplierArmorAlter>5</StuffEffectMultiplierArmorAlter>** 
// This is modded Apparel no more use 2 or more materials Multiplier like normal clothes, half the multiplier maximum as 5. 

		</value>
	</Operation>


  // If this is works properly, does not need to setting default value. 
	<Operation Class="PatchOperationAdd">
		<xpath>Defs/ThingDef[@Name="OA_RK_ApparelBase"]/statBases</xpath>
		<value>
			<ArmorRating_Blunt>2</ArmorRating_Blunt>
		</value>
	</Operation>
	<Operation Class="PatchOperationAdd">
		<xpath>Defs/ThingDef[@Name="OA_RK_ApparelBase"]/statBases</xpath>
		<value>
			<ArmorRating_Sharp>3</ArmorRating_Sharp>
		</value>
	</Operation>
```

Thanks for reading. sincerely.

**Comment by N7Huntsman** [comment]
@choi4624 

Hello. Sorry for the long delay in answering you, I read this when you first posted, but forgot to reply.

While what you are suggesting is potentially interesting, is would be a broad overhaul of Rimworld's crafting system, which currently only supports a single "stuff" material that the apparel is made of. This would be a big undertaking and is outside the scope of Combat Extended, and so we unfortunately cannot consider it.
