### ISSUE TITLE
[Feedback:] Nerf the range/accuracy of the Spiner gun for the War Urchin

### ISSUE THREAD

**Issue by Keerp96** [CombatExtended-Continued/CombatExtended#3084]
The more than doubled range of the spiner from the 6.9 of the vanilla game seems too much for such an early enemy, given how relatively powerful it is. War urchins seem to spawn in the first few raids already and can headshot defenders from max range even behind sandbags. Even one of these is a deadly challenge for a fresh colony.

**Comment by SamaelGray** [comment]
War Urchins are spawned by the War Queen which is a *boss mechanoid*, the player has to be prepared for it.

**Comment by Keerp96** [comment]
> War Urchins are spawned by the War Queen which is a _boss mechanoid_, the player has to be prepared for it.

Ok then this might be an issue with my setup, because they are arriving as a raid alongside a regular human, no other mechanoids in sight.
