### ISSUE TITLE
[Bug]: Starting ghoul cannot fight

### ISSUE THREAD

**Issue by Merlin-Guyard** [CombatExtended-Continued/CombatExtended#3087]
Rimworld version: 1.5.4063 64bit
Combat Extended version: Latest Development Snapshot
Combat Extended source (Steam, GitHub, etc.): Github (https://combatextended.lp-programming.com/CombatExtended-latest.zip)
From the checklist "and required compatibility patches." : I double checked and never got asked to install a patch. If I missed it, this might be the cause of the bug ?

Your operating system: windows 11

Your mod list: 
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/79550735/145c2d36-80c4-4f29-8026-dcd569158e9e)

**Description**
When drafting a ghoul and ordering it to attack any kind of creature, it'll miss all attacks. Sometimes it'll even just walk close to the creature targated and simply wait.
The attack will be shown as dodged and will still appear in the characters's logs.

**Expected behavior**
In vanilla, without CE, the ghoul's hit are registered with an injury and won't always be dodged.

**To reproduce**
Create a new colony with the latest Anomaly scenario.
Skip every part of the creation as it doesn't impact the bug.
Land on the planet and draft the ghoul.
Order it to attack a critter or a colonist.

**Screenshots & log dumps**
No crashes logs.

![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/79550735/648146c9-baf9-49bb-a68c-915c2e3eb883)
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/79550735/899f7cd8-935c-427b-a008-831b46de3816)

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Anomaly has not yet been made compatible, and this is expected behavior from an unpatched creature. The patch is currently being worked on.
