### ISSUE TITLE
[Bug]: XML Errors

### ISSUE THREAD

**Issue by Dezard767** [CombatExtended-Continued/CombatExtended#3103]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Mod won't load, gives a lot of errors

Rimworld version: 1.5.4069
Combat Extended version: 15.6.0.0
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows 10
Your mod list: Only Harmony

**Description**
I only include CE+Harmony with the DLC in Rimworld. After downloading, all mods be disabled, only DLC remain and a console appear with hundreds of red errors.

**Expected behavior**
What did you expect to happen?

**To reproduce**
Enable the mod as usual

**Screenshots & log dumps**
![Знімок екрана 2024-04-23 143723](https://github.com/CombatExtended-Continued/CombatExtended/assets/140973393/55b8b39e-12c4-419c-b021-b9a4cd794cf1)
![Знімок екрана 2024-04-23 143739](https://github.com/CombatExtended-Continued/CombatExtended/assets/140973393/8c5274b5-6a8b-4bb3-a8a4-8651620a9fa3)
Logs is too big for upload on patebin. I will post the initial part of the logs, the rest of the text there is similar
https://pastebin.com/nCxzTXQh

**Complete the following checklist*
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Verify your local copy of Rimworld and see if that changes anything.

**Comment by N7Huntsman** [comment]
Haven't gotten a response, so I can only assume that was the problem. Closing this issue.
