### ISSUE TITLE
[Bug]: Raids/allies have no bullets in ranged weapons.

### ISSUE THREAD

**Issue by Blublu322** [CombatExtended-Continued/CombatExtended#3107]
**Specifications**

Rimworld version: 1.5.4069
Combat Extended version: 15.6.0.0
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows 10
Your mod list: Harmony

**Description**
Sorry if this is already a well known issue: Raids, allied help, basically any pawns that spawn in the map will not have bullets loaded in their weapons. 

They do not have the required munitions in their inventory either, with the exception of heavy weapons that would have required, in normal CE behavior, extra munitions in their inventory- like LMG. 

As a result, without bullets in their guns, they promptly switch to melee weapons if available. Unless, they usually come with extra bullets in their inventory, like LMG loadouts, in which case they do load the extra bullets and are able to shoot their gun.

Of course, spawned pawn loadouts with the new Hellcat rifle still works like vanilla, requiring no bullets to fire, but that's not the issue.

**Expected behavior**
In normal CE behavior, raid/ally pawns already have munitions loaded into their guns, and are able to fire those guns.

**To reproduce**
Start any game, normally or via 'Dev quicktest'.

Wait for a raid or trigger a raid with dev mode.

Notice they will not fire their guns because they don't come with bullets.

**Screenshots & log dumps**
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/168139935/41724824-8acb-40ef-b15c-2a2ed90a6aae)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Rhinous** [comment]
This is because 1.5 changed the order in which gear is generated so when CE goes to give ammo the primary weapon hasn't generated yet
1.5 Version
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/66878914/81d48c5c-c7dc-4714-9850-b1d66d2c5615)

Old 1.4 Version
![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/66878914/d0635698-528e-405d-bdc7-8cecd9b5fad8)
