### ISSUE TITLE
[Patch Request]: Rimsenal - Spacer Faction Pack Patch Update

### ISSUE THREAD

**Issue by ewyncliffe** [CombatExtended-Continued/CombatExtended#3118]
Rimsenal Spacer Faction Pack

(https://steamcommunity.com/sharedfiles/filedetails/?id=3086137468)

**Description:**
Two combat mechs added. Patch will need updating.

**Content:**
Skutaton: Heavily armored blunt-specialized melee mech

Bombito: suicide bomber mech designed to be used en-masse. 

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by SamaelGray** [comment]
Already patched in https://github.com/CombatExtended-Continued/CombatExtended/pull/3120
