### ISSUE TITLE
[Bug]: Indirect Airburst shell isue

### ISSUE THREAD

**Issue by Tostov** [CombatExtended-Continued/CombatExtended#3126]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:  1.4.3901
Combat Extended version: 1.4.5.8
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 11
Your mod list:
brrainz.harmony
ludeon.rimworld
ludeon.rimworld.royalty
ludeon.rimworld.ideology
ludeon.rimworld.biotech
ceteam.combatextended_steam
**Description**
Provide a concise description of the issue or concern. What happened?
Airburst effects are offset from intended impact point by a variable amount, or intermittently do not appear
**Expected behavior**
What did you expect to happen?
Airburst fragmentation and smoke is generated at the same visual position as the shell in flight when detonating, and hits intended effect area.
**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Start a new devmode game, enable god mode, place a mortar and binoculars. Target a pawn or building with the binoculars to mark it then generate a loaded airburst shell into the mortar.
Target the marked item with the mortar and the shell should travel directly towards it, however upon detonation the actual blast will generate elsewhere.
**Screenshots & log dumps**
![Screenshot 2024-05-10 024113](https://github.com/CombatExtended-Continued/CombatExtended/assets/57082718/091a8cd6-f6a0-4cb3-9cec-f078fd3e352b)
![Screenshot 2024-05-10 024117](https://github.com/CombatExtended-Continued/CombatExtended/assets/57082718/4c900cbb-ea31-4047-b563-046d99f4cd4a)

Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by yuganxia** [comment]
The bug  should be in Source/CombatExtended/CombatExtended/Projectiles/ProjectileCE_HeightFuse.cs HeightFuseAirBurst() (I think). 
If remove the <aimHeightOffset>, the SW offset will gone, and sometimes shell will disapear.
