### ISSUE TITLE
[Patch Request]: Vehicle Framework not working anymore at all

### ISSUE THREAD

**Issue by theoretischer** [CombatExtended-Continued/CombatExtended#3129]
**Description:**
I updated CE today, and suddenly it stopped working with Vehicle Framework. Pawns can't move and you get a ton of errors

I only used VF, CE, hugslib, harmony and all dlcs.

**Comment by SamaelGray** [comment]
For the 1.5 version of CE, you need this https://github.com/CombatExtended-Continued/CombatExtended/pull/3122 otherwise the dev snapshot/1.5 beta is not going to work. The 1.4 version on steam works as intended.

**Comment by theoretischer** [comment]
Oh I see, thanks
