### ISSUE TITLE
[Bug]: Arrows can fly over walls and through roofs and hit pawns through solid objects.

### ISSUE THREAD

**Issue by crius-al** [CombatExtended-Continued/CombatExtended#314]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: Arrows can fly over walls and through roofs and hit pawns through solid objects.

**Specifications**
Please provide the following.

Rimworld version: 1.2.2753
Combat Extended version: 3.2 (Latest) as of maybe a day or two ago.
Combat Extended source (Steam, GitHub, etc.): I downloaded it directly from this github.
Your operating system: Windows 10
Your mod list: https://gist.github.com/HugsLibRecordKeeper/cf1604ce574080fc524bc870f8b6fc85

**Description**
I had a pawn shooting at some bulls through an embrasure with arrows. The pawn missed, and hit another pawn who is out of line of sight, and sleeping inside the base. There is a roof and solid wall in the way, but the arrow went through one or the other to hit the pawn in the head. Perhaps line of sight rules should apply to missed projectiles too?

**Expected behavior**
The roof or the wall would have stopped the arrow.

**To reproduce**
Have a pawn shooting arrows at a different creature with a wall/roof structure near by, and the arrows may hit things protected by the roof and wall combo even though line of sight is false.

**Screenshots & log dumps**
https://imgur.com/a/1I8IqQg

**Complete the following checklist**
I hereby verify that I have done the following:
- [ ] Confirmed that my game version and load order are correct.
- [ ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Alicecomma** [comment]
I wonder if the apparent pawn height (say 1.8f, unchanged during sleeping) is added to bed height (say 1f) so the pawn's head seems to be above the roof height (2.8f > ~2-2.5f).
