### ISSUE TITLE
[Bug]: Combat Extended VFE - Deserters patch removes charge sniper rifle from CE Guns

### ISSUE THREAD

**Issue by makentake** [CombatExtended-Continued/CombatExtended#3250]
**Specifications**
Rimworld version: 1.5.4104
Combat Extended version: 15.6.0.0 (Development snapshot from July 4th)
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Windows 10
Your mod list:
Harmony [brrainz.harmony][https://github.com/pardeike/HarmonyRimWorld]
RimWorld [ludeon.rimworld][https://store.steampowered.com/app/294100/RimWorld]
RimWorld - Royalty [ludeon.rimworld.royalty][https://store.steampowered.com/app/1149640/RimWorld__Royalty]
RimWorld - Ideology [ludeon.rimworld.ideology][https://store.steampowered.com/app/1392840/RimWorld__Ideology]
RimWorld - Biotech [ludeon.rimworld.biotech][https://store.steampowered.com/app/1826140/RimWorld__Biotech]
RimWorld - Anomaly [ludeon.rimworld.anomaly][https://store.steampowered.com/app/2380740/RimWorld__Anomaly/]
Cherry Picker [owlchemist.cherrypicker.tmpfix][https://github.com/Owlchemist/cherry-picker]
Vanilla Expanded Framework [oskarpotocki.vanillafactionsexpanded.core][https://steamcommunity.com/sharedfiles/filedetails/?id=2023507013]
Vanilla Factions Expanded - Empire [oskarpotocki.vfe.empire][https://steamcommunity.com/sharedfiles/filedetails/?id=2938820380]
Vanilla Factions Expanded - Deserters [oskarpotocki.vfe.deserters][https://steamcommunity.com/sharedfiles/filedetails/?id=3025493377]
Combat Extended [ceteam.combatextended][https://github.com/CombatExtended-Continued/CombatExtended]
Combat Extended Guns [ceteam.combatextendedguns][https://github.com/CombatExtended-Continued/CombatExtendedGuns]

**Description**
The VFE - Deserters patch in CE erroneously removes the charge sniper rifle (CE_Guns_ChargeSniperRifle) from the game when loaded together with CE Guns and dependencies. This seems to be due to an incorrect patch operation when attempting to add it to the contraband market from Deserters.

**Expected behavior**
The gun not being removed.

**To reproduce**
1. Load VFE - Deserters, CE Guns, and their dependencies.
2. Run the game.
3. Observe that the charge sniper rifle is not present in the research tree (Cherry Picker also fails to pick up the def).

**Screenshots & log dumps**
No errors show up in the log. However, I think I found the issue in the patch.

In the file Contraband.xml (found in _CombatExtended\ModPatches\Vanilla Factions Expanded - Deserters\Patches\Vanilla Factions Expanded - Deserters_) at line 48, it attempts to run a PatchOperationReplace on the rifle's def while only passing in a mod extention as the value, presumably stripping the def of all its essential information. Replacing this with PatchOperationAddModExtention fixes the issue in my testing.

![image](https://github.com/CombatExtended-Continued/CombatExtended/assets/110845323/0d4f8f16-c57c-4353-a088-88341f93919a)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success. _(Since CE Guns depends on CE, this isn't possible)_

**Comment by N7Huntsman** [comment]
Fixed by #3267.
