### ISSUE TITLE
[Bug]: Error loading SOS2 torpedoes

### ISSUE THREAD

**Issue by Trillion44** [CombatExtended-Continued/CombatExtended#3256]
[Bug]: Error loading SOS2 torpedoes

Rimworld version:
Combat Extended version: 15.6.0.0
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: MacOS Sonoma 14.5
Your mod list:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Ideology
  - Ludeon.RimWorld.Biotech
  - UnlimitedHugs.HugsLib
  - CETeam.CombatExtended
  - SmashPhil.VehicleFramework
  - kentington.saveourship2

**Description**
Provide a concise description of the issue or concern. What happened?
- Error log is immediately displayed in-game when there is an SOS2 torpedo launcher with nearby torpedo to load
- Selecting a pawn and then right-clicking on the Torpedo Launcher has no effect in the UI

Error message includes:
Exception in BreadthFirstTraverse: System.TypeLoadException: Could not resolve type with token 010001b2 (from typeref, class/assembly RimWorld.Building_ShipTurret, ShipsHaveInsides, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)
[Ref 25D4E3EA]
 at SaveOurShip2.WorkGiver_LoadTorpedoTube.FindAmmo (Verse.Pawn pawn, SaveOurShip2.Building_ShipTurretTorpedo tube) [0x00086] in <2df847f03d034e0fa0612e7c7e88a026>:0 
     - POSTFIX CombatExtended.HarmonyCE: Void CombatExtended.HarmonyCE.Compatibility.Harmony_Compatibility_SaveOurShip:Postfix(Pawn pawn, Building_Turret tube, Thing& __result)

**Expected behavior**
What did you expect to happen?
- Pawns who are hauling should automatically load the Torpedo Launcher, or a selected pawn should be able to prioritize loading via a right-click on the Launcher

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
- Create minimal mod list above
- Create new colony
- Use dev mod to create a *powered* tiny SOS2 ship with a Torpedo Launcher (6) and a nearby torpedo
- Select a pawn and right-click the Torpedo launcher
- See errors in Player.log file

Optional:
- Save Colony
- Remove CE from mod List, and restart game
- Select a pawn, right-click on Launcher, and successfully load the torpedo

**Screenshots & log dumps**
- Player.log: https://pastebin.com/gGxZ4UPV

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by SaltyKarl** [comment]
is fixed in https://github.com/CombatExtended-Continued/CombatExtended/pull/3182

**Comment by Trillion44** [comment]
Confirmed. Thanks for the quick fix!!!
