### ISSUE TITLE
[Patch Request]: Ancient Armory (& Ancient Armory for Ancients)

### ISSUE THREAD

**Issue by Darknote** [CombatExtended-Continued/CombatExtended#3273]
[Patch Request]: Ancient Armory (& Ancient Armory for Ancients?)

Ancient Armory: https://steamcommunity.com/sharedfiles/filedetails/?id=2972831749

Ancient Armory for Ancients: 
https://steamcommunity.com/sharedfiles/filedetails/?id=3039014779

**Description:**
The mod adds ancient weapons and armour that complements Medieval Overhaul quite nicely and adds to the mystery of the world by replacing the Ancient Ruins marines with soldiers in medieval armour with swords and bows.

**Content:**
What does the new mod contain? Check all that apply.
- [X] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [X] New armor or apparel.

I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
A third party patch exists on the workshop.
