### ISSUE TITLE
[Bug] Localization Key is missing

### ISSUE THREAD

**Issue by tinygrox** [CombatExtended-Continued/CombatExtended#3305]
### these need to be localized:
https://github.com/CombatExtended-Continued/CombatExtended/blob/5ff405a4c92208d7f0e63a58a55e4316a33f77b4/Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs#L848-L852

https://github.com/CombatExtended-Continued/CombatExtended/blob/5ff405a4c92208d7f0e63a58a55e4316a33f77b4/Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs#L854-L862

https://github.com/CombatExtended-Continued/CombatExtended/blob/5ff405a4c92208d7f0e63a58a55e4316a33f77b4/Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs#L864-L872

https://github.com/CombatExtended-Continued/CombatExtended/blob/5ff405a4c92208d7f0e63a58a55e4316a33f77b4/Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs#L890-L894

https://github.com/CombatExtended-Continued/CombatExtended/blob/5ff405a4c92208d7f0e63a58a55e4316a33f77b4/Source/CombatExtended/CombatExtended/Verbs/Verb_LaunchProjectileCE.cs#L900-L916

**Comment by N7Huntsman** [comment]
@tinygrox I have opened #3363 to add translation keys for the lines you've pointed out. Please let me know if you come across any others that need addressed.

**Comment by tinygrox** [comment]
@N7Huntsman sry for the late response! I've been caught up playing Black Myth: Wukong lately and didn't check GitHub.
Here are some other lines that need translation:

https://github.com/CombatExtended-Continued/CombatExtended/blob/88d45a3c792b2dd02068d0aa8e643dc018474bdf/Source/CombatExtended/CombatExtended/Comps/CompFireModes.cs#L322

https://github.com/CombatExtended-Continued/CombatExtended/blob/88d45a3c792b2dd02068d0aa8e643dc018474bdf/Source/CombatExtended/CombatExtended/Comps/CompMeleeTargettingGizmo.cs#L171

https://github.com/CombatExtended-Continued/CombatExtended/blob/88d45a3c792b2dd02068d0aa8e643dc018474bdf/Source/CombatExtended/CombatExtended/StatWorkers/StatWorker_ArmorPartial.cs#L234

When you come across lines that involve parameters, it's better to use methods with parameters for localization. For example:

```C#
"Shooting disallowed by " + current.LabelShort;
```

Instead of:

```C#
"CE_BlockedShield".Translate() + current.LabelShort;
```

It would be better to use:

```C#
"CE_BlockedShield".Translate(current.LabelShort);
```

This allows translators to have more flexibility in their translations.
