### ISSUE TITLE
[Bug]: Plasma turrets from SOS2 not working and create massive lag

### ISSUE THREAD

**Issue by Tilaxx** [CombatExtended-Continued/CombatExtended#3369]
**Specifications**
Please provide the following.

Rimworld version: 1.5,4101 rev435
Combat Extended version: 15.6.0.0
Combat Extended source: Steam
SOS2 version: 
SOS2 source: Steam
Your operating system: Windows 11
Your mod list:  Can provide collection (size 151) on request

**Description**
Plasma turret attached to an SOS2 ship on the ground doesn't work and massively lags the game. From 500tps to ~40.

Had to reload to a previous save because the shots seemed to be buffered.

**Expected behavior**
For the plasma turret to fire with minimal performance impact.

**To reproduce**
Build a minimal SOS2 ship in dev mode. I tried with a square of ship hull containing a ship reactor, capacitor array, heatsink and coolant tank surrounded by powered ship hull (touching). Outside I mounted a single Plasma turret on an XL hard point. Firing worked as expected when CE wasn't included, but didn't work and sunk tps when CE was loaded.

**Screenshots & log dumps**

Log from game:
```Exception ticking ShipTurret_Plasma11441 (at (132, 0, 142)): System.InvalidCastException: Specified cast is not valid.
[Ref 70291874] Duplicate stacktrace, see ref for original
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Log.Error_Patch3 (string)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickList.Tick_Patch1 (Verse.TickList)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.TickManager.DoSingleTick_Patch5 (Verse.TickManager)
Verse.TickManager:TickManagerUpdate ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Game.UpdatePlay_Patch6 (Verse.Game)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Play.Update_Patch2 (Verse.Root_Play)
```

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
    (Checked SOS2 load order and then used rimpy autosort)
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Known issue with the Steam release. An updated patch is in the dev build.
