### ISSUE TITLE
[Patch Request]: Vanilla Weapons Expanded - Bioferrite

### ISSUE THREAD

**Issue by Draconomial** [CombatExtended-Continued/CombatExtended#3405]
**Mod name:** Vanilla Weapons Expanded - Bioferrite

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=3287469135

**Description:**
These 6 weapons will have unique, triggerable abilities that consume bioferrite charges. Without adding too much bloat, this mod allows you to unlock 6 unique, useful guns as long as you have bioferrite to sustain them.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by N7Huntsman** [comment]
Closed by #3409
