### ISSUE TITLE
[Patch Request]: Alpha Animals

### ISSUE THREAD

**Issue by Ashnal** [CombatExtended-Continued/CombatExtended#341]
**Mod name:**
Alpha Animals

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=1541721856

**Description:**
Missing CE values for AA_RayHound which I observed in game when trying to read the info. I'm guessing that the included compatibility patch hasn't been updated. AA_AngelMoth also is missing a patch. I'm guessing that everything added in the August 26th update may be missing patches.

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by LeriWeill** [comment]
I'm commenting here to not open a new issue, but there have been 5 new additions today to Alpha Animals!

**Comment by Breadbox2k19** [comment]
I've already finished updating it on my end, I'll upload it at a later date.
