### ISSUE TITLE
[Bug]: incompatibility with medieval overhaul

### ISSUE THREAD

**Issue by ErrDri0x7b** [CombatExtended-Continued/CombatExtended#3436]
[Bug]: incompatibility with medieval overhaul

Rimworld version: 1.5.4104
Combat Extended version: 15.6.0.0
Combat Extended source (Steam, GitHub, etc.): building mods with top-mods.ru
Your operating system: Windows 10 LTSC
Your mod list:
[modlist.txt](https://github.com/user-attachments/files/17081881/modlist.txt)

There was a working build to which medieval overhaul was added. Then it started. I don't know much about the priority of loading rimworld mods. Therefore, I randomly rearranged these two mods, but there were even more mistakes. Logs and modlist are attached.

debug log:
https://gist.github.com/HugsLibRecordKeeper/83594f15a4a87cb1863850de7fe51a50

I hereby verify that I have done the following:
- [+] Confirmed that my game version and load order are correct.
- [+] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [+] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [+] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by ViralReaction** [comment]
No incompatibility, CE was from outdated source.
