### ISSUE TITLE
[Bug]: Alpha Animals - "Behemoth" gear tab not showing items and causing errors

### ISSUE THREAD

**Issue by Orin55** [CombatExtended-Continued/CombatExtended#3492]
Version: Rimworld 1.5.4243 rev947 + Biotech + Ideology
Combat Extended version:  1.5.1.0
Combat Extended source: Steam
Operating system: Windows 10 22h2
Mod list(sorted with RimPy): https://i.imgur.com/YjPHOUB.png

The alpha animals mod has a pack animal called Behemoth. When checking its gear tab to see what it's carrying, the tab is blank and throws errors on the console.
Other animals gear tab correctly shows the animal inventory. From my tests, this is exclusive to the behemoth.

To reproduce, load the game with only Combat Extended and Alpha Animals(plus dependencies);
Spawn and tame a behemoth using dev mode;
Assemble a caravan with the behemoth, a colonist and any item;
After the colonist load the items to the animal, select the behemoth and check the gear tab, it will be empty and errors will show up.

The tab works normally if I remove the Combat Extended mod.

Logs(Line 1961): https://gist.github.com/HugsLibRecordKeeper/aae6e794a0152000440645bee7ccedd3
Some screenshots:
![image](https://github.com/user-attachments/assets/5536a4d5-0792-456b-941b-f8765935b44e)
![image](https://github.com/user-attachments/assets/033da787-3552-4d0d-86bf-ae20aebf62d3)
![image](https://github.com/user-attachments/assets/a35957d0-2251-4a01-9d22-26238752e385)

**Comment by JackofAllWorlds** [comment]
Same issue - with elephants / Indian elephants. The conflict with my list is Vanilla Animals Expanded.

**Comment by N7Huntsman** [comment]
This should have been resolved by #3479.

**Comment by JackofAllWorlds** [comment]
It is not resolved in my current playthrough, unless this build isn't the most recent one pushed to Steam. I have tried to manually force the mod update through Steam in case it hadn't downloaded, and it didn't show an update. I think these issues started for me almost exactly 2 weeks ago which is when this update apparently issued.

**Comment by mszabo-wikia** [comment]
> It is not resolved in my current playthrough, unless this build isn't the most recent one pushed to Steam. I have tried to manually force the mod update through Steam in case it hadn't downloaded, and it didn't show an update. I think these issues started for me almost exactly 2 weeks ago which is when this update apparently issued.

@JackofAllWorlds Yeah, the fix isn't yet part of a release and so not on Steam either. You can grab the dev build from the link in the README in the interim.
