### ISSUE TITLE
[Patch Request]: Genetic Rim

### ISSUE THREAD

**Issue by Lion-ion** [CombatExtended-Continued/CombatExtended#350]
**Mod name:** Genetic Rim

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=1113137502

**Description:**
InsectHybridsCE.xml fails to patch for the current versions of Genetic Rim and CE. Upon inspection Genetic Rim added a few more entries like Thrumbospider in the past couple months.

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by Breadbox2k19** [comment]
Can you leave more details on why doesn't it work? I'm 100% sure that Thrumbospider has being patched.

**Comment by Lion-ion** [comment]
It seems to fail specifically when CE is also trying to patch for Alpha Animals.

**Comment by Breadbox2k19** [comment]
> It seems to fail specifically when CE is also trying to patch for Alpha Animals.

If you have the error log please paste them here, I made the patch for genetic rim but hasn't been using it recently. I'm not aware of any Genetic rim interaction with alpha animal unless you are also using the genetic rim alpha animal hybrid mod(it is patched and also done by myself).
Are you using that?

**Comment by ussdefiant60** [comment]
I certainly use GR + AA + that hybrid patch myself and get an error in InsectHybridsCE.xml. I also have a couple of Mantistanis things in my base from a quest that throw No Support for Combat Extended errors when i open the info page on it.

Logs be here: [](https://gist.github.com/HugsLibRecordKeeper/e026ae61706f338fe66e1c38e47f8184)

**Comment by Breadbox2k19** [comment]
> I certainly use GR + AA + that hybrid patch myself and get an error in InsectHybridsCE.xml. I also have a couple of Mantistanis things in my base from a quest that throw No Support for Combat Extended errors when i open the info page on it.
> 
> [Logs be here:](https://gist.github.com/HugsLibRecordKeeper/e026ae61706f338fe66e1c38e47f8184)

Please do not send me the whole log, only copy paste the ones highlighted in red in the error log please.

**Comment by Pandemic223** [comment]
I suppose ill throw my hat in the ring here. I am running Combat Extended with Genetic Rim and Alpha Animals. When loading up the game, an error is thrown in console. Below will be the specific error. 

[Combat Extended] Patch operation Verse.PatchOperationFindMod(Genetic Rim) failed
file: F:\SteamLibrary\steamapps\workshop\content\294100\1631756268\Patches\Genetic Rim\GeneticRim_Races_CE\Races_Animal_InsectoidhybridsCE.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()
