### ISSUE TITLE
[Bug]:The overall security is not displayed

### ISSUE THREAD

**Issue by paparil** [CombatExtended-Continued/CombatExtended#3503]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:
Combat Extended version: 1.5.4243
Combat Extended source (Steam, GitHub, etc.):september 24 workshop upload
Your operating system: win 11
Your mod list: Harmony, Combat Extended

**Description**
Provide a concise description of the issue or concern. What happened?
at one point, the general security stopped being displayed, reinstalling the game, mods did not help.
**Expected behavior**
What did you expect to happen?
working display of general security
**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

To be honest, I don't know, but I hope you can help me.
![Снимок экрана (7)](https://github.com/user-attachments/assets/b6ed373b-1669-47b0-b45e-f91438bf6138)

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [✓] Confirmed that my game version and load order are correct.
- [✓] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [✓] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Known issue.
