### ISSUE TITLE
[Bug]: Cannot view caravan gear of some animals

### ISSUE THREAD

**Issue by JackofAllWorlds** [CombatExtended-Continued/CombatExtended#3504]
Rimworld version: 1.5.4243 rev947
Combat Extended version: v1.5.6.1.0
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10

![image_2024-10-24_181543170](https://github.com/user-attachments/assets/417305ce-4d9b-41c1-a8fc-2e9be4bd28a0)

Your mod list:

(from log)
Loading game from file AA Current with mods:
  - brrainz.harmony
  - Ludeon.RimWorld
  - Ludeon.RimWorld.Ideology
  - Telkir.TMods.MoreFloors
  - Ludeon.RimWorld.Biotech
  - RedMattis.BetterGeneInheritance
  - LimeTreeSnake.Systems
  - LimeTreeSnake.Maintenance
  - UnlimitedHugs.HugsLib
  - Mlie.SYREssentialsStone
  - OskarPotocki.VanillaFactionsExpanded.Core
  - VanillaExpanded.VWE
  - CETeam.CombatExtended
  - Oblitus.AnimalsLogic
  - Doug.NoJobAuthors
  - Mlie.AutopsyTable
  - BerryRagepyre.PrisonerRecreation
  - GodlyAnnihilator.AnimalMedicalBed
  - ISOREX.PawnEditor
  - Mlie.SpreadTheWord
  - avilmask.CommonSense
  - ReSplice.XOTR.Core
  - velc.MineItAll
  - kittahkhan.grazeup
  - Mlie.PrisonersDontHaveKeys
  - Wall.Light.Relic
  - overpl.AnimalSarcophagus
  - automatic.prisonerbedsetowner
  - Woolstrand.RealRuins
  - telardo.DragSelect
  - Albion.GoExplore
  - Sl4vP0weR.WeAreUnited
  - Katavrik.CrashLanding
  - Jaxe.Bubbles
  - Mlie.RimQuest
  - roolo.runandgun
  - VanillaExpanded.VanillaBackstoriesExpanded
  - m00nl1ght.MapPreview
  - Ogliss.TheWhiteCrayon.Quarry
  - Murmur.WallLight
  - Uuugggg.ReplaceStuff
  - VanillaExpanded.Ideo.RelicsAndArtifacts
  - VanillaExpanded.VCEF
  - VanillaExpanded.VIESAS
  - VanillaExpanded.VWENL
  - VanillaExpanded.Ideo.IconsandSymbols
  - VanillaExpanded.VBooksE
  - VanillaExpanded.VMemesE
  - Haplo.Miscellaneous.Training
  - VanillaExpanded.VAEEndAndExt
  - VanillaExpanded.VanillaAnimalsExpanded
  - VanillaExpanded.VWEHW
  - VanillaExpanded.VanillaTraitsExpanded
  - VanillaExpanded.VFECore
  - VanillaExpanded.VFEProduction
  - VanillaExpanded.VTEXVariations
  - VanillaExpanded.VTEXE
  - VanillaExpanded.VanillaSocialInteractionsExpanded
  - VanillaExpanded.VPlantsE
  - VanillaExpanded.VEE
  - VanillaExpanded.VFEArt
  - VanillaExpanded.VHE
  - VanillaExpanded.VFEPropsandDecor
  - VanillaExpanded.VFEFarming
  - Mlie.SimplyMoreBridges
  - sarg.rimbees
  - bs.xenotypespawncontrol (incompatible version)
  - spoonshortage.ADogSaidAnimalProsthetics
  - VanillaExpanded.VAPPE
  - VanillaExpanded.VARME
  - MemeGoddess.SearchAndDestroy

**Description**
Elephants return from caravan with gear, but when you click on the gear tab no gear is visible.

**Expected behavior**
What did you expect to happen? To be able to view the gear.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
This started in this playthrough right about 2 weeks ago. No idea how to replicate it outside this game except to test under identical conditions and send elephants on a caravan.

**Screenshots & log dumps**
Screenshot uploaded.
Full log: https://gist.github.com/HugsLibRecordKeeper/4f67a0430c70e8df6e491caab1bb9732

Possible pertinent portion of player.log:

Exception filling tab CombatExtended.ITab_Inventory: System.NullReferenceException: Object reference not set to an instance of an object
[Ref 47A3AA4F]
 at Verse.GenCollection.FirstOrDefault[T] (System.Collections.Generic.List`1[T] list, System.Predicate`1[T] predicate) [0x00000] in <2a40c3593b334f29ac3cb3d32d652351>:0 
 at CombatExtended.ITab_Inventory.RebuildArmorCache (System.Collections.Generic.Dictionary`2[TKey,TValue] armorCache, RimWorld.StatDef stat) [0x00020] in <1dc467c8c68f4c6cb3dd33c143973e2e>:0 
 at CombatExtended.ITab_Inventory.FillTab () [0x002b0] in <1dc467c8c68f4c6cb3dd33c143973e2e>:0 
 at Verse.InspectTabBase+<>c__DisplayClass19_0.<DoTabGUI>b__0 () [0x00039] in <2a40c3593b334f29ac3cb3d32d652351>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Known issue, should be fixed in dev branch.
