### ISSUE TITLE
[Patch Request/maybe bug]: VFE Classical VFE Tribals & Early Times 

### ISSUE THREAD

**Issue by yourmum21** [CombatExtended-Continued/CombatExtended#3533]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**

**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**

**Title should be:** [Patch Request]: (Mod Name)

**Mod name:**

VFE Classical
VFE Tribals 
Early Times

**Link to mod download (preferably Steam workshop or Github):**

VFE Classical https://steamcommunity.com/sharedfiles/filedetails/?id=2787850474
VFE Tribals https://steamcommunity.com/workshop/filedetails/?id=3079786283
Early Times https://steamcommunity.com/sharedfiles/filedetails/?id=2025987215

**Description:**
CE seems to overwrite certain items in the stockpile tables. They are entirely missing from the list, but still absolutely included in the game world. This makes you unable to add these items to the stockpile. I'm sure there are more cases, I just noticed these 3 immediately.
I noticed it with:
CE x VFE Classic: Javelin: deleted in the stockpile list, when searching for it CE's javelin comes up.
CE x VFE Tribals: Throwspikes: deleted in the stockpile list, I'm unsure which item CE wanted to replace it with.
CE  x my beloved Early Times: Pila: deleted, probably also CE javelin. 

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
After looking into the issue, this appears to be cause by CE changing the parents of these weapons from BaseWeapon but forgetting to directly assign them a thing category--a simple oversight and easy enough to fix. I'll have the fixes included in a PR soon.

However, the Early Times patch is on the mod's side, rather than ours, and so we can't do anything about that one.

**Comment by yourmum21** [comment]
Amazing! I would have loved to have fixed auch a trivial thing myself without hogging your time but alas I'm clueless 😂
