### ISSUE TITLE
[Patch Request]: Rebound

### ISSUE THREAD

**Issue by JermandJer** [CombatExtended-Continued/CombatExtended#36]
Mod name: Rebound

https://steamcommunity.com/sharedfiles/filedetails/?id=2068326756

Description: A mod that allows melee users to deflect projectiles back at their shooters based on melee skill. Nerf after patching by increasing manipulation needed to reflect. 

What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

I hereby verify that I have done all of the following:
- [/] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [/] Confirmed there are no other open Patch Requests for this mod.
- [/] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [/] **Have completed this template accurately and completely.**
- [/] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [/] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by N7Huntsman** [comment]
6/16 - Rebound added CE support on their side.
