### ISSUE TITLE
[Bug]:Error and i dont know why

### ISSUE THREAD

**Issue by nexusxeno** [CombatExtended-Continued/CombatExtended#3600]
Exception in Verse.LongEventHandler.UpdateCurrentSynchronousEvent: System.Exception: VCE_Megareindeer.lifeStages[1].femaleDessicatedBodyGraphicData ---> System.Exception: BoundMap(,) ---> System.Exception: Combat Extended :: CropVertical error while cropping Textures/Things/Pawn/Animal/Elk/MegareindeerFemale_Dessicated_side ---> System.NullReferenceException: Object reference not set to an instance of an object
[Ref 23770766] Duplicate stacktrace, see ref for original
   --- End of inner exception stack trace ---
[Ref EF80C482] Duplicate stacktrace, see ref for original
   --- End of inner exception stack trace ---
[Ref A8B4B75B] Duplicate stacktrace, see ref for original
   --- End of inner exception stack trace ---
[Ref 34C3463D]
 at CombatExtended.BoundsInjector.Inject () [0x001f6] in <d4f808b7eac94548b83685e1520170fc>:0 
 at Verse.LongEventHandler.UpdateCurrentSynchronousEvent (System.Boolean& sceneChanged) [0x00027] in <d4283d69f1dd45829ad7cf101e8491d9>:0 
     - TRANSPILER net.pardeike.rimworld.lib.harmony: IEnumerable`1 VisualExceptions.ExceptionsAndActivatorHandler:Transpiler(IEnumerable`1 instructions, MethodBase original)

**Comment by N7Huntsman** [comment]
VCE has not been patched yet.
