### ISSUE TITLE
[Discussion]: Directed energy/beam weapons

### ISSUE THREAD

**Issue by sumghai** [CombatExtended-Continued/CombatExtended#362]
Currently, all ranged weapons in CE fire discrete projectiles, but there are cases where a continuous beam weapon discharge would be more appropriate:

* Vanilla Weapons Expanded: Lasers
* Rimlaser
* Various mods that add Star Trek phasers, disruptors etc.

## Factors to consider

* Range - handled by the weapon itself
* Speed - should be uniformly regarded as instantaneous
* Falloff - some types of energy beams may be more susceptible to dissipation in air than others
* Damage per tick/second at point of contact
* Off-bore tracking - whether the end of the laser beam should continue to follow a moving target, even if off the weapon's axis of firing; Star Trek phasers, for instance, are canonically stated as having gyro stabilization
* Multiple beams fired at multiple simultaneous targets - again, usually Star Trek phasers
* Variable power/damage levels - ditto

**Comment by N7Huntsman** [comment]
I believe this one can be considered completed with the 3.6 release of the laser framework.

**Comment by sumghai** [comment]
Coolio! I should find some time to rework some of our existing patches to take advantage of this new feature. Gracias!
