### ISSUE TITLE
[Patch Request]: Wehrmacht Faction

### ISSUE THREAD

**Issue by eser704** [CombatExtended-Continued/CombatExtended#365]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**

**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**

**Title should be:** [Patch Request]: Wehrmacht Faction by Danny is the Avali-tsar

**Mod name:** Wehrmacht Faction

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2282825562

**Description:**
Provide a brief overview of what content the mod adds or modifies. Specify what content in particular you believe require a patch to be compatiably with Combat Extended.

It's adding a new faction. This mod uses weapons from Reich Armory which is compatible CE, and Apparel from WWII German Uniforms - V's Edit by Vaeringjar (original is made by Ods). When I play CE with the mod, raid from the faction they don't have any ammo. Red signs are displayed when I apply the mod. 

**Content:**
What does the new mod contain? Check all that apply.
- [yes] New weapons.
- [no] New animals, humanoids, or other creatures.
- [yes] New factions.
- [yes] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [O] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [O] Confirmed there are no other open Patch Requests for this mod.
- [O] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [O] **Have completed this template accurately and completely.**
- [O] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [O] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
It seems the mod was removed from the workshop. If there's an alternate upload, go ahead and link it, but I'm closing this for the time being.

**Comment by eser704** [comment]
> It seems the mod was removed from the workshop. If there's an alternate upload, go ahead and link it, but I'm closing this for the time being.

The author has uploaded the mod again. here is the link: https://steamcommunity.com/sharedfiles/filedetails/?id=2282825562
