### ISSUE TITLE
[Patch Request]: Zorg ZF1

### ISSUE THREAD

**Issue by LeriWeill** [CombatExtended-Continued/CombatExtended#366]
**Mod name:** [Zorg ZF1](https://steamcommunity.com/sharedfiles/filedetails/?id=2285163237)

**Description:**
The infamous weapon from Besson's Fifth Element.
The weapon features the different fire mods (arrow, machine gun, flamethrower, etc)
I don't really now how this could translate into CE; a solution would be to allow the various ammunition, but this would require reloading when switching from one mod to another.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Breadbox2k19** [comment]
Might be finally patchable with the attachment system.

**Comment by N7Huntsman** [comment]
This mod is no longer available on the workshop for 1.5.
