### ISSUE TITLE
[Bug]: Game crash when downed Skullywag from MoreMechanoids dies by bullet

### ISSUE THREAD

**Issue by exuvo** [CombatExtended-Continued/CombatExtended#37]
Just wondering if anyone else has/has had similar problems before and can maybe point me in a direction for how to debug this seeing as the game does not print any stack trace. Preferably without having to spend hours changing the mod list and restarting the game.

**Specifications**

Rimworld version: 1.1
Combat Extended version: CombatExtended-Continued 1.1 on steam
Combat Extended source: Steam
Your operating system: Windows 7 x64
Your mod list: ~190st https://pastebin.com/ncKHjnar

**Description**
When a skullywag from MoreMechanoids gets incapacitated with normal bullets, hitting in while it is down instantly and consistenlty crashes the game for me. Have not had problems with the other mechanoids from same mod from what i noticed but maybe they don't get incapacitated and just die?

Workaround is to use finish downed button to kill the incapacitated skullywag without crash.

**Expected behavior**
Skullywag dies and no crash.

**To reproduce**
Shoot skullywag with normal guns ex repeating rifle until it gets incapacitated. Then hit again while it is incapacitated.

**Screenshots & log dumps**
Game dies before any error is printed to the in game log and could not find any other on disk.

**Complete the following checklist**
I hereby verify that I have done the following:
- [think so] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [i removed those that don't work, exception More Vanilla Turrets which i don't build any of until patches are in] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [too lazy] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Juanfrank** [comment]
Test 1:
Upon downing the Skullywag with the Dev mode "Damage until downed": https://pastebin.com/HenbZcEC . No errors when shot to death afterwards.
Test 2: Shot down until downed. Errors pop up as soon as you shoot it.

**Comment by exuvo** [comment]
Must be something with the other mods i have then.
