### ISSUE TITLE
[Bug]: EMP munitions throw error when hitting mortar/bullet shield.

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#40]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.1
Combat Extended version: 1.1.2.0
Combat Extended source (Steam, GitHub, etc.): Github
Your operating system: Windwos 10 x64
Your mod list: Harmony, Core, Combat Extended

**Description**
When hitting a mech mortar/bullet shield from a mech siege, EMP bullets/mortars throw an error when hitting their respective kinds of shields. The projectiles continue through the shield. An EMP rounds affecting the shield generator will temporarily stun it.

This does not occur with non-EMP rounds, which are stopped as intended. 

**Expected behavior**
I'm unsure what the intended behavior is--whether the rounds are just supposed to pass through the shield, or if the EMP round is supposed to stun the shield generator.

**To reproduce**
1. Place mortar or bullet shield using dev mode.
2. Use dev mode to set the mortar to stop non-hostile projectiles.
3. Fire EMP mortar or bullet into the shields area of effect.

**Screenshots & log dumps**
https://pastebin.com/TnsQELzk

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Fortunately, EMP rounds were meant to counter shields to begin with, and this error still has that effect because the rounds can pass through the shield and hit the generator to disable it.

**Comment by MadaraUchiha** [comment]
Either the code has changed, or something else went terribly wrong. The code is looking for a field `lastHitByEmpTicks` on `CompProjectileInterceptor`, and such a field does not exist.

This either never worked, or the RimWorld devs modified the code in such a way as to make that field obsolete.

**Comment by N7Huntsman** [comment]
Resolved by #74
