### ISSUE TITLE
[Discussion]: Mechanoid Ammo Wealth

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#42]
As it stands, the quantity and value of mechanoid ammo causes a great deal of wealth bloat, and can require drastic/unusual steps by the player to manage.

There are two primary culprits:
- The value of mechanoid ammo.
- The quantity of mechanoid ammo.

Centipedes are especially problematic, as the tend to either carry large amounts of ammo (heavy charge blaster) or very valuable ammo (inferno cannon). Reducing the marketValue of these ammo types in the .xml is simple enough, but isn't a permanent solution. 

There's a need to reduce the quantity of ammo dropped by mechanoids when they're killed without diminishing their firepower. @LockdownX7 had suggested this could potentially be done through C#, using a functionality similar to the death acidifier.

**Comment by sumghai** [comment]
@Alicecomma had some pretty neat ideas for Centipedes to internally generate their own ammo, possibly by consuming items or resources while roaming the map:

> * Centipedes could have an internal "ammo generating bodypart", automatically reloading its magazines.
> * Centipedes could require steel or rocks or other stuff to resupply this bodypart, causing them to eat into steel walls and steel deposits to resupply ammo. This'd be especially relevant for miniguns.
> * Centipedes could consume anything and the bodypart could be a fusion thing, so the headcanon is centis convert matter to plasma charges for their charge weapons by eating anything found on the battlefield
> * Centipedes could consume ammo off of downed pawns (as well as the pawns themselves)
> * Consuming items off the ground could result in small explosions within the centipede, so you could intentionally leave grenades and mortar shells around the place for them to internally destroy themselves

**Comment by N7Huntsman** [comment]
This has been somewhat remedied by reducing the mech ammo value in #41

**Comment by Breadbox2k19** [comment]
Centipede no longer carry as much ammo as they used to, closed.
