### ISSUE TITLE
[Patch Request]: Cybernetic Warfare and Special Weapons (Continued)

### ISSUE THREAD

**Issue by LeriWeill** [CombatExtended-Continued/CombatExtended#431]
**Mod name:** [Cybernetic Warfare and Special Weapons (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2155485488)

**Description:**
Cool spacer-level weapons. Mostly updated for CE (stats, bulk, etc), but some weapons, especially the Napalm Blaster, lack an ammo-set.
Mlie doesn't seem to want to make the changes.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [ ] Searched the Steam workshop, Discord, and Github for an existing patch and not found one : patch is built-in the mod, but Tostov told me to open an issue anyway
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by LeriWeill** [comment]
Might as well specify the weapons :

- Napalm Blaster could use the generic fuel ammo

- Recon bolter uses an energy beam which seems to have no value defined.

**Comment by Breadbox2k19** [comment]
I'll contact mlie and make the appropriate changes.

**Comment by Breadbox2k19** [comment]
Again, I'm not really getting the issue, here, not having an ammoset doesn't break the weapon, it just makes weapon fire without ammo, if you are getting red errors because of it. Post it here.
