### ISSUE TITLE
[Bug]: Projectile Incompatibility For Dragon's Descent Dragon Breath, and Potential Further Incompatibility with Other Mods

### ISSUE THREAD

**Issue by Ordpus** [CombatExtended-Continued/CombatExtended#440]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.2.7558.21380
Combat Extended version: 1.2.3.4
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list:
Harmony
Core
Mod Manager
Combat Extended
Dragon's Descent

**Description**
When using the dragon breath skill, cast expectation happens. The dragon cannot produce breath.

**Expected behavior**
The dragon should generate a series of dragon breath projectile

**To reproduce**
Just use the skill of any dragon. The dragon should be tamed for easier operation.

**Screenshots & log dumps**
![image](https://user-images.githubusercontent.com/12138313/102965829-a3f1b800-44bc-11eb-888c-0ad6e744d704.png)
[Player.log](https://github.com/CombatExtended-Continued/CombatExtended/files/5733648/Player.log)

**Some Suggestions**
Can be solved by using the patch
```
<li Class="PatchOperationAttributeAdd">
          <xpath>/Defs/AbilityDef[defName="DragonBreath"]/comps/li[@Class="DD.AbilityCompProperties_CastVerb"]/verbProperties/li</xpath>
          <attribute>Class</attribute>
          <value>CombatExtended.VerbPropertiesCE</value>
        </li>

        <li Class="PatchOperationReplace">
          <xpath>/Defs/AbilityDef[defName="DragonBreath"]/comps/li[@Class="DD.AbilityCompProperties_CastVerb"]/verbProperties/li[verbClass="Verb_Shoot"]/verbClass</xpath>
          <value>
            <verbClass>CombatExtended.Verb_ShootCE</verbClass>
          </value>
        </li>

        <li Class="PatchOperationAdd">
          <xpath>/Defs/AbilityDef[defName="DragonBreath"]/comps/li[@Class="DD.AbilityCompProperties_CastVerb"]/verbProperties/li[verbClass="CombatExtended.Verb_ShootCE"]</xpath>
          <value>
            <ejectsCasings>false</ejectsCasings>
            <recoilAmount>0.2</recoilAmount>
            <circularError>2</circularError>
          </value>
        </li>
```
The numbers are not perfect, but it solves the problem

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Breadbox2k19** [comment]
Well, if you know how to solve the problem, why not submit a PR?
