### ISSUE TITLE
[BUG] M4 carbine from Rimsenal Vanilla bug

### ISSUE THREAD

**Issue by T-rexsuper1** [CombatExtended-Continued/CombatExtended#445]
It has no 3 rounds burst fire mode. I have fixed the issue. 

It's a bug since all other carbines and assault rifles have that.

[Weapons_RSGuns_CE.zip](https://github.com/CombatExtended-Continued/CombatExtended/files/5740078/Weapons_RSGuns_CE.zip)

**Comment by sumghai** [comment]
@T-rexsuper1 - Please open a Pull Request and submit your bugfix through it.
