### ISSUE TITLE
[Patch Request]: Forsakens

### ISSUE THREAD

**Issue by LeriWeill** [CombatExtended-Continued/CombatExtended#454]
**Mod name:** [Forsakens](https://steamcommunity.com/sharedfiles/filedetails/?id=1728999127)

**Description:**
Adds a race, two scenarios, weapons and apparel. 
Most of the mod is already patched, one scenario is missing Forsaken Arrows and some weapons are missing ammo sets.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [x] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Breadbox2k19** [comment]
Specify which weapon is missing ammoset?

**Comment by LeriWeill** [comment]
> Specify which weapon is missing ammoset?

My bad, seems like I spoke too fast. Black Hydra does have ammo but does not need to be reloaded lore-wise. And the scenarios are set-up correctly 🙄

I'm wondering, maybe the Forsaken Bow could be made to accept other arrow ammo, even if it's less powerful than the Forsaken Arrows?

**Comment by Breadbox2k19** [comment]
I can create a new ammoset that allows forsaken bow to fire greatbow arrows as well.
I can also delete the ammoset from black hydra and allow to fire without ammo. But you won’t be able switch between different ammotypes.

**Comment by Breadbox2k19** [comment]
Blackhydra already has no ammoset, which should allow it to fire without ammo. So I’m not sure what the issue is, if you cannot fire the blackhydra, send me the red error messages you got.

**Comment by Breadbox2k19** [comment]
Looking trough the xml, forsaken bow is just a really overpriced recurve bow, I’ll buff the bow alittle and allow it to fire normal arrows as well.

**Comment by LeriWeill** [comment]
> Blackhydra already has no ammoset, which should allow it to fire without ammo. So I’m not sure what the issue is, if you cannot fire the blackhydra, send me the red error messages you got.

Yeah that's what I was saying, I thought BH wasn't patched correctly but it is. I saw no ammo set but there is no need for one, so all is good 😊
