### ISSUE TITLE
[Bug]: "Specified Cast Is Not Valid"

### ISSUE THREAD

**Issue by sabrt00th** [CombatExtended-Continued/CombatExtended#460]
Rimworld version: 1.2.2753
Combat Extended version: 3.4
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10 64bit
Your mod list: See log, it'll be right at the top.

**Description:**
Upon trying to fire any gun, all rounds in the chamber disappear at once without anything being fired. Log spouts something about "InvalidCastException" and several failures of "LaunchProjectileCE.TryCastShot". 

**Expected behaviour:**
Firing the gun one round after the other, with actual bullets coming out the end of it.

**To reproduce:**
1. Spawn any weapon and appropriate ammo.
2. Load ammo into gun.
3. Aim at anything.
4. Attempt to fire.

**Screenshots & log dumps:**
Log: https://gist.github.com/HugsLibRecordKeeper/1371e737dea1200a1dd8f22f9cb4514e
![image](https://user-images.githubusercontent.com/7752227/103265103-c36e7080-49e7-11eb-87c0-9d98254a9d21.png)
![image](https://user-images.githubusercontent.com/7752227/103265146-de40e500-49e7-11eb-9df1-7dbe3b71779c.png)
![image](https://user-images.githubusercontent.com/7752227/103265190-f6186900-49e7-11eb-81c6-1c8f898ed60f.png)
(this all went by in less than half a second, could scarcely blink my eyes.)
![image](https://user-images.githubusercontent.com/7752227/103265213-03355800-49e8-11eb-92d4-6d26f528f122.png)

**I hereby verify that I have done the following:**
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by sumghai** [comment]
With over ~130 mods, diagnosing your issue directly from the logs would take a very long time.

Could you try starting a new, temporary savegave with the **_bare minimum_** number of mods that are required to cause this issue? That will make it easier for us to narrow down the actual cause of the problem.

**Comment by sabrt00th** [comment]
Below are the logs for a brand new save with as little mods as I thought would be relevant (i.e. things that affect inventory, or add weapons. Same thing happened.
https://gist.github.com/sabrt00th/7916a95909235d9d9df0789d48010fe0

**Comment by N7Huntsman** [comment]
Are you running anything that may affect the bullet projectiles? Their damage, speed, or other stats?

**Comment by sabrt00th** [comment]
Not that I'm aware of. I only left things in that affected the weapons, or the way inventory worked, as stated above. Nothing that directly and knowingly edited how much damage something does, if that's what you're asking.

**Comment by sumghai** [comment]
That's still 20 mods to diagnose.

Could you please narrow that list down further, ideally to 1~2 mods that are definitely causing the issue?

**Comment by sabrt00th** [comment]
Having removed every other mod except Harmony, Hugslib, and a minor graphics mod, it's safe to say that the issue lies with [Pick Up And Haul (Continued).](https://steamcommunity.com/sharedfiles/filedetails/?id=2277459062) Strange, since PUAH also seems to conflict with Achtung. Maybe an update on their part broke some stuff when interacting with Harmony?

Log in case you need it: https://gist.github.com/d447f99a6dc5399203a7d4bf0b6e07aa
