### ISSUE TITLE
[Discussion]: Night Vision Comp

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#463]
The addition of a Night Vision xml Comp that could be added to weapons and apparel, which simply negates the aiming penalty CE introduces for shooting at targets darkness, would be a desirable addition.

This would, ideally, be something that could be readily applied to weapons, apparel, an implants. As commented below, an effectiveness adjustable in the xml may also be desirable.

**Comment by sumghai** [comment]
Neat idea!

Would it make sense to have the comp be configurable via a `negationFactor` or equivalent parameter? This would allow modders to make night vision devices with varying degrees of compensating for darkness.

e.g.
- No night vision comp: 100% penalty
- Crude photomultiplier tube: 50% penalty
- Military-grade night vision optics: 25% penalty
- [Full-color night vision optics](https://www.thedrive.com/the-war-zone/25803/this-is-what-color-night-vision-looks-like-and-it-stands-to-be-a-game-changer): 0% penalty, equivalent to daytime

(actual values are up for discussion)

**Comment by Breadbox2k19** [comment]
Do bionic and archotech eyes affect these penalties already?
