### ISSUE TITLE
[Bug]: Trying to get stat MeleeDamage from Mead which has no support for Combat Extended.

### ISSUE THREAD

**Issue by ShuuNae** [CombatExtended-Continued/CombatExtended#466]
**Specifications**

Rimworld version:
Combat Extended version: 1.1
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: win 10
Your mod list: CE

**Description**
I opened deblug log and saw a bunch of these logs:
Trying to get stat MeleeDamage from Mead which has no support for Combat Extended.
Trying to get stat MeleeArmorPenetration from Mead which has no support for Combat Extended.

**Expected behavior**
Remove this bug

**To reproduce**
Remove this bug

**Screenshots & log dumps**
![image](https://user-images.githubusercontent.com/66380099/103471265-c6cf7680-4db0-11eb-9550-059c28489b27.png)
log: https://pastebin.com/sY2mPniR

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by sumghai** [comment]
What version of the base RimWorld game itself are you running?

Why are you running an old version of CE (1.1)? The latest version at the time of writing is v1.2.3.4, designed for RimWorld 1.2.

Mead does not exist in vanilla RimWorld or the Royalty DLC. What other mods are you running?

**Comment by ShuuNae** [comment]
> What version of the base RimWorld game itself are you running?
> 
> Why are you running an old version of CE (1.1)? The latest version at the time of writing is v1.2.3.4, designed for RimWorld 1.2.
> 
> Mead does not exist in vanilla RimWorld or the Royalty DLC. What other mods are you running?

- My RimWorld version is 1.1.2652 rev1102
- Well im running RimWorld 1.1 so i think CE should be 1.1 too.
- Thanks for reminded me RimWorld vanilla doesn't have Mead. I searched my mods and found VGP Vegetable Garden mod has Mead.

**Comment by sumghai** [comment]
Can you try running RimWorld 1.2.2753 and CE 1.2.3.4 instead?

**Comment by ShuuNae** [comment]
> Can you try running RimWorld 1.2.2753 and CE 1.2.3.4 instead?
some of my favorite mods haven't yet updated so i can only stay at RimWorld 1.1
