### ISSUE TITLE
[Patch Request]:Tactical Extremity Protection [BAL] 

### ISSUE THREAD

**Issue by vavetuzik** [CombatExtended-Continued/CombatExtended#487]
Mod name: Tactical Extremity Protection [BAL]

Link to mod download (preferably Steam workshop or Github):https://steamcommunity.com/sharedfiles/filedetails/?id=2362734735&searchtext=

Description: This mod adds 9 new pieces of industrial-era armor, as well as 2 of spacer-era, that have been designed to fill the gaps that currently exist in the base game's selection of armor. They all fit on either the middle or outer layers only, allowing for a high level of loadout customization to suit your needs. These loadouts have been meticulously balanced with MATH to not be clearly superior to existing Core/Royalty power armors.

Content:
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] Have completed this template accurately and completely.
- [x] Understand that putting in a Patch Request does not guarantee a patch will be made.
- [x] Agree that I will not directly contact contributors to ask about patch requests.

**Comment by N7Huntsman** [comment]
Closed by #575
