### ISSUE TITLE
[Bug]:Loadouts don't work with Rimsec Security's droids

### ISSUE THREAD

**Issue by MaldingBald** [CombatExtended-Continued/CombatExtended#498]
Rimworld verision: 1.2.2753 rev705
Combat Extended version: v3.4
Combat Extended source: Github
Your operating system: Windows 10
Your mod list: 
			<li>Harmony</li>
			<li>Core</li>
			<li>Royalty</li>
			<li>HugsLib</li>
			<li>Combat Extended</li>
			<li>Humanoid Alien Races 2.0</li>
			<li>Rimsec Security</li>
Description: The new Rimsec Security Patch won't allow Droids to take ammo from storage when assigned a loadout
Expected behavior: Droids will auto equip ammo from assigined loadouts
To reproduce: spawn Sentinels from Trade Beacons, assign them a loadout and they won't equip the proper loadout
I hereby verify that I have done the following:
- [ x] Confirmed that my game version and load order are correct.
- [ x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Falls under the umbrella of #512.
