### ISSUE TITLE
Ferrex race reload/weapon issue[Bug]:

### ISSUE THREAD

**Issue by RagingLoony** [CombatExtended-Continued/CombatExtended#508]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.2
Combat Extended version: Latest
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: win10 home 64
Your mod list:
<li>brrainz.harmony_copy</li>
    <li>ludeon.rimworld</li>
    <li>ludeon.rimworld.royalty</li>
    <li>unlimitedhugs.hugslib_copy</li>
    <li>user19990313.runtimegc_copy</li>
    <li>fluffy.modmanager_copy</li>
    <li>erdelf.humanoidalienraces_copy</li>
    <li>edb.preparecarefully_copy</li>
    <li>mlie.colonistbarkf_copy</li>
    <li>jaxe.rimhud_copy</li>
    <li>jaxe.pawnrules_copy</li>
    <li>reiquard.researchinfo_copy</li>
    <li>community.psychology.unofficialupdate_copy</li>
    <li>orion.hospitality_copy</li>
    <li>ceteam.combatextended_copy</li>
    <li>dimonsever000.rimcore.specific_copy</li>
    <li>oskarpotocki.vanillafactionsexpanded.core_copy</li>
    <li>machine.betterinfestations_copy</li>
    <li>fluffy.fluffybreakdowns_copy</li>
    <li>fluffy.relationstab_copy</li>
    <li>indeed.stackxxl_copy</li>
    <li>uuugggg.replacestuff_copy</li>
    <li>fluffy.researchtree_copy</li>
    <li>fluffy.medicaltab_copy</li>
    <li>fluffy.pharmacist_copy</li>
    <li>fluffy.worktab_copy</li>
    <li>fluffy.animaltab_copy</li>
    <li>dubwise.dubsmintmenus_copy</li>
    <li>dubwise.dubsbadhygiene_copy</li>
    <li>unlimitedhugs.mapreroll_copy</li>
    <li>notfood.seedsplease_copy</li>
    <li>shadow.spaiomegapatch_copy</li>
    <li>ykara.epoe_copy</li>
    <li>spoonshortage.adogsaidanimalprosthetics_copy</li>
    <li>dimonsever000.prosthesesplus.specific_copy</li>
    <li>dimonsever000.diseasesplus.specific_copy</li>
    <li>mlie.ferrexrace_copy</li>
    <li>dianawinters.orassans_copy</li>
    <li>acpteam.acp_copy</li>
    <li>rh.faction.allegiance_copy</li>
    <li>rh.faction.coalition_copy</li>
    <li>rh.faction.cordis.die_copy</li>
    <li>rh.faction.elite.crew_copy</li>
    <li>rh.faction.last.man.contingent_copy</li>
    <li>rh.faction.task.force.141_copy</li>
    <li>rh.faction.the.ghosts_copy</li>
    <li>rh.faction.void_copy</li>
    <li>rh.faction.war.mongrels_copy</li>
    <li>ceteam.combatextendedguns_copy</li>
    <li>ceteam.combatextendedmelee_copy</li>
    <li>spoonshortage.fashionrimsta_copy</li>
    <li>kentington.saveourship2_copy</li>
    <li>ruyan.highcaliber_copy</li>
    <li>pratt.raw.wwiiweaponspackvanilla_copy</li>
    <li>vanillaexpanded.varme_copy</li>
    <li>vanillaexpanded.vappe_copy</li>
    <li>cp.rimmunation.weapons_copy</li>
    <li>cp.rimmunation.clothing_copy</li>
    <li>shinzy.apparello_copy</li>
    <li>ravvy.amw_copy</li>
    <li>dylan.animalgear_copy</li>
    <li>ohgodspidersno.animalarmor.vanilla_copy</li>
    <li>paradox.morevanillaturrets_copy</li>
    <li>showhair.kv.rw_copy</li>
    <li>rimsenal.hair_copy</li>
    <li>vanillaexpanded.vhe_copy</li>
    <li>sgc.moreutilitypacks_copy</li>
    <li>haplo.miscellaneous.core_copy</li>
    <li>haplo.miscellaneous.robots_copy</li>
    <li>alaestor.miscrobots.plusplus_copy</li>
    <li>haplo.miscellaneous.incidents_copy</li>
    <li>earthyturtle.letstrade_copy</li>
    <li>cucumpear.ledlights_copy</li>
    <li>thegoofyone.arearugs_copy</li>
    <li>wofl.morefurnitureupdated_copy</li>
    <li>spoonshortage.gourimet_copy</li>
    <li>vanillaexpanded.vcooke_copy</li>
    <li>dismarzero.vgp.vgpvegetablegarden_copy</li>
    <li>dismarzero.vgp.vgpmoreveggies_copy</li>
    <li>dismarzero.vgp.vgpgardentools_copy</li>
    <li>dismarzero.vgp.vgpgardenresources_copy</li>
    <li>dismarzero.vgp.vgpgardenmedicine_copy</li>
    <li>dismarzero.vgp.vgpgardengourmet_copy</li>
    <li>dismarzero.vgp.vgpgardenfabrics_copy</li>
    <li>rimfridge.kv.rw_copy</li>
    <li>regrowth.botr.core_copy</li>
    <li>regrowth.botr.borealforestexpansion_copy</li>
    <li>regrowth.botr.coldbogexpansion_copy</li>
    <li>regrowth.botr.temperateforestexpansion_copy</li>
    <li>regrowth.botr.tundraexpansion_copy</li>
    <li>vanillaexpanded.vfecore_copy</li>
    <li>peppsen.pmusic_copy</li>
    <li>mlie.sdadvancedpowergeneration_copy</li>
    <li>mlie.roadsoftherim_copy</li>
    <li>ogliss.bishop.smokeleafindustryreborn_copy</li>
    <li>unlimitedhugs.allowtool_copy</li>
    <li>mlie.pickupandhaul_copy</li>
    <li>vanillaexpanded.vfespacer_copy</li>
    <li>telkir.tmods.morebedscloth_copy</li>
    <li>smashphil.dropspot_copy</li>
    <li>tradingspot.kv.rw_copy</li>
    <li>murmur.walllight_copy</li>
    <li>telkir.tmods.morefloors_copy</li>
    <li>crlsniper.realisticrooms_copy</li>
    <li>dracoix.doormat.r12a_copy</li>
    <li>mlie.barnstall_copy</li>
    <li>jecrell.doorsexpanded_copy</li>
    <li>okradonkey.silentdoors_copy</li>
    <li>syrchalis.setupcamp_copy</li>
    <li>pinochemicali.moretradeships_copy</li>
    <li>ratys.madskills_copy</li>

**Description**
Provide a concise description of the issue or concern. What happened?
Whenever a Ferrex colonist equips a gun, the options to reload are missing, and also the ammo count is missing. They can fire untilt he weapon is out of ammo, then just spam "out of ammo" over and over while trying to reload. Only happens with colonists of the Ferrex race, if they drop the gun and a human equips it everything works normally. 
**Expected behavior**
What did you expect to happen?
Normal CE behavior. 
**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
Have a colonist of the Ferrex race (The ferret people)[modded race] equip any gun.
**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 
No errors are produced in the log, oddly enough.
**Complete the following checklist**
I hereby verify that I have done the following:
- [/ ] Confirmed that my game version and load order are correct.
- [/ ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ /] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [N/A ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by RagingLoony** [comment]
I was able to fix this by going into the Combat Extended mod folder, then into patches, rename the 'Ferret' folder to 'Ferrex', and renaming the 3 XML files inside, replacing the word 'Ferret' with 'ferrex' in each, then copying the raw code from the 3 files here on github, and overwriting the code in the 3 files in the mod folder.

My apologies, I am fairly new to github.

**Comment by sumghai** [comment]
Ferret/Ferrex patches have already fixed in the CE current dev build, and will be included in the next update:

* 84757a1 (8 Jan 2021)
* d438ae8 (11 Jan 2021)
* ada8be3 (24 Jan 2021)
* fc9988d (24 Jan 2021)

Also, please don't deviate from the standard bug report template.
