### ISSUE TITLE
[Discussion]: Non-Colonist Loadout Framework

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#512]
We're beginning to see a number of mods out there that add player-controlled, non-colonist ranged weapon users that can be equipped with ranged weapons. Mods like these include:
- VFE - Mechanoids
- RimSec Security
- What The Hack

Currently, there is nothing in place to allow the player to keep these pawns supplied with ammunition for their weapons.

It seems to me that the most straightforward solution to this issue is to plug these pawns into the loadout system, to allow the player to manually control their ammo supply. At present, these pawns are generally not plugged into that system or to the related inventory jobs. Ideally, we can develop a framework that can be applied to these pawns to quickly make them compatible, rather than creating individual solutions for them.

**Comment by Breadbox2k19** [comment]
Probably the single most major omitted feature RN.
