### ISSUE TITLE
[Bug]: Fallout New Vegas - Elite Riot Gear & CE

### ISSUE THREAD

**Issue by Nubasik** [CombatExtended-Continued/CombatExtended#514]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.2.2753 rev705
Combat Extended version: 1.2.3.2
Combat Extended source (Steam, GitHub, etc.): GitHub
Your operating system: Win 7x64 
Your mod list:
Harmony; Core; Royalty; HugsLib; Combat Extended; Fallout New Vegas - Elite Riot Gear.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

Screenshot
![2021-02-01_102720](https://user-images.githubusercontent.com/70583512/106427275-da204100-6445-11eb-8ef7-3a2be14602de.png)
Log - https://gist.github.com/HugsLibRecordKeeper/938b7cc888e6443c92a54ad8de0bafa7

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Fixed. The defNames for the stuffable variants were changed.
