### ISSUE TITLE
[Discussion]: there is no description anywhere for exactly what aim modes do

### ISSUE THREAD

**Issue by a7x492** [CombatExtended-Continued/CombatExtended#527]
I've searched the tutorials, mod page on steam, and this whole repository. Nothing really explains what they do. For example, see this search: https://github.com/CombatExtended-Continued/CombatExtended/search?q=snapshot

I guess from the name that snapshot is faster and less accurate? What about suppress? Rather than vague descriptions, the exact calculations and numbers involved would be awesome or at least a link to the code involved.

**Comment by N7Huntsman** [comment]
Hmm. Probably an item that could be added to the learning helper, if needed.

**Comment by LockdownX7** [comment]
There is a learning helper for CE aim modes, but it hasn't been updated in a while, so it's missing some important information like suppression. I'll update it to better explain the advantages of each aim mode.

**Comment by LockdownX7** [comment]
@a7x492 I kept the learning helper explanation easy to understand for everyone, but if you want to dive into the calculations, you can look at SwayAmplitude in the [Verb_ShootCE](https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/Source/CombatExtended/CombatExtended/Verbs/Verb_ShootCE.cs) class.
