### ISSUE TITLE
[Bug]: Debug error on startup when patching EPOE

### ISSUE THREAD

**Issue by Brumes-Wolf** [CombatExtended-Continued/CombatExtended#530]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: Debug error on startup for patching EPOE

**Specifications**
Please provide the following.

Rimworld version: 1.2.29
Combat Extended version: 1.2.3.5
Combat Extended source : Steam
Your operating system: Windows
Your mod list:

    brrainz.harmony
    ludeon.rimworld
    ceteam.combatextended
    ykara.epoe

**Description**
After startup there is an error in the log:
Said error: 
```
[Combat Extended] Patch operation Verse.PatchOperationFindMod(Expanded Prosthetics and Organ Engineering) failed
file: C:\SteamLibrary\steamapps\workshop\content\294100\1631756268\Patches\EPOE\Bionics.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

```
While i have no experience with rimworld modding, I have a guess about what is happening though.
Inside of EPOE there is no file called Bionics.xml however, So I assume CE is trying to patch a file that doesn't exist.

**Expected behavior**
What did you expect to happen? 

There to be no error

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?

Load EPOE and CE and harmony, and start the game

**Comment by onigamii** [comment]
Fixed already
