### ISSUE TITLE
[Patch Request]: Androids Expanded (Continued)

### ISSUE THREAD

**Issue by feeddanoob** [CombatExtended-Continued/CombatExtended#534]
**Mod name:** Androids Expanded (Continued)

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2379962272&searchtext=android+expanded

**Description:**
The Androids Expanded fork fixes an issue with the original mod for Rimworld 1.2. It has a new name so the current Androids Expanded patch will not work for it. Things that are already patched from CE for Androids Expanded should also work for Androids Expanded (Continued).

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by onigamii** [comment]
But the original mod is 1.2 already https://steamcommunity.com/sharedfiles/filedetails/?id=2179977828

**Comment by feeddanoob** [comment]
Yes, but the original mod contained errors on game startup because of mismatch traits from the rimworld v1.2 update. The mentioned fork fixes those game startup errors.

**Comment by onigamii** [comment]
Fixed
