### ISSUE TITLE
[Patch Request]: Cybernetic Organism and Neural Network (mod updated)

### ISSUE THREAD

**Issue by feeddanoob** [CombatExtended-Continued/CombatExtended#556]
**Mod name:** Cybernetic Organism and Neural Network

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2045064990

**Description:**
Mod got updated and I am having duplicate xml node errors from the patch on <defName>Trunken_hediff_OuterBlade.

```
<li Class="PatchOperationAdd">
	<xpath>Defs/HediffDef[defName="Trunken_hediff_OuterBlade"]/stages</xpath>
		<value>
			<li>
				<minSeverity>0.000001</minSeverity>
				<statOffsets>
					<MeleeDodgeChance>0.4</MeleeDodgeChance>
					<MeleeCritChance>0.14</MeleeCritChance>
					<MeleeParryChance>0.4</MeleeParryChance>
				</statOffsets>
			</li>
		</value>
</li>
```

Replacing the current PatchOperationAdd with the above worked for me. Idk if anything else needs changing. (Not doing a PR cause I am bad at git from what it looks like...) 
**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
Resolved by #567.
