### ISSUE TITLE
[Bug]:EMP does not stun turrets

### ISSUE THREAD

**Issue by Tostov** [CombatExtended-Continued/CombatExtended#643]
**Specifications**

Rimworld version:  1.2
Combat Extended version: 1.2.3.6
Combat Extended source (Steam, GitHub, etc.):
Your operating system: Windows
Your mod list:

**Description**
EMP is unable to stun turrets, regardless of if they're player, enemy or mechanoid turrets.

**Expected behavior**
EMP stuns the turrets without adaption

**To reproduce**
Start a new game, spawn in a mech cluster or powered turrets, slap it with the EMP tool. EMP shotgun rounds will also have no effect.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Breadbox2k19** [comment]
Apparently, Emp no longer breaks mech low shields either, probably doesn't work on other types of shields too.
