### ISSUE TITLE
[Patch Request]: Vanilla Weapons Expanded - Frontier

### ISSUE THREAD

**Issue by Ezequiel-0052** [CombatExtended-Continued/CombatExtended#644]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**

**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**

**Title should be:** [Patch Request]: (Mod Name)

**Mod name:** Vanilla Weapons Expanded - Frontier

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2454918139#:~:text=This%20mod%20is%20NOT%20YET%20CE%20compatible.

**Description:**
Provide a brief overview of what content the mod adds or modifies. Specify what content in particular you believe require a patch to be compatibly with Combat Extended. It adds a bunch of new weapons. Apparently the Derringer isnt compatible since it doesnt show a bar displaying how much ammo is left on the gun, like with other ce weapons. I assume this isnt the only gun incompatible with ce

**Content:**
What does the new mod contain? Check all that apply.
- [X] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Rebootableglitch** [comment]
it was patched in the latest update of combat extended....
