### ISSUE TITLE
[Bug]: Exception spam with Remove Spacer Stuff (Continued)

### ISSUE THREAD

**Issue by Waether** [CombatExtended-Continued/CombatExtended#646]
Rimworld version: 1.2.2900
Combat Extended version: 1.2.3.2 from Mod manager (Steam desc says 1.2.3.6)
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list: https://pastebin.com/Y3HPfJDr

**Description**

I just installed [Remove Spacer Stuff (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2260590151)
This mod removes spacer factions from the game, including mechanoids, which causes an exception to be thrown every tick.

<details>
  <summary>Exception being thrown</summary>

```C#
System.NullReferenceException: Object reference not set to an instance of an object
  at CombatExtended.LetterTracker.MapComponentTick () [0x0001a] in <c8aecfc8eba541749ed1af0e489ba13a>:0 
  at Verse.MapComponentUtility.MapComponentTick (Verse.Map map) [0x00013] in <c36f9493c9844ddaa7fb5c788416098f>:0 
Verse.Log:Error(String, Boolean)
Verse.MapComponentUtility:MapComponentTick(Map)
Verse.Map:MapPostTick()
Verse.TickManager:Verse.TickManager.DoSingleTick_Patch1(TickManager)
Verse.<>c:<LoadGame>b__59_1()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent()
Verse.LongEventHandler:LongEventsUpdate(Boolean&)
Verse.Root:Verse.Root.Update_Patch1(Root)
Verse.Root_Play:Update()
```

</details>

I took a quick look at CE's code and i'm pretty sure it comes from [LetterTracker.cs](https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/Source/CombatExtended/CombatExtended/LetterTracker.cs) at l.18. 

Faction.OfMechanoids or Faction.OfMechanoids.def is probably null since [Remove Spacer Stuff (Continued)](https://steamcommunity.com/sharedfiles/filedetails/?id=2260590151) removes the faction.

A null check or try catch would probably do, but my specialty isn't exactly C# programming.

**Screenshots & log dumps**
Hugs Logs keep failing to upload, I can provide rimworld logs if needed.

I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Alicecomma** [comment]
Some things:

1. LetterTracker shouldn't be a MapComponent, it should be a GameComponent (introduced recently)
2. Should check Find.TickManager.TicksGame % 2000 == 0
3. Should nullcheck Find.AnyPlayerHomeMap != null
4. Should nullcheck Faction.OfMechanoids != null

Fixing 1. might break saves unless it's possible to handle this. The rest is trivial.
