### ISSUE TITLE
[Bug]: Combat Extended creates Error with NewRatkinPlus(CE compatible)

### ISSUE THREAD

**Issue by pocongmaster** [CombatExtended-Continued/CombatExtended#660]
[Bug]: Combat Extended creates Error with NewRatkinPlus(CE compatible)

**Specifications**

Rimworld version:
Combat Extended version: 1.2 v3.6
Combat Extended source (Steam, GitHub, etc.): Steam, Github
Your operating system:
Your mod list:
[Mod list length: 20]
Harmony [https://steamcommunity.com/sharedfiles/filedetails/?id=2009463077]
Core [https:// no link (local mod)]
Royalty [Official DLC] [https:// no link (local mod)]
HugsLib [https://steamcommunity.com/sharedfiles/filedetails/?id=818773962]
JecsTools (Unofficial) [https://steamcommunity.com/sharedfiles/filedetails/?id=2195729899]
Humanoid Alien Races 2.0 [https://steamcommunity.com/sharedfiles/filedetails/?id=839005762]
What the hack?! [https://steamcommunity.com/sharedfiles/filedetails/?id=1505914869]
Giddy-up! Core [https://steamcommunity.com/sharedfiles/filedetails/?id=1216999901]
Giddy-up! Battle Mounts [https://steamcommunity.com/sharedfiles/filedetails/?id=1217001091]
Giddy-up! Caravan [https://steamcommunity.com/sharedfiles/filedetails/?id=1253251478]
Giddy-up! Mechanoids [https://steamcommunity.com/sharedfiles/filedetails/?id=1518932357]
Giddy-up! Ride and Roll [https://steamcommunity.com/sharedfiles/filedetails/?id=1331961995]
Combat Extended [https://steamcommunity.com/sharedfiles/filedetails/?id=1631756268]
NewRatkinPlus [https://steamcommunity.com/sharedfiles/filedetails/?id=1578693166]
Character Editor [https://steamcommunity.com/sharedfiles/filedetails/?id=1874644848]
[KV] Show Hair With Hats or Hide All Hats [https://steamcommunity.com/sharedfiles/filedetails/?id=1180826364]
Android tiers [https://steamcommunity.com/sharedfiles/filedetails/?id=1386412863]
Psychology (unofficial 1.1/1.2)  [https://steamcommunity.com/sharedfiles/filedetails/?id=2016263135]
What's That Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2258431182]
RocketMan - Performance Mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2479389928]

**Description**
Red error appears when loading up CE with NewRatkinPlus eventhough it is perfectly compatible previously. CE should patched out RK_LongSword, RK_FlechetteRifle, and RK_SniperRifle. It turns out to be buggy mess.

**Expected behavior**
CE should patches these weapons out flawlessly. Patching out weapons should work as expected.

**To reproduce**
Just put CE alongside NewRatkinPlus

**Screenshots & log dumps**
Could not resolve cross-reference to Verse.ThingDef named RK_LongSword (wanter=weaponList)
Verse.Log:Error(String, Boolean)
Verse.DirectXmlCrossRefLoader:TryResolveDef(String, FailMode, Object)
Verse.WantedRefForList`1:TryResolve(FailMode)
Verse.<>c__DisplayClass15_1:<ResolveAllWantedCrossReferences>b__0(WantedRef)
Verse.<>c__DisplayClass6_1`1:<ParallelForEach>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

Could not resolve cross-reference to Verse.ThingDef named RK_FlechetteRifle (wanter=weaponList)
Verse.Log:Error(String, Boolean)
Verse.DirectXmlCrossRefLoader:TryResolveDef(String, FailMode, Object)
Verse.WantedRefForList`1:TryResolve(FailMode)
Verse.<>c__DisplayClass15_1:<ResolveAllWantedCrossReferences>b__0(WantedRef)
Verse.<>c__DisplayClass6_1`1:<ParallelForEach>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

Could not resolve cross-reference to Verse.ThingDef named RK_FlechetteSniperRifle (wanter=weaponList)
Verse.Log:Error(String, Boolean)
Verse.DirectXmlCrossRefLoader:TryResolveDef(String, FailMode, Object)
Verse.WantedRefForList`1:TryResolve(FailMode)
Verse.<>c__DisplayClass15_1:<ResolveAllWantedCrossReferences>b__0(WantedRef)
Verse.<>c__DisplayClass6_1`1:<ParallelForEach>b__0(Object)
System.Threading.QueueUserWorkItemCallback:WaitCallback_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.QueueUserWorkItemCallback:System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
System.Threading.ThreadPoolWorkQueue:Dispatch()
System.Threading._ThreadPoolWaitCallback:PerformWaitCallback()

**Complete the following checklist**
I hereby verify that I have done the following:
- [v] Confirmed that my game version and load order are correct.
- [v] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [v] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [v] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Fixed by #684.
