### ISSUE TITLE
[Bug]: Races Unable to Manually Reload

### ISSUE THREAD

**Issue by Xcallono** [CombatExtended-Continued/CombatExtended#711]
**Specifications**
Rimworld version:1.2.3005 revision 1190
Combat Extended version: 1.2.3.6 Steam
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system:Windows 10 64-bit, Home Edition, Build 19042
Your mod list: (In order) Harmony(before Core and Royalty), Combat Extended, Combat Extended Guns, Combat Extended Melee, Vulpes - Adorable Foxes! [1.2], Humanoid Alien Races, RimBees, BeeGirl Race: RimBees Addon, Ferian Race, HugsLib, Pawnmorpher, JecsTools(Unofficial), Explorite Core, The Human Hive, Fallout Races: Playable Ghouls(Continued), Anthro Race, RimCentaurs, Ferrex Race(Continued), Epona Race, Foxbold Race, Lombax - Desert Warriors, Clay Soldier Race, [SYR] Harpy, [SYR] Thrumkin, [SYR] Naga, Vanilla Expanded Framework, Fallout Races: The Robots Pack (Continued), Nyaron_Race_zh, De-generalize Work, Logann Race (Continued), Racc Race (Continued), Vulpine Race (Continued), Skrix - An Insect-like Race, Xenn Race (Continued), Androids. (Addendum:I forgot to list Kurin HAR edition, I don't know how I missed it but it's in the mix.)

**Description**
In short, while humans and a select few other mods have been unaffected(a list of race mods is provided in the expected behavior for convenience), the ammunition counter and reload button are missing. All races are Humanoid Alien Race 2.0 based.

**Expected behavior**
I'd expect for the ammunition counter to be visible and for the reload button to be available. The races affected are [Anthro Races](https://steamcommunity.com/sharedfiles/filedetails/?id=2455173560), [Centaur Race](https://steamcommunity.com/sharedfiles/filedetails/?id=2384815374), [Frijjid and Fenii races](https://steamcommunity.com/sharedfiles/filedetails/?id=2263865049), [Human hive](https://steamcommunity.com/sharedfiles/filedetails/?id=2222668862), [Foxbold Race](https://steamcommunity.com/sharedfiles/filedetails/?id=2438217201), [Skrix race](https://steamcommunity.com/sharedfiles/filedetails/?id=2267078474), Tieflings(not tested, reported by [zombie_mimic](https://steamcommunity.com/workshop/filedetails/discussion/1631756268/1743358239844788840/?ctp=20#c3114770279415040126)), [Beegirls](https://steamcommunity.com/sharedfiles/filedetails/?id=2437912777), [Kurin race](https://steamcommunity.com/sharedfiles/filedetails/?id=2326430787).

**To reproduce**
- Enter debug mode
- Start a new game
- Spawn a Lee Enfield and 25 .303 British rounds(any type)
- Spawn pawn
- Pick up Lee Enfield and .303
- Look at the bottom-lefthand side corner

**Screenshots & log dumps**
Testing Setup:https://imgur.com/a/2UR2QWu
Starting log:https://pastebin.com/Ex7dytt2
I forgot to grab the logs during the testing setup so here's a makeup for that.
Human and Skrix test:https://pastebin.com/wpHqFbKL

Save file:https://www.mediafire.com/file/h0f6aqjxcmy3d6u/Testing+Save.rws/file

**Complete the following checklist**
I hereby verify that I have done the following:
- [S] Confirmed that my game version and load order are correct.
- [?] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
I could not find any pre-existing patches for these mods.
- [?] Confirmed I am not running any mods with known incompatibilities with Combat Extended. 
None of these mods list incompatibility with CE but they sort of are.
- [S] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Xcallono** [comment]
It should be noted that they can reload automatically just fine, pick up ammunition, and fire like normal. They just can't switch their ammunition type, and can't reload manually. What I'd suggest is to have, on the drop down menu of the weapon, a reload option as well. It's a quick and dirty work around, but it will fix the gameplay issues in the interim.

**Comment by Breadbox2k19** [comment]
This isn't a bug, the race that you are using is unpatched. I suggest closing this and opening a patch request for the unpatched races you re using.
The ones without reload or change ammo button are definitely unpatched.

**Comment by Xcallono** [comment]
> This isn't a bug, the race that you are using is unpatched. I suggest closing this and opening a patch request for the unpatched races you re using.
> The ones without reload or change ammo button are definitely unpatched.

Except, they ARE patched. I know this because Kurin HAR has been patched for ages at the request of a friend, and it just recently broke.

**Comment by Xcallono** [comment]
I wish to now submit [Equiums Anything Goes](https://steamcommunity.com/sharedfiles/filedetails/?id=1774876106) as additionaly evidence of a growing problem. CE support was implemented by the developer of the mod, but they too cannot reload ammunition.

**Comment by Breadbox2k19** [comment]
Both of these races aren't patched on the CE side, it is due to botched CE patches on their side. I'll take a look when I have the time but do note that internal patches take priority.

**Comment by Breadbox2k19** [comment]
I think I know what is going on, those races must have being using a different basepawn, since CE only patches the base game's basepawn, any added by mods is going to be unpatched.
