### ISSUE TITLE
[Bug]: Patch operation Verse.PatchOperationFindMod(Vanilla Armour Expanded) failed

### ISSUE THREAD

**Issue by Luna5225** [CombatExtended-Continued/CombatExtended#732]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
From the Debug Log at startup:

> [Combat Extended] Patch operation Verse.PatchOperationFindMod(Vanilla Armour Expanded) failed
file: C:\Program Files (x86)\Steam\steamapps\workshop\content\294100\1631756268\Patches\Vanilla Armour Expanded\ThingDefs_Misc\Armor_Footwear.xml
Verse.Log:Error(String, Boolean)
Verse.PatchOperation:Complete(String)
Verse.LoadedModManager:ClearCachedPatches()
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Rimworld version: 
RimWorld 1.2.3005 rev1190

Combat Extended version:
V3.6
Combat Extended source (Steam, GitHub, etc.):
Steam first
Then Github

Your operating system: 
Windows 10 x64

Your mod list:
- Id: brrainz.harmony
  Name: Harmony
- Id: me.samboycoding.betterloading
  Name: BetterLoading
- Id: ludeon.rimworld
  Name: Core
- Id: mlie.modcheck
  Name: ModCheck (Continued)
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: fluffy.modmanager
  Name: Mod Manager
- Id: unlimitedhugs.hugslib
  Name: HugsLib
- Id: oskarpotocki.vanillafactionsexpanded.core
  Name: Vanilla Expanded Framework
- Id: vanillaexpanded.achievements
  Name: Vanilla Achievements Expanded
- Id: vanillaexpanded.vaeas
  Name: Vanilla Animals Expanded — Arid Shrubland
- Id: vanillaexpanded.vaeau
  Name: Vanilla Animals Expanded — Australia
- Id: vanillaexpanded.vaebf
  Name: Vanilla Animals Expanded — Boreal Forest
- Id: vanillaexpanded.vaecd
  Name: Vanilla Animals Expanded — Cats and Dogs
- Id: vanillaexpanded.vaed
  Name: Vanilla Animals Expanded — Desert
- Id: vanillaexpanded.vaeendandext
  Name: Vanilla Animals Expanded — Endangered
- Id: vanillaexpanded.vaeed
  Name: Vanilla Animals Expanded — Extreme Desert
- Id: vanillaexpanded.vaeis
  Name: Vanilla Animals Expanded — Ice Sheet
- Id: vanillaexpanded.vaetf
  Name: Vanilla Animals Expanded — Temperate Forest
- Id: vanillaexpanded.vaetr
  Name: Vanilla Animals Expanded — Tropical Rainforest
- Id: vanillaexpanded.vaets
  Name: Vanilla Animals Expanded — Tropical Swamp
- Id: vanillaexpanded.vaet
  Name: Vanilla Animals Expanded — Tundra
- Id: vanillaexpanded.vappe
  Name: Vanilla Apparel Expanded
- Id: vanillaexpanded.vaeaccessories
  Name: Vanilla Apparel Expanded — Accessories
- Id: vanillaexpanded.varme
  Name: Vanilla Armour Expanded
- Id: vanillaexpanded.vbookse
  Name: Vanilla Books Expanded
- Id: vanillaexpanded.vbrewe
  Name: Vanilla Brewing Expanded
- Id: vanillaexpanded.vbrewecandt
  Name: Vanilla Brewing Expanded - Coffees and Teas
- Id: vanillaexpanded.vcooke
  Name: Vanilla Cooking Expanded
- Id: vanillaexpanded.vcookestews
  Name: Vanilla Cooking Expanded - Stews
- Id: vanillaexpanded.vcef
  Name: Vanilla Fishing Expanded
- Id: vanillaexpanded.vcookesushi
  Name: Vanilla Cooking Expanded - Sushi
- Id: vanillaexpanded.vee
  Name: Vanilla Events Expanded
- Id: oskarpotocki.vanillaexpanded.royaltypatches
  Name: Vanilla Expanded - Royalty Patches
- Id: oskarpotocki.vfe.insectoid
  Name: Vanilla Factions Expanded - Insectoids
- Id: oskarpotocki.vfe.mechanoid
  Name: Vanilla Factions Expanded - Mechanoids
- Id: legodude17.vfemechscp
  Name: Vanilla Factions Expanded - Mechanoids - Auto-Mortar Shell Choice Patch
- Id: vanillaexpanded.vwe
  Name: Vanilla Weapons Expanded
- Id: oskarpotocki.vanillafactionsexpanded.medievalmodule
  Name: Vanilla Factions Expanded - Medieval
- Id: oskarpotocki.vanillafactionsexpanded.settlersmodule
  Name: Vanilla Factions Expanded - Settlers
- Id: oskarpotocki.vfe.vikings
  Name: Vanilla Factions Expanded - Vikings
- Id: vanillaexpanded.vcefaddon
  Name: Vanilla Fishing Expanded - Fishing Treasures AddOn
- Id: vanillaexpanded.vfecore
  Name: Vanilla Furniture Expanded
- Id: vanillaexpanded.vfeart
  Name: Vanilla Furniture Expanded - Art
- Id: vanillaexpanded.vfefarming
  Name: Vanilla Furniture Expanded - Farming
- Id: vanillaexpanded.vfemedical
  Name: Vanilla Furniture Expanded - Medical Module
- Id: vanillaexpanded.vfepower
  Name: Vanilla Furniture Expanded - Power
- Id: vanillaexpanded.vfeproduction
  Name: Vanilla Furniture Expanded - Production
- Id: vanillaexpanded.vfesecurity
  Name: Vanilla Furniture Expanded - Security
- Id: vanillaexpanded.vfespacer
  Name: Vanilla Furniture Expanded - Spacer Module
- Id: vanillaexpanded.vhe
  Name: Vanilla Hair Expanded
- Id: vanillaexpanded.vhe.beards
  Name: Vanilla Hair Expanded - Beards
- Id: vanillaexpanded.vplantse
  Name: Vanilla Plants Expanded
- Id: vanillaexpanded.vplantsesucculents
  Name: Vanilla Plants Expanded - Succulents
- Id: zodgilla.vanillarangedretexture
  Name: Vanilla Ranged Retexture
- Id: vse.diegoindustrial
  Name: Vanilla Storytellers Expanded - Diego Industrial
- Id: vse.neronneolithic
  Name: Vanilla Storytellers Expanded - Neron Neolithic
- Id: vse.perrypersistent
  Name: Vanilla Storytellers Expanded - Perry Persistent
- Id: vanillaexpanded.vtexe
  Name: Vanilla Textures Expanded
- Id: vanillaexpanded.vtexvariations
  Name: Vanilla Textures Expanded - Variations
- Id: vanillaexpanded.vanillatraitsexpanded
  Name: Vanilla Traits Expanded
- Id: vanillaexpanded.vwec
  Name: Vanilla Weapons Expanded - Coilguns
- Id: vanillaexpanded.vweq
  Name: Vanilla Weapons Expanded - Quickdraw
- Id: vanillaexpanded.vwel
  Name: Vanilla Weapons Expanded - Laser
- Id: vanillaexpanded.vwehw
  Name: Vanilla Weapons Expanded - Heavy Weapons
- Id: vanillaexpanded.vweft
  Name: Vanilla Weapons Expanded - Frontier
- Id: vanillaexpanded.vweg
  Name: Vanilla Weapons Expanded - Grenades
- Id: vanillaexpanded.vwems
  Name: Vanilla Weapons Expanded - Makeshift
- Id: vanillaexpanded.vwenl
  Name: Vanilla Weapons Expanded - Non-Lethal
- Id: vanillaexpanded.vwetb
  Name: Vanilla Weapons Expanded - Tribal
- Id: ceteam.combatextended
  Name: Combat Extended
- Id: co.uk.epicguru.whatsthatmod
  Name: What's That Mod
- Id: krkr.rocketman
  Name: RocketMan - Performance Mod

**Description**
When I loaded up the game, I received two errors from CE stating they were missing patch files

**Expected behavior**
The patches would be found

**To reproduce**
Subscribe to VE Collection in Steam Workshop
Subscribe to CE in Steam Workshop
Load Mods VE first then CE
Restart Game

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

**Complete the following checklist**
I hereby verify that I have done the following:
- [ x] Confirmed that my game version and load order are correct.
- [x ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Already fixed in dev branch, but thank you for the report.
