### ISSUE TITLE
[Discussion]: Lp-programming is too unstable. Would you please release more builds.

### ISSUE THREAD

**Issue by jinlan** [CombatExtended-Continued/CombatExtended#743]
I tried many times to download from lp-programming.com. It's so hard to successfully download it.
Would you please provide a build maybe once every month?
Or would you please just provide a build?

**Comment by sumghai** [comment]
The latest CE releases are always available from https://github.com/CombatExtended-Continued/CombatExtended/releases, or Steam Workshop.

Why are you using an unauthorized third-party site?

**Comment by perkinslr** [comment]
As sumghai says, the latest release build is always available on the releases tab.  We issue new releases about once a month, usually (there should be a new one coming up here soon).  

`combatextended.lp-programming.com` is used for hosting PR test builds for our playtesters, and the current state of the development branch.  It *should* be reasonably stable going forward, but I was MIA for a while and it choked.

That said, it is easy enough to add mirrors for hosting, so if you have suggestions, we are open to them.  There are some requirements which make finding hosting a bit of a challenge.

1. It's free.  This is a hobby project which generates 0 revenue, so we really can't be paying for hosting.
2. It can have a simple third-level-domain pointed at it.  No large opaque URLs, it needs to be easy to verify the URL is one of ours.  Something like example.com/combatextended/ would also be acceptable.
3. Uploading to the host needs to be possible via some public key system (scp/sftp/rsync).
4. Uploading to the host needs to *only* be possible with a repository secret.
5. The host needs to require 0 maintenance and not turn into a botnet.

Anyway, if you have suggestions that meet those criteria, you can mention them here.  Or you can open a PR against the CI files.
