### ISSUE TITLE
[Discussion]: Removing smoke in mountains

### ISSUE THREAD

**Issue by exuvo** [CombatExtended-Continued/CombatExtended#75]
**Specifications**
Unable to get rid of smoke in mountain bases in a reasonable timeframe.

Rimworld version: 1.1
Combat Extended version: Latest
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windowx 7 x64
Your mod list: unrelated

**Description**
Had largish fire in a mountain base. Opened all doors since last year but smoke still remains in smaller quantities (100-1000ppm) and slow down renderer noticably ca 5ms from CombatExtended.Smoke when looking at base as it has spread out over the whole base.

**Expected behavior**
A building that filters nearby smoke or something to handle this in mountain bases where i cant just remove the roof or side walls to open to outside. The smoke has lasted more than a year now.

Suggestions on how to remove smoke in mountains is appreciated.

**To reproduce**
Start fire in large mountain base where outside is far from where the fire is.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by exuvo** [comment]
No idea why this was marked bug, it is not.

**Comment by Juanfrank** [comment]
Maybe make mountainbase roofs have a hidden passive smoke-destroying capability?

**Comment by exuvo** [comment]
That could work but seems a bit cheaty, I think something that the player has to actively do/build would be more engaging.

For now i just dug a long wide channel to the outside and have almost gotten rid of the smoke now another 2 quarters further along, but total time is going to have been like 2 years.

**Comment by Juanfrank** [comment]
Objectively speaking, smoke doesn't linger forever. In fact, given enough time, it'll just convert into dust and adhere to surfaces, thereby not affecting people's lungs.

**Comment by Breadbox2k19** [comment]
How about just making all smoke disappear after a few days time regardless of where it is?

**Comment by exuvo** [comment]
That would work, just not too short or gas masks wont be used.

**Comment by Azumgi** [comment]
I think the perfect solution balance-wise would be a new researchable re-mountable furniture item called "Air Purifier" that would act the same way as a roof hole. But additionally requiring power and maintenance.
![image](https://user-images.githubusercontent.com/35058624/82759860-8e1df680-9df8-11ea-8d55-5d381ca5cdd1.png)

**Comment by Alicecomma** [comment]
https://github.com/CombatExtended-Continued/CombatExtended/discussions/791#discussioncomment-1128334

**Comment by perkinslr** [comment]
This has been solved (as of CE 4.4 or 4.5).  Smoke now slowly transforms into filth, which handles smoke in sealed rooms.
