### ISSUE TITLE
[Bug]:Gear tab not showing apparel or weapon

### ISSUE THREAD

**Issue by sloppybroth** [CombatExtended-Continued/CombatExtended#76]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: Gear tab not showing apparel or weapon

**Specifications**Gear tab not showing apparel or weapon
Please provide the following.

Rimworld version:1.12575
Combat Extended version:1.1.2.1
Combat Extended source (Steam, GitHub, etc.):Steam
Your operating system:32 bit windows 7 ultimate OS 8Gb RAM intel hd graphics card
Your mod list:Harmony,Core,Royalty,Hugslib,RTfuse,RimFridge,RimHUD,pick up and haul,pharmacist,medical tab,interaction bubble dubs bad hygeine,harvest organs post mortem,edb prepare carefully,reunion,vanilla furniture expanded-security,wall light,combat extended

**Description**
after equipping guns or melee weapons they do not display in the gear section though bulk and mass change

**Expected behavior**
 expected to see guns and melee weapons loaded

**To reproduce**
 just start up a new save game

**Screenshots & log dumps**
 https://gist.github.com/561fbe53bd3644bcb706e47c046f2027

**Complete the following checklist**
I hereby verify that I have done the following:
- [ Yes] Confirmed that my game version and load order are correct.
- [ Yes] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [Yes ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [Yes ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
> 32 bit windows 7
Combat Extended does not support 32 bit systems, I'm afraid.
