### ISSUE TITLE
[Bug]: Vanilla Weapons Expanded - Grenades has a patch, but it still throws up an error:

### ISSUE THREAD

**Issue by Caminha** [CombatExtended-Continued/CombatExtended#761]
When using the latest versions of both mods the game throws up

>Config error in VWE_Apparel_GrenadeTearGasBelt: verb 0: has incorrect forcedMiss settings; explosive projectiles and only explosive projectiles should have forced miss enabled

VWE-Grenades is included in the [Supported Third-Party Mods list](https://github.com/CombatExtended-Continued/CombatExtended/blob/Development/SupportedThirdPartyMods.md), so I believe the patch needs to be tweaked/updated.

**Comment by LeriWeill** [comment]
Yeah the Tear Gas Belt is a very recent addition to the Grenades mod, if you have both Grenades and Non-Lethal loaded.
