### ISSUE TITLE
[Patch Request]: D4egons Magic Wand

### ISSUE THREAD

**Issue by d4egon** [CombatExtended-Continued/CombatExtended#773]
**[Patch Request]: D4egonsMagicWand**

**Mod Name: D4egonsMagicWand**

**Download: https://github.com/d4egon/MagicWands/tree/main**

**Description: **
The mod adds several custom weapons to the game including the use of bullet and explosive tags. (There are some plants, stuffable things and a workbench aswell). 

I believe the ammo for this mod should be crafted at the Infusion Bench as it would make more sense. The wands all have ranged and melee attacks which needs compatibility.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Breadbox2k19** [comment]
Will take a look, but released mods generally takes priority.

**Comment by d4egon** [comment]
I have gone and made the patch myself Will push it
