### ISSUE TITLE
[Bug]: Turrets not firing with disabled ammo system

### ISSUE THREAD

**Issue by kesrith** [CombatExtended-Continued/CombatExtended#78]
Rimworld version: 1.1.2618
Combat Extended version:  1.1.2.1
Combat Extended source (Steam, GitHub, etc.): Steam workshop
Your operating system: Win10
Your mod list:
Harmony
Rimworld Main
Royals DLC
Combat Extended

**Description**
Building a turret when disabling the ammo system in the options makes them unable to shoot. They ignore enemies and the log gets flooded with the error posted below. The error does not occur if the ammo system is enabled

**Expected behavior**
The turret shoots without requiring any ammo.

**To reproduce**
Start a new game
Spawn any turret or give yourself the resources and tech to build them. 
Watch them sit idle while enemies approach

**Screenshots & log dumps**
https://pastebin.com/9eMep7Sf

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by jeffmon** [comment]
I'm having the same issue. When this is happening, my pawns won't clean and I get this in the log:

`CE - MakeReloadJobNoAmmo() (3559010) - Tried to create a reload job on a thing that's not reloadable.`

If I dismantle the turrets, they start cleaning again.

**Comment by Dr-Slump** [comment]
See #98  and #112 .
(apologies, I missed your bug report before I filed mine)

**Comment by N7Huntsman** [comment]
As stated above, should be fixed by Dr-Slump's recent PRs.
