### ISSUE TITLE
[Bug]: Blunt Melee AP Calculated Incorrectly.

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#780]
From the Melee spreadsheet, I've found that currently blunt AP is calculated incorrectly. Due to what I suspect to be a formatting error in the sheet, the blunt AP is taken directly from the calculated Force, and the contact area is not factored in.

This means weapons with low contact areas (like blades) have artificially low Blunt AP while weapons with higher contact areas (like clubs) has artificially high blunt AP.

When I get the opportunity, I'll do a comprehensive check of the physics behind the melee stuff and make adjustments as necessary.

**Comment by Breadbox2k19** [comment]
I doubt following the sheets too closely is wise, blunt weapons has trouble stuff going through most stuff as it is. They can't damage things that they should be able to go through(armour vest).
Don't really want to see them as useless as sharp melee.

**Comment by N7Huntsman** [comment]
Since I'm currently going through various open Issues, I'll leave a note for posterity on this particular problem:

The physics for the melee force calculations are indeed incorrect. However, some napkin math indicates this would (with out current input values) significantly decrease blunt AP. Though, these are also likely a result of some very 'best-guess' values for things like contact area and speed.

Given the enormous cascade of xml work these changes would cause and the overall negative balance implications, this issue is more or less baked-in.
