### ISSUE TITLE
[Bug]: head apparel rendered as a pink box due to missing _Female textures

### ISSUE THREAD

**Issue by Tourman36** [CombatExtended-Continued/CombatExtended#79]
Rimworld version: 1.1.2618
Combat Extended version: 1.1 April 22nd
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win10 and Manjaro Linux both exhibit the same issue
Your mod list:
```
brrainz.harmony
Ludeon.RimWorld
Ludeon.RimWorld.Royalty
UnlimitedHugs.HugsLib
CETeam.CombatExtended
erdelf.HumanoidAlienRaces
ssulunge.BBBodySupport
ssulunge.BBBodyHuman
velc.HatsDisplaySelection
Ryflamer.HDPawnTextures.HAR
ssulunge.KijinRace2
Atlas.AndroidTiers
aRandomKiwi.AndroidTiersTXSerie
Xeva.XevaFBpack.11
Nals.FacialAnimation
smashphil.boats
notfood.MendAndRecycle
telefonmast.graphicssettings
LingLuo.LovelyHairStyle
Rooboid127.RooOsHAccessoryHHairstyles
Ogre.OgreStack
Dubwise.DubsBreakMod
Dubwise.DubsBadHygiene
Uuugggg.TDPack
avilmask.GrazingLands
SoulfulPumpkin.TabletopTrove
Uuugggg.UseBedrolls
Uuugggg.EverybodyGetsOne
Krafs.LevelUp
Cocaine.ElectricStonecuttingTable
Murmur.WallLight
Murmur.UVWallLight
pelador.brrrandphew
kikohi.cybernetic
Rah.RBSE
pelador.drugresponse
pelador.medicalsupplements
automatic.bionicicons
Proxyer.DESurgeries.DESurgeriesColor
Proxyer.DESurgeries.KijinPatch
dismarzero.VGP.VGPVegetableGarden
dismarzero.VGP.VGPGardenCanning
dismarzero.VGP.VGPGardenFabrics
fluffy.fluffybreakdowns
fluffy.pharmacist
fluffy.medicaltab
fluffy.researchtree
fluffy.blueprints
fluffy.worktab
fluffy.spatialpriorities
VanillaExpanded.VARME
HALO.RSF
VanillaExpanded.VCEF
VanillaExpanded.VAPPE
VanillaExpanded.VTEXE
VanillaExpanded.VHE
VanillaExpanded.VAETR
VanillaExpanded.VAEIS
VanillaExpanded.VAEAU
VanillaExpanded.VAEBF
VanillaExpanded.VAET
VanillaExpanded.VAEED
VanillaExpanded.VAED
VanillaExpanded.VAECD
VanillaExpanded.VAETS
VanillaExpanded.VAEAS
VanillaExpanded.VFECore
VanillaExpanded.VFEProduction
VanillaExpanded.VFESecurity
VanillaExpanded.VFEMedical
VanillaExpanded.VFEFarming
VanillaExpanded.VFEArt
VanillaExpanded.VFESpacer
VanillaExpanded.VWE
VanillaExpanded.VWEQ
VanillaExpanded.VWEL
zodgilla.vanillameleeretexture
syrchalis.setupcamp
syrchalis.prosthetictable
kikohi.jewelry
notfood.Outfitted
Techmago.BootsnStuff
PeteTimesSix.SimpleSidearms
Sandy.RPGStyleInventory
Jaxe.RimHUD
RadZerp.wallCorners
Jaxe.PawnRules
Shotgunfrenzy.PriorityTreatment
Jaxe.Bubbles
Community.Psychology.UnofficialUpdate
mobius.royaltytweaks
neceros.oreyields
nephlite.orbitaltradecolumn
LWM.DeepStorage
JangoDsoul.SimplyStorage
aRandomKiwi.PowerPP
BiomesTeam.BiomesCore
BiomesTeam.BiomesIslands
changedresser.kv.rw
Dubwise.DubsPerformanceAnalyzer
```

**Description**
Provide a concise description of the issue or concern. What happened? When using a mod that uses FemaleBB BodyType Support, head apparel textures are rendered with a pink box. 

The issue is that CE is looking for _Female version of specific textures but they don't exist. The FemaleBB BodyType author said this had been previously fixed in 1.0.

**Expected behavior**
What did you expect to happen? Head apparel textures should be rendered.

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen? Easiest way to reproduce is to load CE, FemaleBB BodyType Support and Vanilla Armor Expanded - however VAE is not the root cause of this issue, but since includes many head armor graphics, it's the easiest to reproduce with.

Load order does not make a difference - e.g. loading CE before or after FemaleBB does not fix the issue.

**Screenshots & log dumps**
Whenever possible, add screenshots to help explain your problem, and share error or crash logs to make our jobs easier. For logs, please enter the logs into a pastebin site (e.g pastebin.com, justpasteit.com, etc.) 
and provide a link. Do not paste the entire log here. 

```
Failed to find any textures at Things/Pawn/Humanlike/Apparel/CowboyHat/CowboyHat_Female while constructing Multi(initPath=Things/Pawn/Humanlike/Apparel/CowboyHat/CowboyHat_Female, color=RGBA(0.800, 0.800, 0.800, 1.000), colorTwo=RGBA(1.000, 1.000, 1.000, 1.000))

Exception drawing Anna: System.ArgumentNullException: Value cannot be null. 
```

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by MilanDierickGD** [comment]
Can confirm this to be happening with a cowboy hat crafted with linen cloth provided by the VGP Garden mods.

**Comment by MilanDierickGD** [comment]
I checked a couple of other hats & helmets, and it seems that the cowboy hat is the only one giving issues. I've got all the BB body mods and the KijinRace2 mod as well. Equipping any other hat or helmet works just fine.
