### ISSUE TITLE
[Bug]: Colonists can equip weapons biocoded to others.

### ISSUE THREAD

**Issue by N7Huntsman** [CombatExtended-Continued/CombatExtended#8]
**Complete the template below. Reports that do not follow the template will not be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**

Rimworld version: 1.1
Combat Extended version: 1.1.2.0
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10 x64

**Description**
Colonists can equip weapons biocoded to others in roundabout ways due to CE mechanics. Probably needs a check added for biocoding in these situations.

**Expected behavior**
Colonists should not be able to equip weapons biocoded to others.

**To reproduce**
Colonist can be told to 'pick up` the weapon into their inventory. The weapon can then be equipped by right clicking.
OR
Colonist will ignore biocoding when assigned a loadout.

**Complete the following checklist**
I hereby verify that I have done the following:
[x] Confirmed that my game version and load order are correct.
[x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
[x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
[x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by onigamii** [comment]
Closing, #28 has been merged.
