### ISSUE TITLE
[Bug]: Lasers do not suppress + Other bugs

### ISSUE THREAD

**Issue by Breadbox2k19** [CombatExtended-Continued/CombatExtended#805]
-All laser weapons do not cause any sort of suppression to hostile targets whatsoever.

-Another is issue, is that when a target is very big, all shots fired at the target will miss, if shooter is tall, all shot fired from it will also miss.

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Alicecomma** [comment]
- No suppression because the tiles between source and impact are never flashed on lasers.
- No large targets because laserbeams stop checking tiles when their y-value is larger than 2 (wall height).

**Comment by Breadbox2k19** [comment]
> * No suppression because the tiles between source and impact are never flashed on lasers.
> * No large targets because laserbeams stop checking tiles when their y-value is larger than 2 (wall height).

Pls consider fixing it.
