### ISSUE TITLE
[Bug]:Gear panel

### ISSUE THREAD

**Issue by HippityHop69** [CombatExtended-Continued/CombatExtended#822]
The gear panel is bugged it doesnt show anything

**Comment by HippityHop69** [comment]
![image](https://user-images.githubusercontent.com/87776492/126531720-6ecb07a7-1567-42cd-9a03-4df263c08fc0.png)

**Comment by Breadbox2k19** [comment]
You need to provide more info such as your load order and error messages.

**Comment by Breadbox2k19** [comment]
Closed as no relevant info is provided
