### ISSUE TITLE
[Bug]: No build instructions.

### ISSUE THREAD

**Issue by TashaSkyUp** [CombatExtended-Continued/CombatExtended#823]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.3
Combat Extended version: .13
Combat Extended source (Steam, GitHub, etc.): github
Your operating system: win10
Your mod list: doesn't matter.

**Description**
Please include build instructions.

**Expected behavior**
build.py fails

**To reproduce**
python build.py

**Comment by perkinslr** [comment]
If you run `python build.py --help` it will spit out the usage docstring.  

Generally, you can call `python build.py --all-libs --download-libs` and it will work.  (You can also point it at your local rimworld directory, or some other set of reference assemblies).

Note that it requires the mono compiler (`csc`) on your path.  I do not know if it will build with dotnet.  Nor do I know if it will work on windows (at the very least, it will require `wget` installed.  It *should* work if you have WSL or msys set up).  If it fails to build on windows, and you provide the traceback or error, I am willing to poke at it.

All that aside, you can use vs code or ms visual studio to build the project on windows.  Or you can call the dotnet command to build the project from the .csproj file.

**Comment by TashaSkyUp** [comment]
@perkinslr Thank you very much, can this be appended to readme.md?

**Comment by perkinslr** [comment]
That's probably not a bad idea...  I'll add a section for compiling on *nix systems.  We'll need to get someone who runs windows to write a section for compiling on windows.

**Comment by perkinslr** [comment]
Alright, you can find the build instructions in this branch: https://github.com/CombatExtended-Continued/CombatExtended/tree/add-build-instructions

I'll see if I can get someone on windows to add to it before opening a PR.
