### ISSUE TITLE
[Patch Request]: Erin's Wildlife

### ISSUE THREAD

**Issue by Draconomial** [CombatExtended-Continued/CombatExtended#835]
Mod name: Erin's Wildlife

https://steamcommunity.com/sharedfiles/filedetails/?id=2450520129

A casual collection of common critters to cohabitate with your colonists for community and cheer. Mods animals need compatibility with CE. Only seven mundane animals.

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [x] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Comment by N7Huntsman** [comment]
Done!
