### ISSUE TITLE
[Discussion]: Weapon recoil animation and reinforced barrel.

### ISSUE THREAD

**Issue by Breadbox2k19** [CombatExtended-Continued/CombatExtended#846]
Some vanilla features introduced in 1.3 aren't supported by CE.
A subtle recoil animation is added for all guns and mortars, I believe turret guns are affected as well, certain weapons should be except from this, such as laser weapons.
Reinforced barrels also doesn't do anything atm, perhaps it can be a crafting component for making a mortar that features better accuracy unspotted?

**Comment by N7Huntsman** [comment]
> Reinforced barrels also doesn't do anything atm, perhaps it can be a crafting component for making a mortar that features better accuracy unspotted?

They're required to build mortars, just like in vanilla. I suspect this was done by Tynan to reduce the habit of players amassing large batteries of mortars by the late game and simply shelling most all threats to oblivion before they can reach the player's colony. I don't know if this will actually help the issue (it's rather easy to collection mortars from beating sieges), but I don't see a compelling reason to remove the reinforced barrel as a building component from mortars.

**Comment by Alicecomma** [comment]
Adding recoil animation requires pre- or postfixing `// RimWorld.EquipmentUtility public static Verb_LaunchProjectile GetRecoilVerb(List<Verb> allWeaponVerbs)`
