### ISSUE TITLE
[Bug]: Pawns will not drop buildings from inventory

### ISSUE THREAD

**Issue by bpilgrim23** [CombatExtended-Continued/CombatExtended#847]
Please provide the following.

Rimworld version: 1.3.3069
Combat Extended version: 1.2.4
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list: Royalty/Ideology, Harmony, HugsLib, CE

**Description**
Provide a concise description of the issue or concern. What happened?
Ever since the 1.3 update pawns will not drop buildings from their inventory when ordered.

**Expected behavior**
What did you expect to happen?
When a pawn has a building in its inventory, and I order them to Drop or Drop and Haul it should remove the item from the inventory. They will drop items just fine but not buildings (furniture, turrets, etc).
![rimscreen](https://user-images.githubusercontent.com/26254696/126874656-24fe0992-0393-4f86-8f5d-7f585163039c.jpg)

**To reproduce**
Provide clear steps to reproduce the behavior. How do we make this happen?
1. Start new colony
2. Order pawn to make a bed
3. Uninstall bed
4. Order pawn to pick up bed
5. Order pawn to drop bed

**Screenshots & log dumps**
The key line seems to be this one:
Verse.Pawn_InventoryTracker container tried to drop  Bed11036 which it didn't contain.

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by N7Huntsman** [comment]
Should now be resolved in 1.3.4.0.1.
