### ISSUE TITLE
[Bug]: After returning a downed slave pawn to bed, they disappear and the UI disappears

### ISSUE THREAD

**Issue by booman246** [CombatExtended-Continued/CombatExtended#863]
**Specifications**
Please provide the following.

Rimworld version: 1.3.3071
Combat Extended version: 1.2.4.0
Combat Extended source (Steam, GitHub, etc.): Steam Workshop
Your operating system: Windows 10
Minimally reproducible mod list:

- Harmony
- CombatExtended

**Description**
After capturing (or arresting) an escaping slave pawn, the pawn in question disappears and various UI elements disappear. The bottom menus, item menus on the left, and controls at the bottom right all disappear. The pawn menu is still visible, and F-keys still open menus.

**Expected behavior**
Did not expect the UI or pawn to disappear

**To reproduce**
1. In a game, have a slave pawn.
2. Allow the slave pawn to escape
3. Capture the pawn
4. When you return the pawn to bed, they will disappear and your UI will disappear

**Screenshots & log dumps**
- didn't get an exception

**Complete the following checklist**
I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by DanilGritsenko** [comment]
Got the same issue in my game, as well as another person in Steam Workshop page's comments. Makes you reload a save whenever a rebellion happens.

**Comment by N7Huntsman** [comment]
Should now be resolved in 1.3.4.0.1.
