### ISSUE TITLE
[Bug]: NullReferenceException using comms console

### ISSUE THREAD

**Issue by MadEldar** [CombatExtended-Continued/CombatExtended#87]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version: 1.1.2598
Combat Extended version: 1.1.2.0
Combat Extended source (Steam, GitHub, etc.): RimworldBase
Your operating system: Windows 10
Your mod list: Pick Up And Haul, Combat Extended, More Vanilla Turrets, Work Tab, Progress Renderer.

**Description**
When I tried to use the comms console to call a combat supplier, the game froze for a second and nothing happened. Calling other factions still works.

**Expected behavior**
The usual trade screen should show up.

**To reproduce**
A random combat supplier trade ship not from any faction showed up. I don't know what they have in their inventory.

**Screenshots & log dumps**
Exception: https://pastebin.com/ZyrJJwfG
Screenshot: https://res.cloudinary.com/markskilink/image/upload/v1588999105/Screenshot_37_cdp5e4.png

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by MadEldar** [comment]
I just checked and see that on opening the game, there was an error log for cross reference of the Multibarrel Weapons research. Maybe one of the goods on the trade ship was the minigun and the NullReferenceException was trying to point to it.

Exception: https://pastebin.com/Vg2i2aBn
Screenshot: https://res.cloudinary.com/markskilink/image/upload/v1589038468/Screenshot_38_ful9r5.png

**Comment by N7Huntsman** [comment]
Likely related to #124 and #123
