### ISSUE TITLE
Pawns miss almost every shot / melee attack

### ISSUE THREAD

**Issue by Octofoxy** [CombatExtended-Continued/CombatExtended#874]
Playing on v.1.3.4.0.1. There are no errors in my log. Pawns miss almost every shot (it says "missed"), and melee fighters almost never hit anything. 

Edit: Following the advice from the Steam comments, I downgraded CE to  v.1.3.4.0. This seems to have fixed the issue.

Example:
 Just had 4 of my pawns simultaneously melee-fight with an ancient soldier. His melee lvl was 6, he had no armor, only hediffs were go-juice and a power arm. One of my pawns was able to hit the raider once, all other attacks missed.

Meanwhile my healthy lvl 12 shooter took a pump-action shotgun and fired 45(!) rounds at the raiders back from 2 tiles distance. All shots but one missed.

The area was lit up, there were no obstacles in the way. Other players seem to have the same problem (see comments on steam page).

**Comment by Breadbox2k19** [comment]
I need your modlist for this, try running with a modlist with only CE, then try replicating the bug.

**Comment by N7Huntsman** [comment]
Can you submit your hugslib log and mod list?

**Comment by Breadbox2k19** [comment]
Impossible to address without more relevant info, please at least have the dev mode enabled next time or send the appropriate log.
