### ISSUE TITLE
[Discussion]: VWE: Lasers is not listed in compatible mods, but claims being compatible.

### ISSUE THREAD

**Issue by Payens** [CombatExtended-Continued/CombatExtended#876]
Hey,

So, Vanilla Weapons Expanded: Lasers does state that it's compatible with CE. CE does not list it in the list of compatible mods. I don't know which one is accurate, but suspect it's just an oversight when it comes to CE's list, and that it is in fact compatible, as the other VWE modules are also compatible and listed.

Link to VWE: Lasers
https://steamcommunity.com/sharedfiles/filedetails/?id=1989352844

**Comment by Arcalane** [comment]
Probably just an accidental omission from the compatibility list. Lasers were patched with #612, #623, #630, and VWE:Frontier addon lasers were covered by #708.
