### ISSUE TITLE
[Bug]: Firing an EMP inside the area protected by a Bullet shield throws NullReferenceException

### ISSUE THREAD

**Issue by DoomOfMax97** [CombatExtended-Continued/CombatExtended#88]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**

Rimworld version: 1.1.2624 (64-bit)
Combat Extended version: 1.1.2.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Windows 10
Your mod list:
- Id: brrainz.harmony
  Name: Harmony
- Id: ludeon.rimworld
  Name: Core
- Id: ludeon.rimworld.royalty
  Name: Royalty
- Id: ceteam.combatextended
  Name: Combat Extended
- Id: ceteam.combatextendedguns
  Name: Combat Extended Guns
- Id: fluffy.modmanager
  Name: Mod Manager

**Description**
Fired an EMP grenade with the Mikor MGL inside the area protected by a Bullet shield.

**Expected behavior**
No Exception.

**To reproduce**
Shoot with an EMP grenade with the Mikor MGL inside the area protected by a Bullet shield.

**Screenshots & log dumps**
https://pastebin.com/6EhnF2TN

**Complete the following checklist**
I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- Disabled Combat Extended and attempted to reproduce the behavior without success. 
  **Not possible.**

**Comment by N7Huntsman** [comment]
This sounds like something that's going to be covered by #74 which should be merged fairly soon.

**Comment by Juanfrank** [comment]
Since #74 was already merged, could OP @DoomOfMax97 test if this is still a thing?

**Comment by DoomOfMax97** [comment]
Yep, will test it on the same save file.

**Comment by DoomOfMax97** [comment]
Bug seems to be fixed in the current development branch.
