### ISSUE TITLE
[Bug]: Change of Ammo Type not possible

### ISSUE THREAD

**Issue by Nils001** [CombatExtended-Continued/CombatExtended#882]
Rimworld version: 1.3
Combat Extended version:  4.0 (newest)
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win 10
Your mod list: Harmony, CE

**Description**
It is not possible to change the ammo type of a weapon. My pawn has an LMG from a raider which has the ammo type set to explosive ammunition. I did produce normal AP bullets but I am unable to change the ammo type when I select the pawn. It just says high explosive and that it is impossible to reload because of no ammo. But I have ammo in the warehouse.

**Expected behavior**
That I can change the ammo type so that I can use the weapon

**To reproduce**
Let you pawn pickup a weapon from a raider that has some special ammo type preselected. Then produce other ammo and try to use that.
In general I do not think that it is possible to change the ammo type at all.

**Screenshots & log dumps**
No crash. I try to add screens later

**Complete the following checklist**
I hereby verify that I have done the following:
- [ x] Confirmed that my game version and load order are correct.
- [ x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by Nils001** [comment]
Related errors are also published in the steam comment section of the mod

**Comment by Breadbox2k19** [comment]
R u sure you have the right 7.62 bullets? Happen to the best of us

**Comment by Breadbox2k19** [comment]
Yeaa, Please do at least follow up with error logs when reporting problems(at least tell us what guns you are using). Otherwise the issue would be closed.
