### ISSUE TITLE
[Patch Request]: Fortifications - Industrial

### ISSUE THREAD

**Issue by skycrossercat** [CombatExtended-Continued/CombatExtended#888]
**Mod name:** Fortifications - Industrial

**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2561619583

**Description:**
Adds some industrial fortifications and defensive buildings, also the production line of their materials. The part needs to be patched is the turrets of the mod, it adds two cannons(1 with its own shell shock system), and 3 bunker-like buildings which are actually reinforced mini turrets. (there's a minigun texture in the preview, so maybe will be added in the future)

*edit*: The author says the minigun would be in another seperated mod, and I missed the part that the cannons need to be maintained by "replacing" their barrel (unlike vanilla which just throw steel into it), which can be produced by the mod's own workbench.

**Content:**
What does the new mod contain? Check all that apply.
- [x] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [ ] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
Done. #914
