### ISSUE TITLE
Weapon 'firing' entire magazine without actually firing

### ISSUE THREAD

**Issue by KazTheMercenary** [CombatExtended-Continued/CombatExtended#902]
Hey guys.  I'm not 100% on what logs you would need, but I'm happy to provide.

This MAY not be something you care to fix or even notice, but I wanted to mention it because of the extreme behavior.

Set Up Camp.  Small map.
Characters have just arrived.  One is an Android, has Greysdale Modular Rifle.  5.56, etc, etc.  Wearing a 'can shoot outwards' shield, and a turret backpack.  (I mention all of this just in case it's relevant).

Character goes to shoot... entire magazine disappears over about 1/2 of a second.  You can watch the bar move.  Then character reloads with fresh ammo, spurts all 30 out the end of the barrel using normal aiming mechanics... but they don't fire.  No sound.  Nothin'.  

Watched him reload a few times before I wandered this way.
Possibly related:  Forming caravan seemed to demand my characters drop their ammo and 'load' it back into the caravan before it would accept the formation.

This is my first stop after that little 'run for your lives' incident.  I could NOT get them to form their caravan and just... leave.
Shoulder turret does fire.  Going to check if other weapons do as well.

**Comment by KazTheMercenary** [comment]
Ferelisks appear to be shooting blanks as well.... so they're all just staring at me, hissing, but not actually doing anything.

Grenades throw.
Turret backpack will ONLY fire on individual clicks.  But it fires, and damages.
New caravan mate that joined the dud-fight immediately lost all their ammo as soon as they finished arming.  Didn't even get to aim.

**Comment by Alicecomma** [comment]
This all happens on temporary maps?

**Comment by Breadbox2k19** [comment]
> Hey guys. I'm not 100% on what logs you would need, but I'm happy to provide.

Ideally, copy and paste the red errors here or provide the whole log if you are not able.

**Comment by KazTheMercenary** [comment]
I didn't get a CTD, or anything I'm aware of on startup.

I tried to recreate it, but wasn't able to.

And yes, only on Pristine Ruins, and a Set up Camp mini-map.

**starts digging for error files**

**Comment by KazTheMercenary** [comment]
[Player.log](https://github.com/CombatExtended-Continued/CombatExtended/files/6928900/Player.log)
[Player-prev.log](https://github.com/CombatExtended-Continued/CombatExtended/files/6928901/Player-prev.log)

**Comment by Alicecomma** [comment]
Main error:
Look rotation viewing vector is zero

**Comment by Alicecomma** [comment]
## Finding the code responsible

> Character goes to shoot... entire magazine disappears over about 1/2 of a second. You can watch the bar move.
Fired once per tick

> Then character reloads with fresh ammo, spurts all 30 out the end of the barrel using normal aiming mechanics... but they don't fire. No sound. Nothin'.

Order of things happening:

```
// CombatExtended.Verb_ShootCE
public override bool TryCastShot()
	if (base.TryCastShot())	//Try to fire a projectile
		if (base.ShooterPawn != null)	//Increment shots fired statistics
		if (base.VerbPropsCE.ejectsCasings && base.projectilePropsCE.dropsCasings)	//Drop casings
		if (base.CompAmmo != null && !base.CompAmmo.HasMagazine && base.CompAmmo.UseAmmo)
			if (!base.CompAmmo.Notify_ShotFired())	//Destroy ammo
				if (base.VerbPropsCE.soundCast != null)	//Make sound
			return base.CompAmmo.Notify_PostShotFired();	//Start reload
```

> Grenades throw.

Makes no sense, calls the same method (base.TryCastShot())!

```
// CombatExtended.Verb_ShootCEOneUse
public override bool TryCastShot()
	if (base.TryCastShot())
		if (burstShotsLeft <= 1)
			SelfConsume();
```

**Comment by Alicecomma** [comment]
Another modlist: 
[message.txt](https://github.com/CombatExtended-Continued/CombatExtended/files/6934299/message.txt)

**Comment by Alicecomma** [comment]
Other reports:

- [mvirgo95 1 Aug @ 11:56pm ](https://steamcommunity.com/sharedfiles/filedetails/comments/1631756268)
The EMP 12-Gauge shells don't seem to work with the Double Barreled Shotgun from Vanilla Factions Expanded - Settlers. Instead of firing, the gun is emptied and the pawn reloads, consuming the shells.

**Comment by KazTheMercenary** [comment]
Oh wow, I'm glad I could at least bring it up in a centralized fashion.  Anything to help you guys bug hunt.

**Comment by Alicecomma** [comment]
Karim's interpretation:

```
// CombatExtended.Verb_ShootCE
public override bool TryCastShot()
{
	if (base.CompAmmo != null && !base.CompAmmo.TryReduceAmmoCount(base.VerbPropsCE.ammoConsumedPerShotCount))
	{
		return false;
	}
	if (base.TryCastShot())
	{
```

Here, base.TryCastShot() is:

```
// CombatExtended.Verb_LaunchProjectileCE
public override bool TryCastShot()
{
	if (!TryFindCEShootLineFromTo(caster.Position, currentTarget, out var resultingLine))
	{
		return false;
	}
	if (projectilePropsCE.pelletCount < 1)
	{
		Log.Error(base.EquipmentSource.LabelCap + " tried firing with pelletCount less than 1.");
		return false;
	}
```

This can return false once in a while, and remains false throughout a burst. Then:

```
// Verse.Verb
protected void TryCastNextBurstShot()
{
	LocalTargetInfo localTargetInfo = currentTarget;
	if (Available() && TryCastShot())
	{
		burstShotsLeft--;
	}
	else
	{
		burstShotsLeft = 0;
	}
```

----

But.. burstShotsLeft _doesn't_ decrease / get set to zero, because the whole mag is emptied..?

**Comment by Breadbox2k19** [comment]
> > Ferelisks appear to be shooting blanks as well.... so they're all just staring at me, hissing, but not actually doing anything.
> 
> This is the strangest thing to note.
> 
> * FeraliskClutchMother has Verb_ShootCE firing a BulletCE
> * Feralisk has Verb_Shoot (not Verb_ShootCE!!!), firing a BulletCE
> 
> Is the problem BulletCE (ProjectileCE) related instead?

This is a simple xml error, I forgot to patch Feralisks with the CE shoot, this isn't related to the other occurances.

**Comment by Alicecomma** [comment]
> > > Ferelisks appear to be shooting blanks as well.... so they're all just staring at me, hissing, but not actually doing anything.
> > 
> > 
> > This is the strangest thing to note.
> > 
> > * FeraliskClutchMother has Verb_ShootCE firing a BulletCE
> > * Feralisk has Verb_Shoot (not Verb_ShootCE!!!), firing a BulletCE
> > 
> > Is the problem BulletCE (ProjectileCE) related instead?
> 
> This is a simple xml error, I forgot to patch Feralisks with the CE shoot, this isn't related to the other occurances.

Yes but the fact that the error also occurs if Verb_ShootCE is not present tells us Verb_ShootCE doesn't have the error

**Comment by Alicecomma** [comment]
[10:13 PM] Oscar: All right, maybe its with pawns returning from caravans
[10:32 PM] Oscar: Ok, every time I send a caravan to an ancient complex, when the caravan returns I have the issue
[10:32 PM] Oscar: Managed to repro with dev mode, but when caravan is returning home, I have to let the caravan walk a little in order to let the ancient complex map to disappear
[10:33 PM] Oscar: when the caravan arrives pawns will have the issue
[10:34 PM] Oscar: Tested at night, that may have something to do, but I think its something regarding the temporal map

Summary:
- Pawn enters temporary map
- Caravan reformed on temporary map
- While moving caravan, temporary map destroyed (from worldmap entirely)
- Enter new/existing map: pawns have issue

**Comment by Alicecomma** [comment]
Things to note:
- Guns in inventory keep storing "Position", but it is the position in whatever map they were picked up in
- Verbs are stored with 'CurrentTarget (0,0,0)', 'CurrentDestination (0,0' and 'LastShotTick -999999'
- Saving and reloading fully restores the save, but none of those inspector variables change
