### ISSUE TITLE
[Bug]: Downed pawn can be hit behind cover.

### ISSUE THREAD

**Issue by Breadbox2k19** [CombatExtended-Continued/CombatExtended#905]
Unlike hunkered pawn which cannot be hit by stray shots behind cover, downed pawns does not seem to apply and can be hit behind cover by stray shots. 

What's happening here is that bullet seems to be randomly intercepted by the downed pawn as it pass over like in vanilla, any bodypart can be hit by the stray bullet.

I hereby verify that I have done the following:
- [x] Confirmed that my game version and load order are correct.
- [x] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [x] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [x] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by AluminumAlman** [comment]
Could you please provide a screenshot of you recreating this bug?

**Comment by Alicecomma** [comment]
It may be that downed pawn heights are high - heightLaying/height = 0.3

**Comment by Breadbox2k19** [comment]
> It may be that downed pawn heights are high - heightLaying/height = 0.3; Hunkering reaches 0.45 + 0.15.

They are being hit behind embrasures and rocks so this does not seem like an issue of 0.3 being too high.

**Comment by N7Huntsman** [comment]
This appears to be fixed? In testing, the shooter does not have a line of sight on a colonist downed behind an embrasure.
