### ISSUE TITLE
[Patch Request]: compatibility patch for a new mod "[JDS] Exiled Dawn"

### ISSUE THREAD

**Issue by nomoretime0723** [CombatExtended-Continued/CombatExtended#92]
**Read and complete the template below. Requests that fail to follow the template will be deleted without warning.**
ok
**If a Patch Request (open or closed) already exists for the same mod, you may add a reaction to indicate your support. Do not create another request. Duplicate requests will be deleted.**
ok
**Title should be:** [Patch Request]: (Mod Name)

**Mod name:**
[JDS] Exiled Dawn
**Link to mod download (preferably Steam workshop or Github):**
https://steamcommunity.com/sharedfiles/filedetails/?id=2092014538&searchtext=
**Description:**
Provide a brief overview of what content the mod adds or modifies. Specify what content in particular you believe require a patch to be compatibly with Combat Extended.
it adds a faction armors and weapons

**Content:**
What does the new mod contain? Check all that apply.
- [check] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [check] New factions.
- [check] New armor or apparel.

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [check] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [check] Confirmed there are no other open Patch Requests for this mod.
- [check] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [check] **Have completed this template accurately and completely.**
- [check] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [sorry i already did wont do that again] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Breadbox2k19** [comment]
Making a patch for it wouldn’t be difficult, but it’s a ton of busy work, use other apparel and faction mod patches as template will save you alot of time.

**Comment by N7Huntsman** [comment]
For tracking purposes: #102

**Comment by onigamii** [comment]
PR has been merged and will be supported in the next release of Combat Extended.
