### ISSUE TITLE
[Patch Request]: Call of Cthulhu - Factions

### ISSUE THREAD

**Issue by Mortagonus** [CombatExtended-Continued/CombatExtended#940]
Mod name: Call of Cthulhu - Factions

[https://steamcommunity.com/sharedfiles/filedetails/?id=764375772](url)

While the lingering fear of Cthulhu is most unnerving, you are not alone. Secretive coastal fishing villages and bases of operations for The Agency have begun to appear across the rimworlds. While the villages are not fond of outsiders, should you trade with them, you might acquire large hooks, branding irons, flare guns, or even a harpoon. The Agency come attired in stylish trench coats, fedoras, bowler hats, and wield revolvers to put down potential threats.

This mod actually had a forked version at [https://steamcommunity.com/sharedfiles/filedetails/?id=2248352027](url) that implemented CE support, however it appears to generate some errors in 1.3 and the original mod's author, Jecrell, has not implemented CE support in his own main version of the mod

What does the new mod contain? Check all that apply.
- [X] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [X] New armor or apparel.

I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by N7Huntsman** [comment]
Mod has its own CE patch.
