### ISSUE TITLE
[Patch Request]: Crystalloid

### ISSUE THREAD

**Issue by Mortagonus** [CombatExtended-Continued/CombatExtended#941]
Mod name: Crystalloid

[https://steamcommunity.com/sharedfiles/filedetails/?id=1571323744](url)

Description:
This mod adds a xenohuman race of crystalline people called Crystalloids. Crystalloids are psionic beings that come from a strict collectivist civilization. Independence is limited, and some Crystalloids strive to escape and live among humans and other xenohumans.

What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [X] New animals, humanoids, or other creatures.
- [x] New factions.
- [x] New armor or apparel.

I hereby verify that I have done all of the following:
- [X] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [X] Confirmed there are no other open Patch Requests for this mod.
- [X] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended.
- [X] **Have completed this template accurately and completely.**
- [X] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [X] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Theblessedwant** [comment]
Working on it,

**Comment by Theblessedwant** [comment]
damn this patch is late

**Comment by N7Huntsman** [comment]
Mod has not been updated to 1.5.
