### ISSUE TITLE
[Patch Request] Dubs Apparel Tweaks

### ISSUE THREAD

**Issue by Ministry-of-Truth** [CombatExtended-Continued/CombatExtended#943]
**Mod name:** Dubs Apparel Tweaks

**Link to mod download (preferably Steam workshop or Github):** https://steamcommunity.com/sharedfiles/filedetails/?id=2296697286

**Description:**
A bunch of apparel tweaks: time to put apparel on, hide apparel when indoors, show hair under hats. After Show Hair with Hats' mod author confirmed that they won't be providing CE compatibility in the feature, switched to Dubs apparel tweaks. I'm only interested in hair being visible under hats which is partially broken: as of now, majority of headwear is rendered under the hair, not over it (pawn portraits aren't affected, the issue is only visible on the game map).

**Content:**
What does the new mod contain? Check all that apply.
- [ ] New weapons.
- [ ] New animals, humanoids, or other creatures.
- [ ] New factions.
- [x] New armor or apparel. (modifies rendering)

**Complete the following checklist before submitting a request.**
I hereby verify that I have done all of the following:
- [x] Searched the Steam workshop, Discord, and Github for an existing patch and not found one.
- [x] Confirmed there are no other open Patch Requests for this mod.
- [x] Confirmed the requested mod is not known to be fundamentally incompatible with Combat Extended. - Worked fine until yesterday.
- [x] **Have completed this template accurately and completely.**
- [x] **Understand that putting in a Patch Request does not guarantee a patch will be made.**
- [x] **Agree that I will not directly contact contributors to ask about patch requests.**

**Putting in request does not guarantee a patch will be made. Do not directly contact team members about Patch Requests. For smaller mods, consider reviewing the guide and making a patch yourself. If you wish to create a patch for any requested mod, there is no need to ask for permission.**

**Comment by Breadbox2k19** [comment]
Did this issue crop up recently? I remember it being ok the last time I was using it.

**Comment by Ministry-of-Truth** [comment]
Yup, it broke only recently. There was a similar issue with it about a week ago but it was reverted within hours, which makes me think that this time the change / conflict source might be permanent.
