### ISSUE TITLE
[Bug]:Minifiedthing tree cannot be selected

### ISSUE THREAD

**Issue by wuming123** [CombatExtended-Continued/CombatExtended#964]
**Complete the template below. Reports that do not follow the template will be deleted.**
**Title should be:** [Bug]: (Short description of bug)

**Specifications**
Please provide the following.

Rimworld version:1.3.3087
Combat Extended version: 1.3.4.1
Combat Extended source (Steam, GitHub, etc.):1.3.4.1
Your operating system:Windows10
Your mod list:
- Harmony
- Core
- Royalty Dlc
- HugbLib
- Combat Extended

**Description**
Minifiedthing tree cannot be selected

**Expected behavior**
I don't know

**To reproduce**
1. Unloading trees
2. Cannot select

**Screenshots & log dumps**
"MinifiedThing" error, 

**Complete the following checklist**
I hereby verify that I have done the following:
- [ x ] Confirmed that my game version and load order are correct.
- [ x ] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [ x ] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [ x ] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Comment by wuming123** [comment]
Error Message: https://pastebin.com/BSJ5ENLg

**Comment by AluminumAlman** [comment]
Could you download the development branch of Combat Extended from: https://github.com/CombatExtended-Continued/CombatExtended/archive/refs/heads/Development.zip?
It might have already been fixed with https://github.com/CombatExtended-Continued/CombatExtended/pull/949.

**Comment by KazTheMercenary** [comment]
While perhaps unrelated, there's a develpment beta of Camping Stuff that has been working on 'tent bags' that allow packing and upacking... and I'm seeing very similar behavior there.  The tent bag itself has suddenly become unclickable.

Going to give one of the newer development versions a swing to see if that solves the problem.

**Comment by wuming123** [comment]
> 能否下载《战斗扩展》的开发分支[：https://github.com/CombatExtended-Continued/CombatExtended/archive/refs/heads/Development.zip？](https://github.com/CombatExtended-Continued/CombatExtended/archive/refs/heads/Development.zip)
> 它可能已经修复了[#949。](https://github.com/CombatExtended-Continued/CombatExtended/pull/949)

OK, I'll try

**Comment by wuming123** [comment]
> *https://github.com/CombatExtended-Continued/CombatExtended/archive/refs/heads/Development.zip[#949？](https://github.com/CombatExtended-Continued/CombatExtended/archive/refs/heads/Development.zip)

ok,I'll try

**Comment by KazTheMercenary** [comment]
I just got a busted EVERYTHING.  Blank new game screen.  No pawns generated.  Trying the new build didn't seem to be successful from my end.

**Comment by AluminumAlman** [comment]
Heck, use this one https://combatextended.lp-programming.com/CombatExtended-latest.zip instead of https://github.com/CombatExtended-Continued/CombatExtended/archive/refs/heads/Development.zip.

**Comment by KazTheMercenary** [comment]
Yeah.  Not sure what that was about.  I used the latest-zip from the description page.
