### ISSUE TITLE
[Bug]: siege raids broken when ammo is turned off

### ISSUE THREAD

**Issue by Dr-Slump** [CombatExtended-Continued/CombatExtended#98]
**Specifications**
Rimworld version: 1.1.2618
Combat Extended version: 1.1.2.1
Combat Extended source (Steam, GitHub, etc.): Steam
Your operating system: Win10
Your mod list: Harmony, Combat Extended (no other mods)

**Description**
With the ammo system turned of, siege raids keep on receiving empty transport pods (mortar ammo I'm guessing), and they can never use their mortars.

**Expected behavior**
Siege raids should still be able to use mortars. Either fix the siege raids; or don't disable mortar/cannon ammo even when the ammo system is turned off. The vanilla game has mortar rounds, I think it's ok to keep them in CE.

**To reproduce**
Turn off ammo in mod settings.
If you force a siege raid, the AI will send (empty) transport pods every ~5 seconds. Once the enemy is done building, they just wander around and never use the mortars.

I hereby verify that I have done the following:
- [X] Confirmed that my game version and load order are correct.
- [X] Confirmed that I am running the appropriate and most updated version of Combat Extended and required compatibility patches.
- [X] Confirmed I am not running any mods with known incompatibilities with Combat Extended.
- [X] Disabled Combat Extended and attempted to reproduce the behavior without success.

**Note**

I downloaded the source code and tried to patch AmmoInjector.cs so that it doesn't disable mortar/cannon ammo, but I couldn't get it to work... I'll give it another shot later if I can.

**Comment by Dr-Slump** [comment]
I gave it another shot and found a working solution. That was a tricky fix, but it seems to work.

https://github.com/Dr-Slump/CombatExtended/tree/bugfix/siege-with-ammo-off

A few notes:

- I only patched the 81mm and 90mm ammo defs, since they're the only vanilla mortars/guns you can build with the base game. Not sure if the other ammo types need the same fix?
- this fix restores the vanilla game mechanics: you need to craft mortar/cannon shells. No more infinite mortar ammo!
- I haven't written C# in years, so my code is probably not great 😅

**Comment by Tourman36** [comment]
@Dr-Slump why don't you send CE a PR to they can look over the patch?

**Comment by Dr-Slump** [comment]
@Tourman36 will do! I'm still testing it, trying to make sure there's no regression.

**Comment by Dr-Slump** [comment]
I found another bug while testing, which appears to be in the current version as well: once raiders have used all the HE mortar ammo, they will not switch to other shell types (e.g. incendiary), even if there are shells next to them. And they don't receive HE shell resupply drops, so they just loiter around the mortars.
It seems that the initial ammo type is "sticky". Debugging some more...
